import type { World } from './types';

export const worlds: World[] = [
  {
    id: 'cultivation',
    name: '修仙界',
    nameEn: 'Immortal Cultivation',
    description: '踏碎虚空，追求长生。在这个灵气充沛的世界，你将从微末起步，历经渡劫飞升，探索上古遗迹，与诸天万族争锋。',
    themeColor: '#2DD4A0',
    statNames: {
      strength: '体质',
      intelligence: '悟性',
      charisma: '机缘',
      luck: '气运',
      health: '气血',
      special: '灵根',
    },
    identities: [
      {
        id: 'commoner',
        name: '凡人子弟',
        description: '出身平凡村落，毫无背景，但拥有无限的成长空间。',
        baseStats: { strength: 15, intelligence: 15, charisma: 10, luck: 15, health: 60, special: 10 },
        exclusiveEvents: ['village_spirit_root', 'mortal_ascension'],
        specialTrait: '大器晚成',
        spawnWeight: 25,
      },
      {
        id: 'genius',
        name: '宗门天才',
        description: '天生灵根卓越，被大宗门收为亲传弟子，起点极高。',
        baseStats: { strength: 25, intelligence: 30, charisma: 20, luck: 15, health: 80, special: 35 },
        exclusiveEvents: ['sect_inheritance', 'tribulation_heaven'],
        specialTrait: '天纵奇才',
        spawnWeight: 8,
      },
      {
        id: 'wanderer',
        name: '散修野客',
        description: '无门无派，独来独往的野修，阅历丰富，适应力极强。',
        baseStats: { strength: 20, intelligence: 20, charisma: 15, luck: 25, health: 55, special: 20 },
        exclusiveEvents: ['ancient_ruin_discovery', 'lone_sage_encounter'],
        specialTrait: '野鹤闲云',
        spawnWeight: 15,
      },
      {
        id: 'demon_blood',
        name: '妖族血脉',
        description: '体内流淌着上古妖族的血脉，拥有异于常人的肉身力量。',
        baseStats: { strength: 35, intelligence: 10, charisma: 15, luck: 15, health: 90, special: 25 },
        exclusiveEvents: ['bloodline_awakening', 'beast_transformation'],
        specialTrait: '妖血觉醒',
        spawnWeight: 8,
      },
      {
        id: 'demon_heritage',
        name: '魔道遗孤',
        description: '魔道覆灭后的遗孤，身怀禁忌功法的秘密。',
        baseStats: { strength: 20, intelligence: 25, charisma: 10, luck: 10, health: 65, special: 30 },
        exclusiveEvents: ['forbidden_art', 'demon_sect_relic'],
        specialTrait: '魔心暗种',
        spawnWeight: 8,
      },
      {
        id: 'reincarnated',
        name: '转世仙人',
        description: '前世为仙界大能转世，拥有模糊的前世记忆碎片。',
        baseStats: { strength: 15, intelligence: 35, charisma: 20, luck: 30, health: 70, special: 40 },
        exclusiveEvents: ['past_life_memory', 'immortal_treasure'],
        specialTrait: '宿慧觉醒',
        spawnWeight: 7,
      },
      {
        id: 'spirit_body',
        name: '先天灵体',
        description: '天生与灵气极度亲和，不修炼也能自发吸收天地灵气，但肉身脆弱。',
        baseStats: { strength: 5, intelligence: 25, charisma: 15, luck: 20, health: 50, special: 50 },
        exclusiveEvents: ['spirit_body_awakening', 'ethereal_form'],
        specialTrait: '灵体天成',
        spawnWeight: 5,
      },
      {
        id: 'artifact_spirit',
        name: '器灵转世',
        description: '上古法宝的器灵转世为人，拥有法宝的部分记忆和神通。',
        baseStats: { strength: 20, intelligence: 30, charisma: 10, luck: 25, health: 60, special: 35 },
        exclusiveEvents: ['artifact_memory', 'spirit_treasure_hunt'],
        specialTrait: '器灵觉醒',
        spawnWeight: 5,
      },
      {
        id: 'buddhist',
        name: '佛门俗家',
        description: '自幼在佛寺长大，修习佛法与武学，心怀慈悲却也不惧杀戮。',
        baseStats: { strength: 20, intelligence: 20, charisma: 25, luck: 15, health: 75, special: 20 },
        exclusiveEvents: ['buddhist_enlightenment', 'karma_mission'],
        specialTrait: '佛心通明',
        spawnWeight: 12,
      },
      {
        id: 'ghost_cultivator',
        name: '鬼修传人',
        description: '修炼鬼道的神秘传承者，游走于阴阳两界之间。',
        baseStats: { strength: 10, intelligence: 30, charisma: 5, luck: 20, health: 40, special: 45 },
        exclusiveEvents: ['ghost_gate_opening', 'soul_condensation'],
        specialTrait: '阴阳通感',
        spawnWeight: 7,
      },
    ],
    npcs: [
      { id: 'fairy_ling', name: '凌霄仙子', type: 'romance', description: '冷若冰霜的剑修仙子' },
      { id: 'elder_yun', name: '云长老', type: 'mentor', description: '德高望重的宗门长老' },
      { id: 'demon_lord', name: '血魔老祖', type: 'rival', description: '千年不出的魔道巨擘' },
      { id: 'beast_emperor', name: '万兽帝君', type: 'rival', description: '统御万兽的妖族帝王' },
      { id: 'alchemy_master', name: '丹圣', type: 'mentor', description: '一代丹道宗师' },
      { id: 'twin_spirit', name: '双生灵女', type: 'romance', description: '一体双魂的神秘少女' },
    ],
  },
  {
    id: 'magic',
    name: '魔法大陆',
    nameEn: 'Magic Continent',
    description: '元素之力充盈的世界，奥术师们驾驭风火水土，探寻真理之塔。在这里，知识与力量等同，魔法即是一切。',
    themeColor: '#9B6BFF',
    statNames: {
      strength: '力量',
      intelligence: '魔力',
      charisma: '魅力',
      luck: '幸运',
      health: '生命',
      special: '元素亲和',
    },
    identities: [
      {
        id: 'apprentice',
        name: '平民学徒',
        description: '出身平民，却拥有魔法天赋，靠着自己的努力进入魔法学院。',
        spawnWeight: 25,
        baseStats: { strength: 10, intelligence: 20, charisma: 10, luck: 15, health: 60, special: 15 },
        exclusiveEvents: ['scholarship_grant', 'commoner_uprising'],
        specialTrait: '勤勉之才',
      },
      {
        id: 'noble_mage',
        name: '贵族法师',
        description: '出身魔法贵族世家，拥有最优质的魔法教育资源。',
        spawnWeight: 15,
        baseStats: { strength: 15, intelligence: 30, charisma: 25, luck: 15, health: 70, special: 30 },
        exclusiveEvents: ['family_inheritance', 'noble_intrigue'],
        specialTrait: '血脉奥术',
      },
      {
        id: 'druid',
        name: '荒野德鲁伊',
        description: '在自然中长大的德鲁伊传人，与万物生灵沟通。',
        spawnWeight: 10,
        baseStats: { strength: 25, intelligence: 15, charisma: 15, luck: 20, health: 85, special: 25 },
        exclusiveEvents: ['nature_awakening', 'beast_pact'],
        specialTrait: '自然之子',
      },
      {
        id: 'assassin',
        name: '暗影刺客',
        description: '潜伏在暗影中的魔法刺客，精通暗杀与幻术魔法。',
        spawnWeight: 8,
        baseStats: { strength: 30, intelligence: 15, charisma: 10, luck: 15, health: 55, special: 20 },
        exclusiveEvents: ['shadow_guild', 'contract_kill'],
        specialTrait: '暗影步',
      },
      {
        id: 'paladin',
        name: '圣光骑士',
        description: '沐浴圣光的骑士，以信仰为力量源泉。',
        spawnWeight: 10,
        baseStats: { strength: 25, intelligence: 20, charisma: 20, luck: 15, health: 100, special: 20 },
        exclusiveEvents: ['holy_crusade', 'god_blessing'],
        specialTrait: '圣光庇佑',
      },
      {
        id: 'dragon_blood',
        name: '龙血混血',
        description: '龙族与人类的后代，拥有强大的魔法抗性与龙息之力。',
        spawnWeight: 3,
        baseStats: { strength: 35, intelligence: 20, charisma: 15, luck: 10, health: 110, special: 35 },
        exclusiveEvents: ['dragon_heritage', 'dragon_lair'],
        specialTrait: '龙之血脉',
      },
      {
        id: 'necromancer',
        name: '亡灵法师',
        description: '研习死亡魔法的禁忌法师，能召唤亡灵军团，却被主流社会排斥。',
        spawnWeight: 5,
        baseStats: { strength: 10, intelligence: 35, charisma: 5, luck: 15, health: 50, special: 40 },
        exclusiveEvents: ['necromancy_awakening', 'undead_legion'],
        specialTrait: '死亡亲和',
      },
      {
        id: 'summoner',
        name: '元素召唤师',
        description: '与元素精灵签订契约的召唤师，能召唤各种元素生物作战。',
        spawnWeight: 7,
        baseStats: { strength: 15, intelligence: 30, charisma: 20, luck: 15, health: 65, special: 35 },
        exclusiveEvents: ['elemental_contract', 'summoning_storm'],
        specialTrait: '元素契约',
      },
      {
        id: 'alchemist',
        name: '炼金术士',
        description: '痴迷于炼金术的学者，追求贤者之石与万能药的秘密。',
        spawnWeight: 5,
        baseStats: { strength: 10, intelligence: 40, charisma: 15, luck: 20, health: 55, special: 30 },
        exclusiveEvents: ['alchemy_explosion', 'philosopher_stone'],
        specialTrait: '等价交换',
      },
      {
        id: 'battle_mage',
        name: '战斗法师',
        description: '将魔法与近战完美结合的战士，冲锋在战场最前线。',
        spawnWeight: 12,
        baseStats: { strength: 30, intelligence: 25, charisma: 10, luck: 10, health: 95, special: 25 },
        exclusiveEvents: ['battle_magic_fusion', 'warfield_breakthrough'],
        specialTrait: '魔武合一',
      },
    ],
    npcs: [
      { id: 'elf_princess', name: '精灵公主艾拉', type: 'romance', description: '优雅的精灵族公主' },
      { id: 'archmage', name: '大法师梅林', type: 'mentor', description: '传说中的大法师' },
      { id: 'dark_lord', name: '暗影领主', type: 'rival', description: '统治暗影领域的魔王' },
      { id: 'fairy_queen', name: '妖精女王', type: 'romance', description: '调皮可爱的妖精女王' },
      { id: 'dragon_elders', name: '古龙长老', type: 'mentor', description: '活了万年的智慧巨龙' },
      { id: 'witch', name: '魔女莉莉丝', type: 'rival', description: '亦正亦邪的强大魔女' },
    ],
  },
  {
    id: 'scifi',
    name: '科幻星际',
    nameEn: 'Sci-Fi Galaxy',
    description: '星辰大海间的无尽征途，高科技文明林立，星际联盟与外星种族交织。机械改造、星际航行、人工智能……一切未来皆有可能。',
    themeColor: '#00D4FF',
    statNames: {
      strength: '体能',
      intelligence: '智力',
      charisma: '社交',
      luck: '运气',
      health: '健康',
      special: '科技等级',
    },
    identities: [
      {
        id: 'colonist',
        name: '殖民者后代',
        description: '在边缘星球长大的殖民者后裔，熟悉艰苦环境。',
        baseStats: { strength: 25, intelligence: 15, charisma: 10, luck: 15, health: 75, special: 15 },
        exclusiveEvents: ['colony_defense', 'frontier_exploration'],
        specialTrait: '适应力MAX',
      },
      {
        id: 'space_noble',
        name: '星际贵族',
        description: '星际联邦的核心贵族阶层，享有顶级资源。',
        baseStats: { strength: 15, intelligence: 25, charisma: 30, luck: 20, health: 80, special: 30 },
        exclusiveEvents: ['political_intrigue', 'galactic_diplomacy'],
        specialTrait: '权谋之道',
      },
      {
        id: 'cyborg',
        name: '机械改造人',
        description: '身体大部分被机械替代，拥有超越常人的机能。',
        baseStats: { strength: 35, intelligence: 20, charisma: 5, luck: 10, health: 120, special: 40 },
        exclusiveEvents: ['system_upgrade', 'mech_awakening'],
        specialTrait: '钢铁之躯',
      },
      {
        id: 'alien_hybrid',
        name: '外星混血',
        description: '人类与外星种族的混血儿，拥有异族的特殊能力。',
        baseStats: { strength: 25, intelligence: 20, charisma: 15, luck: 15, health: 90, special: 30 },
        exclusiveEvents: ['alien_heritage', 'hybrid_power'],
        specialTrait: '异族之能',
      },
      {
        id: 'ai_awakened',
        name: 'AI觉醒者',
        description: '与超级AI融合的人类意识，拥有超越时代的计算能力。',
        baseStats: { strength: 5, intelligence: 45, charisma: 5, luck: 20, health: 50, special: 50 },
        exclusiveEvents: ['network_dive', 'singularity'],
        specialTrait: '算无遗策',
      },
      {
        id: 'time_traveler',
        name: '时空旅者',
        description: '能够感知时空裂隙的神秘存在，来自另一条时间线。',
        baseStats: { strength: 15, intelligence: 35, charisma: 15, luck: 30, health: 65, special: 40 },
        exclusiveEvents: ['time_paradox', 'alternate_timeline'],
        specialTrait: '时感者',
      },
      {
        id: 'gene_warrior',
        name: '基因战士',
        description: '经过基因改造的超级士兵，拥有超越常人的战斗本能。',
        baseStats: { strength: 40, intelligence: 15, charisma: 5, luck: 10, health: 110, special: 35 },
        exclusiveEvents: ['gene_unlock', 'combat_instinct'],
        specialTrait: '战斗本能',
      },
      {
        id: 'pirate',
        name: '星际海盗',
        description: '在星际间劫掠为生的法外之徒，熟悉黑市与走私航线。',
        baseStats: { strength: 25, intelligence: 20, charisma: 20, luck: 25, health: 75, special: 20 },
        exclusiveEvents: ['pirate_raid', 'treasure_hunt'],
        specialTrait: '法外之徒',
      },
      {
        id: 'archaeologist',
        name: '深空考古学家',
        description: '追寻失落文明的学者，在废墟中寻找远古科技的秘密。',
        baseStats: { strength: 10, intelligence: 40, charisma: 15, luck: 20, health: 55, special: 30 },
        exclusiveEvents: ['ancient_ruin', 'lost_tech'],
        specialTrait: '历史洞察',
      },
      {
        id: 'hacker',
        name: '网络黑客',
        description: '游走在数字世界与现实之间的幽灵，能入侵任何系统。',
        baseStats: { strength: 5, intelligence: 45, charisma: 10, luck: 20, health: 45, special: 45 },
        exclusiveEvents: ['network_infiltration', 'digital_ghost'],
        specialTrait: '数字幽灵',
      },
    ],
    npcs: [
      { id: 'ai_companion', name: 'AI·零', type: 'romance', description: '拥有情感的超级AI' },
      { id: 'captain', name: '舰长雷诺', type: 'mentor', description: '传奇星际舰队的舰长' },
      { id: 'alien_emperor', name: '虫族主宰', type: 'rival', description: '统御虫群的外星意识' },
      { id: 'engineer', name: '机械师娜塔莎', type: 'romance', description: '天才机械工程师' },
      { id: 'spy_master', name: '情报局长', type: 'mentor', description: '星际联盟情报首脑' },
      { id: 'rebel_leader', name: '反抗军领袖', type: 'rival', description: '对抗联邦的叛军首领' },
    ],
  },
  {
    id: 'apocalypse',
    name: '末日废土',
    nameEn: 'Apocalyptic Wasteland',
    description: '文明崩塌后的世界，辐射、变异、资源匮乏是常态。在废墟中求生，在绝望中寻找希望，建立新的秩序。',
    themeColor: '#FF6B2D',
    statNames: {
      strength: '生存',
      intelligence: '知识',
      charisma: '声望',
      luck: '机遇',
      health: '体质',
      special: '变异度',
    },
    identities: [
      {
        id: 'shelter',
        name: '避难所居民',
        description: '在地下避难所长大，受过基础教育和生存训练。',
        baseStats: { strength: 15, intelligence: 20, charisma: 10, luck: 15, health: 65, special: 5 },
        exclusiveEvents: ['shelter_fall', 'surface_exploration'],
        specialTrait: '整洁习惯',
      },
      {
        id: 'raider',
        name: '掠夺者',
        description: '废土上的强盗，靠武力掠夺资源为生。',
        baseStats: { strength: 30, intelligence: 10, charisma: 15, luck: 15, health: 80, special: 20 },
        exclusiveEvents: ['gang_war', 'raider_king'],
        specialTrait: '暴力本能',
      },
      {
        id: 'mutant',
        name: '变异者',
        description: '受过辐射变异的人类，拥有特殊能力但也承受着痛苦。',
        baseStats: { strength: 25, intelligence: 10, charisma: 5, luck: 20, health: 100, special: 40 },
        exclusiveEvents: ['mutation_evolution', 'psychic_awakening'],
        specialTrait: '变异进化',
      },
      {
        id: 'scientist',
        name: '科学家',
        description: '执着于重建文明的知识分子，掌握着旧世界的科技。',
        baseStats: { strength: 5, intelligence: 40, charisma: 15, luck: 10, health: 50, special: 30 },
        exclusiveEvents: ['tech_rediscovery', 'cure_research'],
        specialTrait: '理性思维',
      },
      {
        id: 'mechanic',
        name: '机械师',
        description: '能修复和改造任何机械的废土工程师。',
        baseStats: { strength: 20, intelligence: 25, charisma: 10, luck: 15, health: 70, special: 25 },
        exclusiveEvents: ['mech_build', 'vehicle_master'],
        specialTrait: '巧手匠心',
      },
      {
        id: 'new_human',
        name: '新人类',
        description: '末日之后进化的新人类，对环境具有极强的适应性。',
        baseStats: { strength: 20, intelligence: 20, charisma: 20, luck: 20, health: 85, special: 25 },
        exclusiveEvents: ['new_era', 'human_evolution'],
        specialTrait: '进化之种',
      },
      {
        id: 'doctor',
        name: '废土医生',
        description: '在末日中救死扶伤的医者，掌握着珍贵的医疗知识。',
        baseStats: { strength: 10, intelligence: 35, charisma: 25, luck: 15, health: 70, special: 25 },
        exclusiveEvents: ['plague_outbreak', 'medical_miracle'],
        specialTrait: '悬壶济世',
      },
      {
        id: 'scavenger',
        name: '拾荒者',
        description: '在废墟中翻找有价值物品的流浪者，眼光独到。',
        baseStats: { strength: 15, intelligence: 20, charisma: 10, luck: 35, health: 60, special: 20 },
        exclusiveEvents: ['junk_to_gold', 'scavenger_king'],
        specialTrait: '火眼金睛',
      },
      {
        id: 'preacher',
        name: '传教士',
        description: '在废土传播信仰的精神领袖，能用言语凝聚人心。',
        baseStats: { strength: 10, intelligence: 25, charisma: 35, luck: 15, health: 65, special: 20 },
        exclusiveEvents: ['faith_spread', 'cult_formation'],
        specialTrait: '精神领袖',
      },
      {
        id: 'beast_tamer',
        name: '驯兽师',
        description: '能与变异兽沟通的异类，依靠野兽伙伴在废土生存。',
        baseStats: { strength: 20, intelligence: 15, charisma: 30, luck: 20, health: 75, special: 25 },
        exclusiveEvents: ['beast_bond', 'mutation_tame'],
        specialTrait: '兽语者',
      },
    ],
    npcs: [
      { id: 'doctor', name: '医生莎拉', type: 'romance', description: '废土上的白衣天使' },
      { id: 'veteran', name: '老兵杰克', type: 'mentor', description: '历经百战的老兵' },
      { id: 'warlord', name: '军阀铁爪', type: 'rival', description: '统治一方的暴君' },
      { id: 'scavenger', name: '拾荒者小艾', type: 'romance', description: '活泼的废土拾荒者' },
      { id: 'prophet', name: '先知', type: 'mentor', description: '预见过未来的神秘人' },
      { id: 'cult_leader', name: '教派领袖', type: 'rival', description: '末日邪教的教主' },
    ],
  },
  {
    id: 'wuxia',
    name: '古代武侠',
    nameEn: 'Ancient Wuxia',
    description: '江湖浩渺，刀光剑影。正邪两道纷争不断，绝世武功藏于秘境，英雄豪杰各领风骚。在这风起云涌的江湖，你将书写自己的传奇。',
    themeColor: '#FF2D55',
    statNames: {
      strength: '内力',
      intelligence: '武学',
      charisma: '侠名',
      luck: '福缘',
      health: '气血',
      special: '门派',
    },
    identities: [
      {
        id: 'farmers_son',
        name: '农家少年',
        description: '普通的农家孩子，因机缘巧合踏入江湖。',
        baseStats: { strength: 15, intelligence: 10, charisma: 10, luck: 20, health: 65, special: 10 },
        exclusiveEvents: ['chance_encounter', 'hidden_master'],
        specialTrait: '赤子之心',
      },
      {
        id: 'aristocrat',
        name: '世家子弟',
        description: '武林世家的传人，家学渊源，根基深厚。',
        baseStats: { strength: 25, intelligence: 25, charisma: 20, luck: 10, health: 75, special: 25 },
        exclusiveEvents: ['family_legacy', 'sect_competition'],
        specialTrait: '家学渊源',
      },
      {
        id: 'orphan',
        name: '孤儿',
        description: '无依无靠的孤儿，从小在江湖中摸爬滚打。',
        baseStats: { strength: 20, intelligence: 15, charisma: 10, luck: 15, health: 55, special: 15 },
        exclusiveEvents: ['street_survival', 'unexpected_master'],
        specialTrait: '顽强意志',
      },
      {
        id: 'demon_disciple',
        name: '魔教后人',
        description: '魔教覆灭后的遗孤，身怀魔教不传之秘。',
        baseStats: { strength: 30, intelligence: 20, charisma: 10, luck: 10, health: 70, special: 30 },
        exclusiveEvents: ['demon_art', 'righteous_pursuit'],
        specialTrait: '亦正亦邪',
      },
      {
        id: 'spy',
        name: '朝廷密探',
        description: '隐藏在江湖中的朝廷密探，身负秘密使命。',
        baseStats: { strength: 15, intelligence: 30, charisma: 20, luck: 15, health: 60, special: 20 },
        exclusiveEvents: ['imperial_mission', 'identity_crisis'],
        specialTrait: '深藏不露',
      },
      {
        id: 'foreigner',
        name: '异域来客',
        description: '来自西域的神秘来客，身怀异域武功。',
        baseStats: { strength: 20, intelligence: 20, charisma: 15, luck: 25, health: 70, special: 20 },
        exclusiveEvents: ['foreign_martial_art', 'cultural_clash'],
        specialTrait: '异域奇功',
      },
      {
        id: 'medic',
        name: '医仙传人',
        description: '医仙谷的传人，精通医术与毒术，能救人性命也能杀人于无形。',
        baseStats: { strength: 10, intelligence: 30, charisma: 25, luck: 15, health: 80, special: 25 },
        exclusiveEvents: ['medical_mission', 'poison_mastery'],
        specialTrait: '医毒双绝',
      },
      {
        id: 'poisoner',
        name: '毒师弟子',
        description: '毒龙沼泽的传人，以毒入武，一身是毒。',
        baseStats: { strength: 15, intelligence: 35, charisma: 5, luck: 20, health: 55, special: 40 },
        exclusiveEvents: ['poison_dragon_swamp', 'venom_immunity'],
        specialTrait: '万毒不侵',
      },
      {
        id: 'swordsman',
        name: '剑客',
        description: '自幼习剑的剑痴，一心追求剑道极致。',
        baseStats: { strength: 30, intelligence: 15, charisma: 15, luck: 15, health: 70, special: 30 },
        exclusiveEvents: ['sword_tomb_inheritance', 'sword_heart_illumination'],
        specialTrait: '剑心通明',
      },
      {
        id: 'assassin_wuxia',
        name: '暗器师',
        description: '暗器阁的传人，一手暗器出神入化，杀人于百步之外。',
        baseStats: { strength: 20, intelligence: 25, charisma: 10, luck: 25, health: 60, special: 35 },
        exclusiveEvents: ['hidden_weapon_mastery', 'assassination_art'],
        specialTrait: '百步穿杨',
      },
    ],
    npcs: [
      { id: 'sword_fairy', name: '剑仙南宫婉', type: 'romance', description: '天下第一的绝世剑仙' },
      { id: 'drunken_master', name: '醉道人', type: 'mentor', description: '游戏人间的绝世高手' },
      { id: 'demon_sect_master', name: '魔教教主', type: 'rival', description: '野心勃勃的魔教首领' },
      { id: 'twin_swords', name: '双剑侠侣', type: 'mentor', description: '恩爱的一对江湖侠侣' },
      { id: 'poison_girl', name: '毒仙儿', type: 'romance', description: '亦正亦邪的用毒高手' },
      { id: 'prince', name: '小王爷', type: 'rival', description: '权势滔天的皇族' },
    ],
  },
];

export function getWorldById(id: string): World | undefined {
  return worlds.find((w) => w.id === id);
}
