import type { World } from './types';

export const worlds: World[] = [
  {
    id: 'cultivation',
    name: '修仙界',
    nameEn: 'Immortal Cultivation',
    description: '踏碎虚空，追求长生。在这个灵气充沛的世界，你将从微末起步，历经渡劫飞升，探索上古遗迹，与诸天万族争锋。',
    themeColor: '#2DD4A0',
    statNames: {
      strength: '体质',
      intelligence: '悟性',
      charisma: '机缘',
      luck: '气运',
      health: '气血',
      special: '灵根',
    },
    identities: [
      {
        id: 'commoner',
        name: '凡人子弟',
        description: '出身平凡村落，毫无背景，但拥有无限的成长空间。',
        baseStats: { strength: 15, intelligence: 15, charisma: 10, luck: 15, health: 60, special: 10 },
        exclusiveEvents: ['village_spirit_root', 'mortal_ascension'],
        specialTrait: '大器晚成',
        spawnWeight: 25,
      },
      {
        id: 'genius',
        name: '宗门天才',
        description: '天生灵根卓越，被大宗门收为亲传弟子，起点极高。',
        baseStats: { strength: 25, intelligence: 30, charisma: 20, luck: 15, health: 80, special: 35 },
        exclusiveEvents: ['sect_inheritance', 'tribulation_heaven'],
        specialTrait: '天纵奇才',
        spawnWeight: 8,
      },
      {
        id: 'wanderer',
        name: '散修野客',
        description: '无门无派，独来独往的野修，阅历丰富，适应力极强。',
        baseStats: { strength: 20, intelligence: 20, charisma: 15, luck: 25, health: 55, special: 20 },
        exclusiveEvents: ['ancient_ruin_discovery', 'lone_sage_encounter'],
        specialTrait: '野鹤闲云',
        spawnWeight: 15,
      },
      {
        id: 'demon_blood',
        name: '妖族血脉',
        description: '体内流淌着上古妖族的血脉，拥有异于常人的肉身力量。',
        baseStats: { strength: 35, intelligence: 10, charisma: 15, luck: 15, health: 90, special: 25 },
        exclusiveEvents: ['bloodline_awakening', 'beast_transformation'],
        specialTrait: '妖血觉醒',
        spawnWeight: 8,
      },
      {
        id: 'demon_heritage',
        name: '魔道遗孤',
        description: '魔道覆灭后的遗孤，身怀禁忌功法的秘密。',
        baseStats: { strength: 20, intelligence: 25, charisma: 10, luck: 10, health: 65, special: 30 },
        exclusiveEvents: ['forbidden_art', 'demon_sect_relic'],
        specialTrait: '魔心暗种',
        spawnWeight: 8,
      },
      {
        id: 'reincarnated',
        name: '转世仙人',
        description: '前世为仙界大能转世，拥有模糊的前世记忆碎片。',
        baseStats: { strength: 15, intelligence: 35, charisma: 20, luck: 30, health: 70, special: 40 },
        exclusiveEvents: ['past_life_memory', 'immortal_treasure'],
        specialTrait: '宿慧觉醒',
        spawnWeight: 7,
      },
      {
        id: 'spirit_body',
        name: '先天灵体',
        description: '天生与灵气极度亲和，不修炼也能自发吸收天地灵气，但肉身脆弱。',
        baseStats: { strength: 5, intelligence: 25, charisma: 15, luck: 20, health: 50, special: 50 },
        exclusiveEvents: ['spirit_body_awakening', 'ethereal_form'],
        specialTrait: '灵体天成',
        spawnWeight: 5,
      },
      {
        id: 'artifact_spirit',
        name: '器灵转世',
        description: '上古法宝的器灵转世为人，拥有法宝的部分记忆和神通。',
        baseStats: { strength: 20, intelligence: 30, charisma: 10, luck: 25, health: 60, special: 35 },
        exclusiveEvents: ['artifact_memory', 'spirit_treasure_hunt'],
        specialTrait: '器灵觉醒',
        spawnWeight: 5,
      },
      {
        id: 'buddhist',
        name: '佛门俗家',
        description: '自幼在佛寺长大，修习佛法与武学，心怀慈悲却也不惧杀戮。',
        baseStats: { strength: 20, intelligence: 20, charisma: 25, luck: 15, health: 75, special: 20 },
        exclusiveEvents: ['buddhist_enlightenment', 'karma_mission'],
        specialTrait: '佛心通明',
        spawnWeight: 12,
      },
      {
        id: 'ghost_cultivator',
        name: '鬼修传人',
        description: '修炼鬼道的神秘传承者，游走于阴阳两界之间。',
        baseStats: { strength: 10, intelligence: 30, charisma: 5, luck: 20, health: 40, special: 45 },
        exclusiveEvents: ['ghost_gate_opening', 'soul_condensation'],
        specialTrait: '阴阳通感',
        spawnWeight: 7,
      },
    ],
    npcs: [
      { id: 'fairy_ling', name: '凌霄仙子', type: 'romance', description: '冷若冰霜的剑修仙子', avatar: '💕', introEvent: '你在山巅偶遇凌霄仙子，她冷若冰霜的目光让你心神一震。', maxRelationshipEvents: ['凌霄仙子为你挡下天劫，衣袂飘飘间，你们的心终于贴在了一起。'] },
      { id: 'elder_yun', name: '云长老', type: 'mentor', description: '德高望重的宗门长老', avatar: '👤', introEvent: '云长老在山门下打量着你，眼中闪过一丝欣慰。', maxRelationshipEvents: ['云长老将毕生修为传于你，含笑而逝。'] },
      { id: 'demon_lord', name: '血魔老祖', type: 'rival', description: '千年不出的魔道巨擘', avatar: '⚔', introEvent: '血魔老祖的威压让你窒息，他冷笑一声："有趣的蝼蚁。"', maxRelationshipEvents: ['血魔老祖最终认可了你的实力，将魔道秘典赠予你。'] },
      { id: 'beast_emperor', name: '万兽帝君', type: 'rival', description: '统御万兽的妖族帝王', avatar: '⚔', introEvent: '万兽帝君的兽瞳注视着你，仿佛在审视一件猎物。', maxRelationshipEvents: ['万兽帝君与你把酒言欢，承认你是万族之中最值得尊敬的对手。'] },
      { id: 'alchemy_master', name: '丹圣', type: 'mentor', description: '一代丹道宗师', avatar: '👤', introEvent: '丹圣闻到你身上的药香，难得地露出一丝笑意。', maxRelationshipEvents: ['丹圣将丹炉与毕生心血交付于你，从此隐退山林。'] },
      { id: 'twin_spirit', name: '双生灵女', type: 'romance', description: '一体双魂的神秘少女', avatar: '💕', introEvent: '双生灵女的两双眼睛同时望向你，一个好奇，一个警惕。', maxRelationshipEvents: ['双生灵女终于合二为一，对你敞开心扉，愿随你浪迹天涯。'] },
    ],
  },
  {
    id: 'magic',
    name: '魔法大陆',
    nameEn: 'Magic Continent',
    description: '元素之力充盈的世界，奥术师们驾驭风火水土，探寻真理之塔。在这里，知识与力量等同，魔法即是一切。',
    themeColor: '#9B6BFF',
    statNames: {
      strength: '力量',
      intelligence: '魔力',
      charisma: '魅力',
      luck: '幸运',
      health: '生命',
      special: '元素亲和',
    },
    identities: [
      {
        id: 'apprentice',
        name: '平民学徒',
        description: '出身平民，却拥有魔法天赋，靠着自己的努力进入魔法学院。',
        spawnWeight: 25,
        baseStats: { strength: 10, intelligence: 20, charisma: 10, luck: 15, health: 60, special: 15 },
        exclusiveEvents: ['scholarship_grant', 'commoner_uprising'],
        specialTrait: '勤勉之才',
      },
      {
        id: 'noble_mage',
        name: '贵族法师',
        description: '出身魔法贵族世家，拥有最优质的魔法教育资源。',
        spawnWeight: 15,
        baseStats: { strength: 15, intelligence: 30, charisma: 25, luck: 15, health: 70, special: 30 },
        exclusiveEvents: ['family_inheritance', 'noble_intrigue'],
        specialTrait: '血脉奥术',
      },
      {
        id: 'druid',
        name: '荒野德鲁伊',
        description: '在自然中长大的德鲁伊传人，与万物生灵沟通。',
        spawnWeight: 10,
        baseStats: { strength: 25, intelligence: 15, charisma: 15, luck: 20, health: 85, special: 25 },
        exclusiveEvents: ['nature_awakening', 'beast_pact'],
        specialTrait: '自然之子',
      },
      {
        id: 'assassin',
        name: '暗影刺客',
        description: '潜伏在暗影中的魔法刺客，精通暗杀与幻术魔法。',
        spawnWeight: 8,
        baseStats: { strength: 30, intelligence: 15, charisma: 10, luck: 15, health: 55, special: 20 },
        exclusiveEvents: ['shadow_guild', 'contract_kill'],
        specialTrait: '暗影步',
      },
      {
        id: 'paladin',
        name: '圣光骑士',
        description: '沐浴圣光的骑士，以信仰为力量源泉。',
        spawnWeight: 10,
        baseStats: { strength: 25, intelligence: 20, charisma: 20, luck: 15, health: 100, special: 20 },
        exclusiveEvents: ['holy_crusade', 'god_blessing'],
        specialTrait: '圣光庇佑',
      },
      {
        id: 'dragon_blood',
        name: '龙血混血',
        description: '龙族与人类的后代，拥有强大的魔法抗性与龙息之力。',
        spawnWeight: 3,
        baseStats: { strength: 35, intelligence: 20, charisma: 15, luck: 10, health: 110, special: 35 },
        exclusiveEvents: ['dragon_heritage', 'dragon_lair'],
        specialTrait: '龙之血脉',
      },
      {
        id: 'necromancer',
        name: '亡灵法师',
        description: '研习死亡魔法的禁忌法师，能召唤亡灵军团，却被主流社会排斥。',
        spawnWeight: 5,
        baseStats: { strength: 10, intelligence: 35, charisma: 5, luck: 15, health: 50, special: 40 },
        exclusiveEvents: ['necromancy_awakening', 'undead_legion'],
        specialTrait: '死亡亲和',
      },
      {
        id: 'summoner',
        name: '元素召唤师',
        description: '与元素精灵签订契约的召唤师，能召唤各种元素生物作战。',
        spawnWeight: 7,
        baseStats: { strength: 15, intelligence: 30, charisma: 20, luck: 15, health: 65, special: 35 },
        exclusiveEvents: ['elemental_contract', 'summoning_storm'],
        specialTrait: '元素契约',
      },
      {
        id: 'alchemist',
        name: '炼金术士',
        description: '痴迷于炼金术的学者，追求贤者之石与万能药的秘密。',
        spawnWeight: 5,
        baseStats: { strength: 10, intelligence: 40, charisma: 15, luck: 20, health: 55, special: 30 },
        exclusiveEvents: ['alchemy_explosion', 'philosopher_stone'],
        specialTrait: '等价交换',
      },
      {
        id: 'battle_mage',
        name: '战斗法师',
        description: '将魔法与近战完美结合的战士，冲锋在战场最前线。',
        spawnWeight: 12,
        baseStats: { strength: 30, intelligence: 25, charisma: 10, luck: 10, health: 95, special: 25 },
        exclusiveEvents: ['battle_magic_fusion', 'warfield_breakthrough'],
        specialTrait: '魔武合一',
      },
    ],
    npcs: [
      { id: 'elf_princess', name: '精灵公主艾拉', type: 'romance', description: '优雅的精灵族公主', avatar: '💕', introEvent: '精灵公主艾拉在花园中回眸一笑，你仿佛看见了整个春天。', maxRelationshipEvents: ['艾拉在月光下向你坦白心意，愿放弃王位与你私奔。'] },
      { id: 'archmage', name: '大法师梅林', type: 'mentor', description: '传说中的大法师', avatar: '👤', introEvent: '大法师梅林从书卷中抬头，目光如炬地审视着你。', maxRelationshipEvents: ['梅林将真理之塔的钥匙交给你，任命你为接班人。'] },
      { id: 'dark_lord', name: '暗影领主', type: 'rival', description: '统治暗影领域的魔王', avatar: '⚔', introEvent: '暗影领主的笑声在虚空中回荡："又一个送死的。"', maxRelationshipEvents: ['暗影领主摘下头盔，向你伸出手："一起统治这个世界吧。"'] },
      { id: 'fairy_queen', name: '妖精女王', type: 'romance', description: '调皮可爱的妖精女王', avatar: '💕', introEvent: '妖精女王在你鼻尖上轻点一下，笑嘻嘻地消失在花丛中。', maxRelationshipEvents: ['妖精女王为你举办了一场盛大的妖精婚礼，全森林的精灵都来祝福。'] },
      { id: 'dragon_elders', name: '古龙长老', type: 'mentor', description: '活了万年的智慧巨龙', avatar: '👤', introEvent: '古龙长老睁开万年未曾睁开的双眼，低沉地说："终于等到你了。"', maxRelationshipEvents: ['古龙长老将龙语魔法与龙晶赠予你，称你为龙之传人。'] },
      { id: 'witch', name: '魔女莉莉丝', type: 'rival', description: '亦正亦邪的强大魔女', avatar: '⚔', introEvent: '魔女莉莉丝把玩着魔杖，嘴角勾起一抹危险的弧度。', maxRelationshipEvents: ['莉莉丝在你唇上印下一个吻："我决定了，你就是我的共犯了。"'] },
    ],
  },
  {
    id: 'scifi',
    name: '科幻星际',
    nameEn: 'Sci-Fi Galaxy',
    description: '星辰大海间的无尽征途，高科技文明林立，星际联盟与外星种族交织。机械改造、星际航行、人工智能……一切未来皆有可能。',
    themeColor: '#00D4FF',
    statNames: {
      strength: '体能',
      intelligence: '智力',
      charisma: '社交',
      luck: '运气',
      health: '健康',
      special: '科技等级',
    },
    identities: [
      {
        id: 'colonist',
        name: '殖民者后代',
        description: '在边缘星球长大的殖民者后裔，熟悉艰苦环境。',
        baseStats: { strength: 25, intelligence: 15, charisma: 10, luck: 15, health: 75, special: 15 },
        exclusiveEvents: ['colony_defense', 'frontier_exploration'],
        specialTrait: '适应力MAX',
      },
      {
        id: 'space_noble',
        name: '星际贵族',
        description: '星际联邦的核心贵族阶层，享有顶级资源。',
        baseStats: { strength: 15, intelligence: 25, charisma: 30, luck: 20, health: 80, special: 30 },
        exclusiveEvents: ['political_intrigue', 'galactic_diplomacy'],
        specialTrait: '权谋之道',
      },
      {
        id: 'cyborg',
        name: '机械改造人',
        description: '身体大部分被机械替代，拥有超越常人的机能。',
        baseStats: { strength: 35, intelligence: 20, charisma: 5, luck: 10, health: 120, special: 40 },
        exclusiveEvents: ['system_upgrade', 'mech_awakening'],
        specialTrait: '钢铁之躯',
      },
      {
        id: 'alien_hybrid',
        name: '外星混血',
        description: '人类与外星种族的混血儿，拥有异族的特殊能力。',
        baseStats: { strength: 25, intelligence: 20, charisma: 15, luck: 15, health: 90, special: 30 },
        exclusiveEvents: ['alien_heritage', 'hybrid_power'],
        specialTrait: '异族之能',
      },
      {
        id: 'ai_awakened',
        name: 'AI觉醒者',
        description: '与超级AI融合的人类意识，拥有超越时代的计算能力。',
        baseStats: { strength: 5, intelligence: 45, charisma: 5, luck: 20, health: 50, special: 50 },
        exclusiveEvents: ['network_dive', 'singularity'],
        specialTrait: '算无遗策',
      },
      {
        id: 'time_traveler',
        name: '时空旅者',
        description: '能够感知时空裂隙的神秘存在，来自另一条时间线。',
        baseStats: { strength: 15, intelligence: 35, charisma: 15, luck: 30, health: 65, special: 40 },
        exclusiveEvents: ['time_paradox', 'alternate_timeline'],
        specialTrait: '时感者',
      },
      {
        id: 'gene_warrior',
        name: '基因战士',
        description: '经过基因改造的超级士兵，拥有超越常人的战斗本能。',
        baseStats: { strength: 40, intelligence: 15, charisma: 5, luck: 10, health: 110, special: 35 },
        exclusiveEvents: ['gene_unlock', 'combat_instinct'],
        specialTrait: '战斗本能',
      },
      {
        id: 'pirate',
        name: '星际海盗',
        description: '在星际间劫掠为生的法外之徒，熟悉黑市与走私航线。',
        baseStats: { strength: 25, intelligence: 20, charisma: 20, luck: 25, health: 75, special: 20 },
        exclusiveEvents: ['pirate_raid', 'treasure_hunt'],
        specialTrait: '法外之徒',
      },
      {
        id: 'archaeologist',
        name: '深空考古学家',
        description: '追寻失落文明的学者，在废墟中寻找远古科技的秘密。',
        baseStats: { strength: 10, intelligence: 40, charisma: 15, luck: 20, health: 55, special: 30 },
        exclusiveEvents: ['ancient_ruin', 'lost_tech'],
        specialTrait: '历史洞察',
      },
      {
        id: 'hacker',
        name: '网络黑客',
        description: '游走在数字世界与现实之间的幽灵，能入侵任何系统。',
        baseStats: { strength: 5, intelligence: 45, charisma: 10, luck: 20, health: 45, special: 45 },
        exclusiveEvents: ['network_infiltration', 'digital_ghost'],
        specialTrait: '数字幽灵',
      },
    ],
    npcs: [
      { id: 'ai_companion', name: 'AI·零', type: 'romance', description: '拥有情感的超级AI', avatar: '💕', introEvent: 'AI·零的全息影像在你面前闪烁，声音温柔得不像机器："你好，我是零。"', maxRelationshipEvents: ['零将自己的核心代码与你共享，宣布永远与你同在。'] },
      { id: 'captain', name: '舰长雷诺', type: 'mentor', description: '传奇星际舰队的舰长', avatar: '👤', introEvent: '舰长雷诺拍了拍你的肩膀："小子，有胆量跟我上船吗？"', maxRelationshipEvents: ['雷诺将旗舰的指挥权交给你，自己则退居幕后。'] },
      { id: 'alien_emperor', name: '虫族主宰', type: 'rival', description: '统御虫群的外星意识', avatar: '⚔', introEvent: '虫族主宰的意识如潮水般涌入你的脑海："有趣的小虫子。"', maxRelationshipEvents: ['虫族主宰与你达成停战协议，视你为唯一的平等对手。'] },
      { id: 'engineer', name: '机械师娜塔莎', type: 'romance', description: '天才机械工程师', avatar: '💕', introEvent: '娜塔莎从机甲下面探出头，满脸油污却笑得灿烂："要帮我递个扳手吗？"', maxRelationshipEvents: ['娜塔莎为你打造了一台独一无二的机甲，上面刻着你的名字。'] },
      { id: 'spy_master', name: '情报局长', type: 'mentor', description: '星际联盟情报首脑', avatar: '👤', introEvent: '情报局长从阴影中走出，将一份加密档案放在你面前。', maxRelationshipEvents: ['情报局长向你透露了联邦最大的秘密，并任命你为继任者。'] },
      { id: 'rebel_leader', name: '反抗军领袖', type: 'rival', description: '对抗联邦的叛军首领', avatar: '⚔', introEvent: '反抗军领袖用枪指着你的头，眼神中却有一丝欣赏。', maxRelationshipEvents: ['反抗军领袖放下武器，与你并肩站在废墟之上，共创新秩序。'] },
    ],
  },
  {
    id: 'apocalypse',
    name: '末日废土',
    nameEn: 'Apocalyptic Wasteland',
    description: '文明崩塌后的世界，辐射、变异、资源匮乏是常态。在废墟中求生，在绝望中寻找希望，建立新的秩序。',
    themeColor: '#FF6B2D',
    statNames: {
      strength: '生存',
      intelligence: '知识',
      charisma: '声望',
      luck: '机遇',
      health: '体质',
      special: '变异度',
    },
    identities: [
      {
        id: 'shelter',
        name: '避难所居民',
        description: '在地下避难所长大，受过基础教育和生存训练。',
        baseStats: { strength: 15, intelligence: 20, charisma: 10, luck: 15, health: 65, special: 5 },
        exclusiveEvents: ['shelter_fall', 'surface_exploration'],
        specialTrait: '整洁习惯',
      },
      {
        id: 'raider',
        name: '掠夺者',
        description: '废土上的强盗，靠武力掠夺资源为生。',
        baseStats: { strength: 30, intelligence: 10, charisma: 15, luck: 15, health: 80, special: 20 },
        exclusiveEvents: ['gang_war', 'raider_king'],
        specialTrait: '暴力本能',
      },
      {
        id: 'mutant',
        name: '变异者',
        description: '受过辐射变异的人类，拥有特殊能力但也承受着痛苦。',
        baseStats: { strength: 25, intelligence: 10, charisma: 5, luck: 20, health: 100, special: 40 },
        exclusiveEvents: ['mutation_evolution', 'psychic_awakening'],
        specialTrait: '变异进化',
      },
      {
        id: 'scientist',
        name: '科学家',
        description: '执着于重建文明的知识分子，掌握着旧世界的科技。',
        baseStats: { strength: 5, intelligence: 40, charisma: 15, luck: 10, health: 50, special: 30 },
        exclusiveEvents: ['tech_rediscovery', 'cure_research'],
        specialTrait: '理性思维',
      },
      {
        id: 'mechanic',
        name: '机械师',
        description: '能修复和改造任何机械的废土工程师。',
        baseStats: { strength: 20, intelligence: 25, charisma: 10, luck: 15, health: 70, special: 25 },
        exclusiveEvents: ['mech_build', 'vehicle_master'],
        specialTrait: '巧手匠心',
      },
      {
        id: 'new_human',
        name: '新人类',
        description: '末日之后进化的新人类，对环境具有极强的适应性。',
        baseStats: { strength: 20, intelligence: 20, charisma: 20, luck: 20, health: 85, special: 25 },
        exclusiveEvents: ['new_era', 'human_evolution'],
        specialTrait: '进化之种',
      },
      {
        id: 'doctor',
        name: '废土医生',
        description: '在末日中救死扶伤的医者，掌握着珍贵的医疗知识。',
        baseStats: { strength: 10, intelligence: 35, charisma: 25, luck: 15, health: 70, special: 25 },
        exclusiveEvents: ['plague_outbreak', 'medical_miracle'],
        specialTrait: '悬壶济世',
      },
      {
        id: 'scavenger',
        name: '拾荒者',
        description: '在废墟中翻找有价值物品的流浪者，眼光独到。',
        baseStats: { strength: 15, intelligence: 20, charisma: 10, luck: 35, health: 60, special: 20 },
        exclusiveEvents: ['junk_to_gold', 'scavenger_king'],
        specialTrait: '火眼金睛',
      },
      {
        id: 'preacher',
        name: '传教士',
        description: '在废土传播信仰的精神领袖，能用言语凝聚人心。',
        baseStats: { strength: 10, intelligence: 25, charisma: 35, luck: 15, health: 65, special: 20 },
        exclusiveEvents: ['faith_spread', 'cult_formation'],
        specialTrait: '精神领袖',
      },
      {
        id: 'beast_tamer',
        name: '驯兽师',
        description: '能与变异兽沟通的异类，依靠野兽伙伴在废土生存。',
        baseStats: { strength: 20, intelligence: 15, charisma: 30, luck: 20, health: 75, special: 25 },
        exclusiveEvents: ['beast_bond', 'mutation_tame'],
        specialTrait: '兽语者',
      },
    ],
    npcs: [
      { id: 'doctor', name: '医生莎拉', type: 'romance', description: '废土上的白衣天使', avatar: '💕', introEvent: '莎拉在帐篷里为你包扎伤口，温柔得像一束光。', maxRelationshipEvents: ['莎拉在废墟中为你戴上了一枚戒指，那是她最后的珍藏。'] },
      { id: 'veteran', name: '老兵杰克', type: 'mentor', description: '历经百战的老兵', avatar: '👤', introEvent: '老兵杰克递给你一把生锈的刀："想活命，先学会这个。"', maxRelationshipEvents: ['杰克将珍藏的战前军牌挂在你胸前，认你为他唯一的传人。'] },
      { id: 'warlord', name: '军阀铁爪', type: 'rival', description: '统治一方的暴君', avatar: '⚔', introEvent: '军阀铁爪的铁爪捏碎了酒杯，冷冷地盯着你。', maxRelationshipEvents: ['铁爪破天荒地大笑，将一半领地割让给你，称你为兄弟。'] },
      { id: 'scavenger', name: '拾荒者小艾', type: 'romance', description: '活泼的废土拾荒者', avatar: '💕', introEvent: '小艾从垃圾堆里探出头，兴奋地举着一块发光的零件："快看这个！"', maxRelationshipEvents: ['小艾找到了传说中的绿洲地图，说要和你一起去找。'] },
      { id: 'prophet', name: '先知', type: 'mentor', description: '预见过未来的神秘人', avatar: '👤', introEvent: '先知睁开浑浊的双眼，低声说："你终于来了，改变命运的人。"', maxRelationshipEvents: ['先知将预言水晶交付于你，说未来就交给你书写了。'] },
      { id: 'cult_leader', name: '教派领袖', type: 'rival', description: '末日邪教的教主', avatar: '⚔', introEvent: '教派领袖张开双臂，狂热地宣布你是神谕中的使者。', maxRelationshipEvents: ['教派领袖最终臣服于你，将整个教派的信徒交付于你指挥。'] },
    ],
  },
  {
    id: 'wuxia',
    name: '古代武侠',
    nameEn: 'Ancient Wuxia',
    description: '江湖浩渺，刀光剑影。正邪两道纷争不断，绝世武功藏于秘境，英雄豪杰各领风骚。在这风起云涌的江湖，你将书写自己的传奇。',
    themeColor: '#FF2D55',
    statNames: {
      strength: '内力',
      intelligence: '武学',
      charisma: '侠名',
      luck: '福缘',
      health: '气血',
      special: '门派',
    },
    identities: [
      {
        id: 'farmers_son',
        name: '农家少年',
        description: '普通的农家孩子，因机缘巧合踏入江湖。',
        baseStats: { strength: 15, intelligence: 10, charisma: 10, luck: 20, health: 65, special: 10 },
        exclusiveEvents: ['chance_encounter', 'hidden_master'],
        specialTrait: '赤子之心',
      },
      {
        id: 'aristocrat',
        name: '世家子弟',
        description: '武林世家的传人，家学渊源，根基深厚。',
        baseStats: { strength: 25, intelligence: 25, charisma: 20, luck: 10, health: 75, special: 25 },
        exclusiveEvents: ['family_legacy', 'sect_competition'],
        specialTrait: '家学渊源',
      },
      {
        id: 'orphan',
        name: '孤儿',
        description: '无依无靠的孤儿，从小在江湖中摸爬滚打。',
        baseStats: { strength: 20, intelligence: 15, charisma: 10, luck: 15, health: 55, special: 15 },
        exclusiveEvents: ['street_survival', 'unexpected_master'],
        specialTrait: '顽强意志',
      },
      {
        id: 'demon_disciple',
        name: '魔教后人',
        description: '魔教覆灭后的遗孤，身怀魔教不传之秘。',
        baseStats: { strength: 30, intelligence: 20, charisma: 10, luck: 10, health: 70, special: 30 },
        exclusiveEvents: ['demon_art', 'righteous_pursuit'],
        specialTrait: '亦正亦邪',
      },
      {
        id: 'spy',
        name: '朝廷密探',
        description: '隐藏在江湖中的朝廷密探，身负秘密使命。',
        baseStats: { strength: 15, intelligence: 30, charisma: 20, luck: 15, health: 60, special: 20 },
        exclusiveEvents: ['imperial_mission', 'identity_crisis'],
        specialTrait: '深藏不露',
      },
      {
        id: 'foreigner',
        name: '异域来客',
        description: '来自西域的神秘来客，身怀异域武功。',
        baseStats: { strength: 20, intelligence: 20, charisma: 15, luck: 25, health: 70, special: 20 },
        exclusiveEvents: ['foreign_martial_art', 'cultural_clash'],
        specialTrait: '异域奇功',
      },
      {
        id: 'medic',
        name: '医仙传人',
        description: '医仙谷的传人，精通医术与毒术，能救人性命也能杀人于无形。',
        baseStats: { strength: 10, intelligence: 30, charisma: 25, luck: 15, health: 80, special: 25 },
        exclusiveEvents: ['medical_mission', 'poison_mastery'],
        specialTrait: '医毒双绝',
      },
      {
        id: 'poisoner',
        name: '毒师弟子',
        description: '毒龙沼泽的传人，以毒入武，一身是毒。',
        baseStats: { strength: 15, intelligence: 35, charisma: 5, luck: 20, health: 55, special: 40 },
        exclusiveEvents: ['poison_dragon_swamp', 'venom_immunity'],
        specialTrait: '万毒不侵',
      },
      {
        id: 'swordsman',
        name: '剑客',
        description: '自幼习剑的剑痴，一心追求剑道极致。',
        baseStats: { strength: 30, intelligence: 15, charisma: 15, luck: 15, health: 70, special: 30 },
        exclusiveEvents: ['sword_tomb_inheritance', 'sword_heart_illumination'],
        specialTrait: '剑心通明',
      },
      {
        id: 'assassin_wuxia',
        name: '暗器师',
        description: '暗器阁的传人，一手暗器出神入化，杀人于百步之外。',
        baseStats: { strength: 20, intelligence: 25, charisma: 10, luck: 25, health: 60, special: 35 },
        exclusiveEvents: ['hidden_weapon_mastery', 'assassination_art'],
        specialTrait: '百步穿杨',
      },
    ],
    npcs: [
      { id: 'sword_fairy', name: '剑仙南宫婉', type: 'romance', description: '天下第一的绝世剑仙', avatar: '💕', introEvent: '南宫婉的剑尖停在你咽喉前三寸，美眸中闪过一丝讶异。', maxRelationshipEvents: ['南宫婉放下长剑，与你隐居桃花源，再也不问江湖事。'] },
      { id: 'drunken_master', name: '醉道人', type: 'mentor', description: '游戏人间的绝世高手', avatar: '👤', introEvent: '醉道人将酒葫芦递给你，打了个酒嗝："小子，陪我喝一口？"', maxRelationshipEvents: ['醉道人将毕生绝学「醉仙剑诀」传授于你，飘然远去。'] },
      { id: 'demon_sect_master', name: '魔教教主', type: 'rival', description: '野心勃勃的魔教首领', avatar: '⚔', introEvent: '魔教教主狂笑着拍碎了桌子："正道？不过是一群伪君子！"', maxRelationshipEvents: ['魔教教主将魔教至宝交付于你，独自去挑战武林盟主。'] },
      { id: 'twin_swords', name: '双剑侠侣', type: 'mentor', description: '恩爱的一对江湖侠侣', avatar: '👤', introEvent: '双剑侠侣同时出剑，剑气交织成一幅鸳鸯图案，让你叹为观止。', maxRelationshipEvents: ['双剑侠侣将合璧剑谱传授于你，嘱咐你找到值得托付的人。'] },
      { id: 'poison_girl', name: '毒仙儿', type: 'romance', description: '亦正亦邪的用毒高手', avatar: '💕', introEvent: '毒仙儿将一枚毒丸塞进你嘴里，笑道："放心，不是毒药。"', maxRelationshipEvents: ['毒仙儿为你解了天下无解的奇毒，说你的命只能是她的。'] },
      { id: 'prince', name: '小王爷', type: 'rival', description: '权势滔天的皇族', avatar: '⚔', introEvent: '小王爷摇着折扇，似笑非笑地看着你："有点意思。"', maxRelationshipEvents: ['小王爷在朝堂上力保你无罪，私下说他是为了你赌上了全部。'] },
    ],
  },
  {
    id: 'floating_citadel',
    name: '浮空要塞',
    nameEn: 'The Floating Citadel',
    description: '一座悬浮在虚空中的千层巨塔，每一层都是一片独立的大陆。传闻到达最顶层的人，将获得真正的自由...',
    themeColor: '#2ECC71',
    statNames: {
      strength: '力量',
      intelligence: '技巧',
      charisma: '人缘',
      luck: '幸运',
      health: '生命值',
      special: '剑技',
    },
    identities: [
      {
        id: 'lone_wolf',
        name: '独行者',
        description: '独自在塔中生存的玩家，不依赖任何人。高技巧高剑技。',
        baseStats: { strength: 20, intelligence: 35, charisma: 10, luck: 15, health: 55, special: 40 },
        exclusiveEvents: ['lone_wolf_awakening', 'lone_wolf_peak'],
        specialTrait: '独行剑心',
        spawnWeight: 15,
      },
      {
        id: 'guild_master',
        name: '公会领袖',
        description: '创建或领导大型公会，统筹攻略。高力量高魅力。',
        baseStats: { strength: 35, intelligence: 20, charisma: 35, luck: 10, health: 70, special: 20 },
        exclusiveEvents: ['guild_founding', 'guild_unity'],
        specialTrait: '统御之力',
        spawnWeight: 10,
      },
      {
        id: 'blacksmith',
        name: '锻造师',
        description: '专注于武器锻造与强化。高技巧。',
        baseStats: { strength: 25, intelligence: 40, charisma: 15, luck: 10, health: 65, special: 25 },
        exclusiveEvents: ['master_forge', 'legendary_weapon'],
        specialTrait: '锻魂之手',
        spawnWeight: 12,
      },
      {
        id: 'tamer',
        name: '驯兽师',
        description: '与塔中怪物建立羁绊。高魅力高幸运。',
        baseStats: { strength: 15, intelligence: 20, charisma: 35, luck: 35, health: 60, special: 20 },
        exclusiveEvents: ['beast_bond', 'monster_companion'],
        specialTrait: '兽语通心',
        spawnWeight: 10,
      },
      {
        id: 'info_broker',
        name: '情报商',
        description: '掌握塔中最全面的信息。高技巧高魅力。',
        baseStats: { strength: 10, intelligence: 40, charisma: 30, luck: 20, health: 50, special: 15 },
        exclusiveEvents: ['info_network', 'secret_knowledge'],
        specialTrait: '千里眼',
        spawnWeight: 10,
      },
      {
        id: 'chef',
        name: '料理人',
        description: '用美食恢复队友生命与士气。高魅力。',
        baseStats: { strength: 15, intelligence: 25, charisma: 40, luck: 15, health: 70, special: 10 },
        exclusiveEvents: ['culinary_healing', 'feast_of_courage'],
        specialTrait: '料理之心',
        spawnWeight: 12,
      },
      {
        id: 'frontliner',
        name: '前线攻略者',
        description: '永远冲在最前线。高力量高生命值。',
        baseStats: { strength: 40, intelligence: 15, charisma: 15, luck: 10, health: 110, special: 25 },
        exclusiveEvents: ['first_blood', 'shield_wall'],
        specialTrait: '不屈意志',
        spawnWeight: 8,
      },
      {
        id: 'healer',
        name: '治疗者',
        description: '辅助与治疗。高技巧高魅力。',
        baseStats: { strength: 10, intelligence: 35, charisma: 35, luck: 15, health: 65, special: 25 },
        exclusiveEvents: ['healing_touch', 'resurrection_art'],
        specialTrait: '回春之手',
        spawnWeight: 10,
      },
      {
        id: 'merchant',
        name: '商人',
        description: '在各层间倒卖道具。高魅力高幸运。',
        baseStats: { strength: 10, intelligence: 25, charisma: 35, luck: 35, health: 55, special: 10 },
        exclusiveEvents: ['trade_route', 'golden_opportunity'],
        specialTrait: '商机洞察',
        spawnWeight: 15,
      },
      {
        id: 'roleplayer',
        name: '角色扮演者',
        description: '沉浸在自己的角色中。高幸运。',
        baseStats: { strength: 15, intelligence: 20, charisma: 25, luck: 40, health: 50, special: 15 },
        exclusiveEvents: ['role_immersion', 'lucky_star'],
        specialTrait: '命运宠儿',
        spawnWeight: 8,
      },
    ],
    npcs: [
      { id: 'shadow', name: '暗影', type: 'mentor', description: '居住在第22层湖畔小屋的神秘黑衣剑士，传授独门剑技', avatar: '🗡️', introEvent: '你在第22层的湖畔小屋遇到了一位身穿黑衣的神秘剑士。他背对着你，淡淡地说："想学剑？先学会不怕死。"', maxRelationshipEvents: ['暗影将毕生领悟的「星爆剑技」传授于你，随后化作光点消散在虚空中。'] },
      { id: 'dawn', name: '晨曦', type: 'mentor', description: '使用细剑的公会干部，擅长团队指挥与战术规划', avatar: '⚔️', introEvent: '晨曦站在公会大厅的台阶上，细剑斜指地面。她打量着你，露出赞许的微笑："你很有潜力，要不要加入攻略组？"', maxRelationshipEvents: ['晨曦将公会会长的位置传给了你，自己退居幕后继续培养新人。'] },
      { id: 'blood_blade', name: '血刃', type: 'rival', description: '以猎杀其他冒险者为乐的PK者，神出鬼没', avatar: '🔴', introEvent: '血刃从阴影中现身，红色的斗篷在风中猎猎作响。他舔了舔嘴唇："又一个猎物送上门来了。"', maxRelationshipEvents: ['血刃在被你击败后，将一把染血的短剑扔给你："下次，我会变得更强。"'] },
      { id: 'colossus', name: '巨像', type: 'rival', description: '每25层出现的特殊楼层守护者，实力恐怖', avatar: '🏰', introEvent: '大地震动，一个高达十米的石制巨人从地面升起。巨像的眼中燃烧着蓝色的火焰："凡人，止步于此。"', maxRelationshipEvents: ['巨像在被你击败后，胸口的宝石碎裂，露出了一颗跳动的心脏："原来...这就是败北的感觉。"'] },
      { id: 'feather', name: '羽衣', type: 'romance', description: '在迷宫深处迷路的失忆少女，似乎隐藏着某种秘密', avatar: '🪶', introEvent: '你在迷宫深处发现了一个蜷缩在角落的少女。她抬起头，眼神迷茫："我...我是谁？这里...是哪里？"', maxRelationshipEvents: ['羽衣恢复了记忆，原来她是这座塔的创造者留下的"引导程序"。她选择留在你身边，陪你一起走向顶层。'] },
      { id: 'hammer', name: '铁锤', type: 'romance', description: '热情开朗的锻造师，独自经营着一家小店', avatar: '🔨', introEvent: '铁锤的锻造店里传来叮叮当当的敲击声。她擦了擦额头的汗，冲你露出灿烂的笑容："欢迎光临！要打造什么武器？"', maxRelationshipEvents: ['铁锤为你打造了一对婚戒，材质是她在塔的最深处找到的稀有金属。她说："这对戒指，就算塔倒塌了也不会损坏。"'] },
    ],
  },
  // ============================================================
  // 斗破苍穹
  // ============================================================
  {
    id: 'doupo',
    name: '斗破苍穹',
    nameEn: 'Battle Through the Heavens',
    description: '斗气大陆，强者云集。在这里，斗气决定一切，异火焚天，强者可踏碎虚空。',
    themeColor: '#FF6B35',
    statNames: {
      strength: '力量',
      intelligence: '灵魂力',
      charisma: '声望',
      luck: '机缘',
      health: '生命力',
      special: '异火',
    },
    identities: [
      {
        id: 'xiao_clan',
        name: '萧家子弟',
        description: '落魄家族的后裔，肩负着复兴家族的使命。',
        baseStats: { strength: 15, intelligence: 15, charisma: 10, luck: 20, health: 60, special: 15 },
        exclusiveEvents: ["xiao_clan_legacy", "fallen_genius"],
        specialTrait: '陨落天才',
        spawnWeight: 20,
      },
      {
        id: 'alchemist',
        name: '炼药师',
        description: '以炼药为生的修行者，丹药可生死人肉白骨。',
        baseStats: { strength: 10, intelligence: 30, charisma: 15, luck: 10, health: 55, special: 25 },
        exclusiveEvents: ["alchemy_awakening", "pill_formation"],
        specialTrait: '丹心',
        spawnWeight: 12,
      },
      {
        id: 'beast_clan',
        name: '魔兽家族',
        description: '体内流淌着上古魔兽的血脉，肉身强横无比。',
        baseStats: { strength: 30, intelligence: 10, charisma: 10, luck: 15, health: 90, special: 20 },
        exclusiveEvents: ["bloodline_awakening", "beast_transformation"],
        specialTrait: '兽血沸腾',
        spawnWeight: 10,
      },
      {
        id: 'yunlan',
        name: '云岚宗弟子',
        description: '云岚宗的内门弟子，修炼风属性斗气，身法飘逸。',
        baseStats: { strength: 20, intelligence: 20, charisma: 15, luck: 15, health: 65, special: 20 },
        exclusiveEvents: ["yunlan_sword", "cloud_dance"],
        specialTrait: '云岚剑意',
        spawnWeight: 12,
      },
      {
        id: 'soul_hall',
        name: '魂殿使者',
        description: '魂殿的使者，行踪诡秘，擅长灵魂攻击。',
        baseStats: { strength: 15, intelligence: 25, charisma: 5, luck: 10, health: 50, special: 30 },
        exclusiveEvents: ["soul_capture", "dark_pact"],
        specialTrait: '噬魂',
        spawnWeight: 8,
      },
      {
        id: 'jia_nan',
        name: '迦南学院学生',
        description: '迦南学院的天之骄子，拥有最优质的修炼资源。',
        baseStats: { strength: 20, intelligence: 20, charisma: 20, luck: 15, health: 70, special: 20 },
        exclusiveEvents: ["academy_trial", "inner_court"],
        specialTrait: '学院精英',
        spawnWeight: 10,
      },
      {
        id: 'mercenary',
        name: '佣兵',
        description: '刀口舔血的佣兵，在生死之间磨练斗技。',
        baseStats: { strength: 25, intelligence: 10, charisma: 10, luck: 20, health: 75, special: 15 },
        exclusiveEvents: ["mercenary_life", "bounty_hunt"],
        specialTrait: '嗜战',
        spawnWeight: 15,
      },
      {
        id: 'royal',
        name: '皇室成员',
        description: '帝国皇室的后裔，拥有最高的权势与资源。',
        baseStats: { strength: 20, intelligence: 20, charisma: 25, luck: 15, health: 70, special: 20 },
        exclusiveEvents: ["royal_decree", "imperial_power"],
        specialTrait: '龙气',
        spawnWeight: 8,
      },
      {
        id: 'snake',
        name: '蛇人族',
        description: '沙漠蛇人族的后裔，拥有毒属性斗气和强大的肉身。',
        baseStats: { strength: 25, intelligence: 15, charisma: 10, luck: 15, health: 80, special: 25 },
        exclusiveEvents: ["snake_blood", "desert_king"],
        specialTrait: '蛇毒',
        spawnWeight: 8,
      },
      {
        id: 'ancient',
        name: '古族后裔',
        description: '远古八族的后裔，血脉中蕴含着远古的力量。',
        baseStats: { strength: 20, intelligence: 25, charisma: 20, luck: 20, health: 70, special: 30 },
        exclusiveEvents: ["ancient_blood", "tribal_legacy"],
        specialTrait: '古血',
        spawnWeight: 7,
      },
    ],
    npcs: [
      {
        id: 'yao_lao',
        name: '药老',
        type: 'mentor',
        description: '曾经的药尊者，灵魂体状态寄居于戒指之中',
        avatar: '💍',
        introEvent: '你手中的戒指微微发热，一个苍老的声音在脑海中响起。',
        maxRelationshipEvents: ["药老将毕生炼药术传授于你，含笑消散于天地之间。"],
      },
      {
        id: 'yun_yun',
        name: '云韵',
        type: 'romance',
        description: '云岚宗宗主，气质出尘，心思细腻',
        avatar: '💕',
        introEvent: '云巅之上，一位白衣女子御剑而来，目光中带着几分审视。',
        maxRelationshipEvents: ["云韵放弃宗主之位，与你携手隐居山林。"],
      },
      {
        id: 'medusa',
        name: '美杜莎',
        type: 'romance',
        description: '蛇人族女王，冷艳而危险',
        avatar: '🐍',
        introEvent: '沙漠深处，一双金色的蛇瞳锁定了你，危险而迷人。',
        maxRelationshipEvents: ["美杜莎第一次露出温柔的笑容，愿为你放弃王位。"],
      },
      {
        id: 'hun_tiandi',
        name: '魂天帝',
        type: 'rival',
        description: '魂殿之主，野心勃勃，欲吞噬天下灵魂',
        avatar: '⚔️',
        introEvent: '魂天帝的威压笼罩全场，他冷冷一笑：\'有趣的蝼蚁。\'',
        maxRelationshipEvents: ["魂天帝最终认可了你的实力，承认你是唯一值得尊敬的对手。"],
      },
      {
        id: 'yun_shan',
        name: '云山',
        type: 'rival',
        description: '云岚宗前任宗主，为求突破不择手段',
        avatar: '⚔️',
        introEvent: '云山踏空而来，目光如剑，直刺你的灵魂。',
        maxRelationshipEvents: ["云山在临终前终于醒悟，将云岚宗的未来托付于你。"],
      },
      {
        id: 'gu_xun_er',
        name: '薰儿',
        type: 'romance',
        description: '古族千金，温柔而坚定，始终守护着你',
        avatar: '💕',
        introEvent: '薰儿在月光下静静地看着你，目光中满是温柔与期待。',
        maxRelationshipEvents: ["薰儿牵起你的手，轻声说：无论你去哪里，我都会跟着。"],
      },
    ],
  },
  // ============================================================
  // 龙族
  // ============================================================
  {
    id: 'dragon_raja',
    name: '龙族',
    nameEn: 'Dragon Raja',
    description: '龙血流淌的世界，混血种与龙类的战争从未停止。言灵觉醒之时，便是命运齿轮转动之际。',
    themeColor: '#1E3A8A',
    statNames: {
      strength: '龙血',
      intelligence: '言灵',
      charisma: '血统',
      luck: '命运',
      health: '生命',
      special: '龙化',
    },
    identities: [
      {
        id: 'cassell_student',
        name: '卡塞尔学生',
        description: '卡塞尔学院的学生，正在接受屠龙训练。',
        baseStats: { strength: 15, intelligence: 20, charisma: 15, luck: 15, health: 60, special: 20 },
        exclusiveEvents: ["cassell_entrance", "dragon_course"],
        specialTrait: '屠龙者',
        spawnWeight: 20,
      },
      {
        id: 'executioner',
        name: '执行部专员',
        description: '执行部的精英，专门处理与龙类相关的事件。',
        baseStats: { strength: 25, intelligence: 15, charisma: 10, luck: 15, health: 75, special: 25 },
        exclusiveEvents: ["field_mission", "dragon_hunt"],
        specialTrait: '杀胚',
        spawnWeight: 10,
      },
      {
        id: 'alchemist_dr',
        name: '炼金术师',
        description: '精通炼金术，能够制造强大的炼金武器。',
        baseStats: { strength: 10, intelligence: 30, charisma: 10, luck: 15, health: 55, special: 25 },
        exclusiveEvents: ["alchemy_research", "dragon_blood_experiment"],
        specialTrait: '炼金狂',
        spawnWeight: 10,
      },
      {
        id: 'dragon_blood',
        name: '龙类混血',
        description: '体内龙血浓度极高，随时可能堕化为死侍。',
        baseStats: { strength: 30, intelligence: 10, charisma: 5, luck: 10, health: 85, special: 35 },
        exclusiveEvents: ["blood_awakening", "dragon_eyes"],
        specialTrait: '龙血沸腾',
        spawnWeight: 8,
      },
      {
        id: 'ordinary',
        name: '普通人',
        description: '没有龙血的普通人，却意外卷入了混血种的世界。',
        baseStats: { strength: 10, intelligence: 15, charisma: 15, luck: 20, health: 50, special: 10 },
        exclusiveEvents: ["accidental_involvement", "ordinary_hero"],
        specialTrait: '平凡',
        spawnWeight: 15,
      },
      {
        id: 'secret_party',
        name: '密党成员',
        description: '秘党的高层，掌握着混血种世界的秘密。',
        baseStats: { strength: 20, intelligence: 25, charisma: 20, luck: 10, health: 65, special: 25 },
        exclusiveEvents: ["secret_meeting", "party_intrigue"],
        specialTrait: '深谋',
        spawnWeight: 8,
      },
      {
        id: 'watcher',
        name: '守望者',
        description: '独自守望龙族遗迹的孤独者，知晓许多被遗忘的历史。',
        baseStats: { strength: 15, intelligence: 25, charisma: 10, luck: 20, health: 60, special: 20 },
        exclusiveEvents: ["ruin_discovery", "ancient_secret"],
        specialTrait: '守望',
        spawnWeight: 10,
      },
      {
        id: 'dragon_slayer',
        name: '屠龙者',
        description: '以屠龙为生的战士，身上布满了与龙类战斗的伤痕。',
        baseStats: { strength: 30, intelligence: 10, charisma: 10, luck: 15, health: 80, special: 30 },
        exclusiveEvents: ["dragon_slay", "legendary_hunt"],
        specialTrait: '屠龙',
        spawnWeight: 8,
      },
      {
        id: 'merchant_dr',
        name: '商人',
        description: '在混血种与普通人之间倒卖情报与物资的商人。',
        baseStats: { strength: 10, intelligence: 20, charisma: 25, luck: 20, health: 55, special: 15 },
        exclusiveEvents: ["black_market", "information_trade"],
        specialTrait: '精明',
        spawnWeight: 12,
      },
      {
        id: 'archaeologist',
        name: '考古学家',
        description: '专门研究龙族遗迹与历史的学者。',
        baseStats: { strength: 10, intelligence: 30, charisma: 15, luck: 15, health: 50, special: 20 },
        exclusiveEvents: ["ruin_excavation", "dragon_text_decipher"],
        specialTrait: '博学',
        spawnWeight: 9,
      },
    ],
    npcs: [
      {
        id: 'anger',
        name: '昂热',
        type: 'mentor',
        description: '卡塞尔学院的校长，活了百余年的S级混血种',
        avatar: '👤',
        introEvent: '昂热点燃雪茄，锐利的目光穿透了你的心防。',
        maxRelationshipEvents: ["昂热将学院的未来托付于你，独自走向最后的战场。"],
      },
      {
        id: 'lu_mingfei',
        name: '路明非',
        type: 'mentor',
        description: '看似废柴的S级学生，体内沉睡着未知的力量',
        avatar: '👤',
        introEvent: '路明非挠挠头，露出一个尴尬却真诚的微笑。',
        maxRelationshipEvents: ["路明非用四分之一的生命为你打开了通往未来的门。"],
      },
      {
        id: 'nuonuo',
        name: '诺诺',
        type: 'romance',
        description: '红发女巫，性格张扬热烈',
        avatar: '💕',
        introEvent: '诺诺骑着机车停在你面前，红发在风中飞扬。',
        maxRelationshipEvents: ["诺诺第一次卸下了所有的伪装，在你面前露出了脆弱的一面。"],
      },
      {
        id: 'hualilizi',
        name: '绘梨衣',
        type: 'romance',
        description: '蛇岐八家的上杉家主，单纯如白纸',
        avatar: '💕',
        introEvent: '绘梨衣歪着头看着你，在本子上写下：\'你看起来很有趣。\'',
        maxRelationshipEvents: ["绘梨衣用尽最后的力气，为你写下了世界上最温柔的告白。"],
      },
      {
        id: 'caesar',
        name: '凯撒',
        type: 'rival',
        description: '加图索家的继承人，骄傲如狮',
        avatar: '⚔️',
        introEvent: '凯撒整理着袖口，目光中带着天生的傲慢。',
        maxRelationshipEvents: ["凯撒举起酒杯，第一次真诚地称你为朋友。"],
      },
      {
        id: 'chu_zihang',
        name: '楚子航',
        type: 'rival',
        description: '永远的杀胚师兄，面瘫却可靠',
        avatar: '⚔️',
        introEvent: '楚子航默默地站在雨中，村雨上的水珠折射出冷冽的光。',
        maxRelationshipEvents: ["楚子航第一次露出笑容，说：谢谢你，让我想起了阳光。"],
      },
    ],
  },
  // ============================================================
  // 三体
  // ============================================================
  {
    id: 'three_body',
    name: '三体',
    nameEn: 'The Three-Body Problem',
    description: '宇宙就是一座黑暗森林，每个文明都是带枪的猎人。在这冰冷的宇宙中，生存是第一需要。',
    themeColor: '#0F172A',
    statNames: {
      strength: '意志',
      intelligence: '理性',
      charisma: '影响力',
      luck: '机遇',
      health: '生存',
      special: '科技',
    },
    identities: [
      {
        id: 'physicist',
        name: '物理学家',
        description: '研究基础物理的科学家，试图解开宇宙的终极奥秘。',
        baseStats: { strength: 10, intelligence: 35, charisma: 10, luck: 15, health: 50, special: 30 },
        exclusiveEvents: ["physics_breakthrough", "cosmic_signal"],
        specialTrait: '求真',
        spawnWeight: 15,
      },
      {
        id: 'sociologist',
        name: '社会学家',
        description: '研究宇宙社会学的学者，深谙黑暗森林法则。',
        baseStats: { strength: 15, intelligence: 25, charisma: 20, luck: 15, health: 55, special: 20 },
        exclusiveEvents: ["dark_forest_theory", "civilization_study"],
        specialTrait: '洞察',
        spawnWeight: 10,
      },
      {
        id: 'engineer_3b',
        name: '工程师',
        description: '建造恒星飞船与太空城市的工程师。',
        baseStats: { strength: 20, intelligence: 25, charisma: 10, luck: 15, health: 65, special: 25 },
        exclusiveEvents: ["ship_design", "space_station"],
        specialTrait: '建造',
        spawnWeight: 12,
      },
      {
        id: 'soldier_3b',
        name: '军人',
        description: '守护人类文明的太空军人。',
        baseStats: { strength: 25, intelligence: 15, charisma: 15, luck: 15, health: 80, special: 20 },
        exclusiveEvents: ["military_training", "space_battle"],
        specialTrait: '铁血',
        spawnWeight: 12,
      },
      {
        id: 'wallfacer',
        name: '面壁者',
        description: '被赋予无限权力的面壁者，独自对抗三体文明。',
        baseStats: { strength: 20, intelligence: 30, charisma: 20, luck: 10, health: 60, special: 30 },
        exclusiveEvents: ["wallfacer_plan", "solitary_strategy"],
        specialTrait: '面壁',
        spawnWeight: 5,
      },
      {
        id: 'wallbreaker',
        name: '破壁人',
        description: '识破面壁者计划的破壁人，代表三体文明的智慧。',
        baseStats: { strength: 15, intelligence: 35, charisma: 10, luck: 15, health: 55, special: 30 },
        exclusiveEvents: ["breaking_wall", "truth_reveal"],
        specialTrait: '破壁',
        spawnWeight: 5,
      },
      {
        id: 'observer',
        name: '观察员',
        description: '观察宇宙文明的神秘存在。',
        baseStats: { strength: 10, intelligence: 30, charisma: 15, luck: 20, health: 50, special: 35 },
        exclusiveEvents: ["cosmic_observation", "civilization_contact"],
        specialTrait: '观察',
        spawnWeight: 8,
      },
      {
        id: 'fugitive',
        name: '逃亡者',
        description: '选择逃离太阳系的人类，在宇宙中流浪。',
        baseStats: { strength: 15, intelligence: 20, charisma: 10, luck: 25, health: 60, special: 20 },
        exclusiveEvents: ["escape_earth", "interstellar_wander"],
        specialTrait: '逃亡',
        spawnWeight: 10,
      },
      {
        id: 'guardian',
        name: '文明守护者',
        description: '决心守护地球文明到底的战士。',
        baseStats: { strength: 25, intelligence: 20, charisma: 20, luck: 10, health: 75, special: 25 },
        exclusiveEvents: ["last_stand", "civilization_defense"],
        specialTrait: '守护',
        spawnWeight: 8,
      },
      {
        id: 'civilian_3b',
        name: '普通民众',
        description: '危机纪元中的普通人，在大时代中努力生存。',
        baseStats: { strength: 10, intelligence: 15, charisma: 15, luck: 20, health: 55, special: 10 },
        exclusiveEvents: ["crisis_era", "ordinary_survival"],
        specialTrait: '坚韧',
        spawnWeight: 15,
      },
    ],
    npcs: [
      {
        id: 'luo_ji',
        name: '罗辑',
        type: 'mentor',
        description: '第四位面壁者，悟出黑暗森林法则的执剑人',
        avatar: '👤',
        introEvent: '罗辑坐在雪地中，目光深邃如星空。',
        maxRelationshipEvents: ["罗辑将黑暗森林的真谛传授于你，独自面对宇宙的终结。"],
      },
      {
        id: 'zhang_beihai',
        name: '章北海',
        type: 'mentor',
        description: '太空军政委，坚定的逃亡主义者',
        avatar: '👤',
        introEvent: '章北海的目光平静而坚定，仿佛早已看透了一切。',
        maxRelationshipEvents: ["章北海在最后的时刻，为你指明了人类唯一的生路。"],
      },
      {
        id: 'cheng_xin',
        name: '程心',
        type: 'romance',
        description: '第二代执剑人，善良却优柔寡断',
        avatar: '💕',
        introEvent: '程心看着你，眼中满是对未来的迷茫与希望。',
        maxRelationshipEvents: ["程心第一次做出果断的决定，是为了守护你。"],
      },
      {
        id: 'sophon',
        name: '智子',
        type: 'romance',
        description: '三体文明制造的微观粒子智能体',
        avatar: '💕',
        introEvent: '一个和服少女凭空出现，她的微笑让人不寒而栗。',
        maxRelationshipEvents: ["智子第一次流露出真实的情感，说：你是我唯一无法理解的人类。"],
      },
      {
        id: 'wade',
        name: '韦德',
        type: 'rival',
        description: '极端理性的PIA局长，为达目的不择手段',
        avatar: '⚔️',
        introEvent: '韦德冷冷地看着你：\'失去人性，失去很多；失去兽性，失去一切。\'',
        maxRelationshipEvents: ["韦德在最后的时刻，露出了罕见的赞许目光。"],
      },
      {
        id: 'listener',
        name: '监听员',
        type: 'rival',
        description: '三体世界的监听员，第一个收到地球信号的存在',
        avatar: '⚔️',
        introEvent: '监听员的声音从虚空中传来：\'不要回答！不要回答！不要回答！\'',
        maxRelationshipEvents: ["监听员最终选择了背叛三体世界，只为保护人类文明。"],
      },
    ],
  },
  // ============================================================
  // 葬送的芙莉莲
  // ============================================================
  {
    id: 'frieren',
    name: '葬送的芙莉莲',
    nameEn: 'Frieren: Beyond Journey\'s End',
    description: '千年之后的魔法世界，精灵的寿命漫长而人类的生命短暂。真正的魔法，是理解人心的过程。',
    themeColor: '#C084FC',
    statNames: {
      strength: '魔力',
      intelligence: '精神',
      charisma: '羁绊',
      luck: '命运',
      health: '寿命',
      special: '魔法理解',
    },
    identities: [
      {
        id: 'elf',
        name: '精灵族',
        description: '寿命近千年的精灵族，拥有强大的魔力但情感淡薄。',
        baseStats: { strength: 25, intelligence: 20, charisma: 10, luck: 15, health: 80, special: 35 },
        exclusiveEvents: ["elf_longevity", "magic_mastery"],
        specialTrait: '长生',
        spawnWeight: 8,
      },
      {
        id: 'human_mage',
        name: '人类魔法使',
        description: '人类中的魔法天才，用短暂的生命追求魔法的极致。',
        baseStats: { strength: 20, intelligence: 25, charisma: 15, luck: 15, health: 55, special: 25 },
        exclusiveEvents: ["human_potential", "short_life_shine"],
        specialTrait: '短命天才',
        spawnWeight: 20,
      },
      {
        id: 'hero_descendant',
        name: '勇者后裔',
        description: '传说中的勇者的后代，继承了守护世界的使命。',
        baseStats: { strength: 20, intelligence: 15, charisma: 20, luck: 20, health: 65, special: 20 },
        exclusiveEvents: ["hero_legacy", "sword_inheritance"],
        specialTrait: '勇者血脉',
        spawnWeight: 10,
      },
      {
        id: 'monk',
        name: '僧侣',
        description: '信仰神明的僧侣，用神圣魔法治愈与守护。',
        baseStats: { strength: 15, intelligence: 20, charisma: 20, luck: 15, health: 70, special: 20 },
        exclusiveEvents: ["holy_magic", "divine_blessing"],
        specialTrait: '圣光',
        spawnWeight: 12,
      },
      {
        id: 'warrior',
        name: '战士',
        description: '以肉身与武器战斗的战士，简单而可靠。',
        baseStats: { strength: 25, intelligence: 10, charisma: 15, luck: 15, health: 85, special: 15 },
        exclusiveEvents: ["sword_training", "battle_instinct"],
        specialTrait: '蛮力',
        spawnWeight: 15,
      },
      {
        id: 'thief',
        name: '盗贼',
        description: '擅长开锁与陷阱解除的盗贼，在遗迹探险中不可或缺。',
        baseStats: { strength: 15, intelligence: 20, charisma: 10, luck: 25, health: 55, special: 15 },
        exclusiveEvents: ["lock_picking", "trap_master"],
        specialTrait: '灵巧',
        spawnWeight: 10,
      },
      {
        id: 'court_mage',
        name: '宫廷法师',
        description: '服务于王室的宫廷法师，精通礼仪与政治魔法。',
        baseStats: { strength: 20, intelligence: 25, charisma: 20, luck: 10, health: 60, special: 25 },
        exclusiveEvents: ["court_intrigue", "royal_magic"],
        specialTrait: '权谋',
        spawnWeight: 8,
      },
      {
        id: 'demon',
        name: '魔族',
        description: '与人类对立的魔族，拥有强大的魔力与长久的寿命。',
        baseStats: { strength: 25, intelligence: 20, charisma: 5, luck: 15, health: 80, special: 30 },
        exclusiveEvents: ["demon_magic", "human_demon_war"],
        specialTrait: '魔性',
        spawnWeight: 8,
      },
      {
        id: 'adventurer',
        name: '冒险者',
        description: '在世界各地流浪的冒险者，为了财富与名声而旅行。',
        baseStats: { strength: 20, intelligence: 15, charisma: 15, luck: 20, health: 65, special: 15 },
        exclusiveEvents: ["adventure_begin", "treasure_hunt"],
        specialTrait: '冒险',
        spawnWeight: 15,
      },
      {
        id: 'librarian',
        name: '图书管理员',
        description: '管理古老魔法典籍的管理员，知晓许多被遗忘的知识。',
        baseStats: { strength: 10, intelligence: 30, charisma: 10, luck: 20, health: 50, special: 25 },
        exclusiveEvents: ["ancient_text", "forgotten_magic"],
        specialTrait: '博学',
        spawnWeight: 14,
      },
    ],
    npcs: [
      {
        id: 'frieren_npc',
        name: '芙莉莲',
        type: 'mentor',
        description: '活了千年的精灵魔法使，正在寻找理解人类情感的方法',
        avatar: '👤',
        introEvent: '芙莉莲从魔法书中抬起头，目光中带着千年的淡漠与一丝好奇。',
        maxRelationshipEvents: ["芙莉莲第一次流下眼泪，说：原来这就是悲伤。"],
      },
      {
        id: 'himmei',
        name: '辛美尔',
        type: 'mentor',
        description: '已故的勇者，只留下雕像与传说',
        avatar: '👤',
        introEvent: '辛美尔的雕像在阳光下闪耀，仿佛他从未离开。',
        maxRelationshipEvents: ["辛美尔的灵魂微笑着说：你终于理解了勇者的意义。"],
      },
      {
        id: 'fern',
        name: '菲伦',
        type: 'romance',
        description: '芙莉莲的弟子，认真而努力的少女魔法使',
        avatar: '💕',
        introEvent: '菲伦认真地练习着魔法，看到你的到来微微红了脸。',
        maxRelationshipEvents: ["菲伦终于坦率地说出了心意，那是她练习了无数次的告白。"],
      },
      {
        id: 'stark',
        name: '修塔尔克',
        type: 'rival',
        description: '战士村的少年，看似粗犷实则温柔',
        avatar: '⚔️',
        introEvent: '修塔尔克挥舞着巨大的斧头，露出一个笨拙的笑容。',
        maxRelationshipEvents: ["修塔尔克承认你是他唯一认可的对手与朋友。"],
      },
      {
        id: 'aura',
        name: '阿乌拉',
        type: 'rival',
        description: '活了五百年的魔族，自称为芙莉莲的宿敌',
        avatar: '⚔️',
        introEvent: '阿乌拉轻抚着琴弦，目光中满是对芙莉莲的执念。',
        maxRelationshipEvents: ["阿乌拉在最后的时刻，终于理解了人类的情感。"],
      },
      {
        id: 'serie',
        name: '赛丽艾',
        type: 'romance',
        description: '一级魔法使考试的考官，强大的大魔法使',
        avatar: '💕',
        introEvent: '赛丽艾审视着你，目光中带着对天才的期待。',
        maxRelationshipEvents: ["赛丽艾第一次露出了真正的笑容，承认你是她最出色的弟子。"],
      },
    ],
  },
  // ============================================================
  // 高达SEED
  // ============================================================
  {
    id: 'gundam_seed',
    name: '高达SEED',
    nameEn: 'Gundam SEED',
    description: '调整者与自然人之间的战争撕裂了世界。在宇宙的黑暗中，少年们驾驶着机动战士寻找和平的答案。',
    themeColor: '#00B894',
    statNames: {
      strength: '格斗',
      intelligence: '战术',
      charisma: '领导力',
      luck: '调整率',
      health: '装甲',
      special: 'SEED觉醒',
    },
    identities: [
      {
        id: 'coordinator',
        name: '调整者',
        description: '基因调整过的超人，拥有更强的身体素质与反应速度。',
        baseStats: { strength: 25, intelligence: 20, charisma: 15, luck: 20, health: 70, special: 25 },
        exclusiveEvents: ["coordinator_awakening", "superior_genes"],
        specialTrait: '调整',
        spawnWeight: 18,
      },
      {
        id: 'natural',
        name: '自然人',
        description: '未经基因调整的普通人，在调整者的压迫下挣扎求生。',
        baseStats: { strength: 15, intelligence: 15, charisma: 15, luck: 15, health: 60, special: 10 },
        exclusiveEvents: ["natural_pride", "ordinary_hero"],
        specialTrait: '自然',
        spawnWeight: 18,
      },
      {
        id: 'pilot',
        name: '机师',
        description: '驾驶机动战士的王牌机师，在战场上出生入死。',
        baseStats: { strength: 25, intelligence: 20, charisma: 15, luck: 15, health: 75, special: 30 },
        exclusiveEvents: ["mobile_suit_training", "ace_battle"],
        specialTrait: '王牌',
        spawnWeight: 12,
      },
      {
        id: 'captain',
        name: '舰长',
        description: '指挥战舰的舰长，肩负着船员的生命与使命。',
        baseStats: { strength: 20, intelligence: 25, charisma: 20, luck: 15, health: 70, special: 20 },
        exclusiveEvents: ["command_authority", "fleet_battle"],
        specialTrait: '统率',
        spawnWeight: 10,
      },
      {
        id: 'scientist_gs',
        name: '科学家',
        description: '开发机动战士与武器系统的科学家，掌握着改变战争的力量。',
        baseStats: { strength: 10, intelligence: 35, charisma: 10, luck: 15, health: 55, special: 25 },
        exclusiveEvents: ["mobile_suit_dev", "nuclear_engine"],
        specialTrait: '发明',
        spawnWeight: 8,
      },
      {
        id: 'politician',
        name: '政客',
        description: '在调整者与自然人之间周旋的政客，试图用外交结束战争。',
        baseStats: { strength: 10, intelligence: 25, charisma: 25, luck: 15, health: 55, special: 15 },
        exclusiveEvents: ["diplomacy", "peace_talks"],
        specialTrait: '外交',
        spawnWeight: 8,
      },
      {
        id: 'rebel',
        name: '反抗军',
        description: '反抗现有秩序的反抗军成员，为了自由而战。',
        baseStats: { strength: 20, intelligence: 15, charisma: 15, luck: 20, health: 70, special: 20 },
        exclusiveEvents: ["rebel_uprising", "freedom_fight"],
        specialTrait: '反抗',
        spawnWeight: 10,
      },
      {
        id: 'mercenary_gs',
        name: '佣兵',
        description: '在战争中谋生的佣兵，没有立场只有利益。',
        baseStats: { strength: 20, intelligence: 15, charisma: 10, luck: 20, health: 70, special: 20 },
        exclusiveEvents: ["mercenary_contract", "battlefield_survival"],
        specialTrait: '生存',
        spawnWeight: 10,
      },
      {
        id: 'doctor_gs',
        name: '医生',
        description: '在战地医院救治伤员的医生，见证着战争的残酷。',
        baseStats: { strength: 10, intelligence: 25, charisma: 20, luck: 15, health: 60, special: 15 },
        exclusiveEvents: ["field_hospital", "life_save"],
        specialTrait: '仁心',
        spawnWeight: 10,
      },
      {
        id: 'reporter_gs',
        name: '记者',
        description: '报道战争真相的记者，用文字对抗谎言。',
        baseStats: { strength: 10, intelligence: 25, charisma: 20, luck: 20, health: 50, special: 15 },
        exclusiveEvents: ["war_report", "truth_reveal"],
        specialTrait: '真相',
        spawnWeight: 14,
      },
    ],
    npcs: [
      {
        id: 'kira',
        name: '基拉',
        type: 'mentor',
        description: '最强调整者，拥有SEED能力的王牌机师',
        avatar: '👤',
        introEvent: '基拉从自由高达上下来，目光中带着战争带来的疲惫。',
        maxRelationshipEvents: ["基拉微笑着说：我终于找到了不用战斗也能保护大家的方法。"],
      },
      {
        id: 'murrue',
        name: '玛琉',
        type: 'mentor',
        description: '大天使号舰长，坚韧不拔的女性指挥官',
        avatar: '👤',
        introEvent: '玛琉站在舰桥上，目光坚定地注视着前方的战场。',
        maxRelationshipEvents: ["玛琉将舰长的位置传给了你，说：这艘船，交给你了。"],
      },
      {
        id: 'lacus',
        name: '拉克丝',
        type: 'romance',
        description: 'PLANT的歌姬，用歌声传递和平的希望',
        avatar: '💕',
        introEvent: '拉克丝的歌声在宇宙中回荡，那是对和平的祈愿。',
        maxRelationshipEvents: ["拉克丝握住你的手，轻声说：让我们一起创造没有战争的世界。"],
      },
      {
        id: 'cagalli',
        name: '卡嘉莉',
        type: 'romance',
        description: '奥布的公主，性格刚烈却内心温柔',
        avatar: '💕',
        introEvent: '卡嘉莉叉着腰瞪着你，眼中却藏着不易察觉的关心。',
        maxRelationshipEvents: ["卡嘉莉第一次露出了脆弱的一面，靠在你的肩膀上哭泣。"],
      },
      {
        id: 'athrun',
        name: '阿斯兰',
        type: 'rival',
        description: 'ZAFT的王牌机师，正义高达的驾驶者',
        avatar: '⚔️',
        introEvent: '阿斯兰驾驶着正义高达挡在你面前，目光复杂。',
        maxRelationshipEvents: ["阿斯兰伸出手，说：我们再也不用战斗了，朋友。"],
      },
      {
        id: 'creuset',
        name: '克鲁泽',
        type: 'rival',
        description: '面具下的复仇者，对人类充满憎恨的克隆人',
        avatar: '⚔️',
        introEvent: '克鲁泽摘下面具，露出与你一模一样的脸，诡异地笑了。',
        maxRelationshipEvents: ["克鲁泽在消散前，第一次露出了释然的表情。"],
      },
    ],
  },
  // ============================================================
  // 某科学的超电磁炮
  // ============================================================
  {
    id: 'railgun',
    name: '某科学的超电磁炮',
    nameEn: 'A Certain Scientific Railgun',
    description: '学园都市，一座以开发超能力为目的的城市。在这里，能力等级决定一切，而无能力者也有属于自己的战斗方式。',
    themeColor: '#F39C12',
    statNames: {
      strength: '体能',
      intelligence: '计算力',
      charisma: '人缘',
      luck: '开发潜力',
      health: '生命力',
      special: '能力等级',
    },
    identities: [
      {
        id: 'academy_student',
        name: '常盘台学生',
        description: '常盘台中学的大小姐学生，拥有优秀的教养与潜力。',
        baseStats: { strength: 15, intelligence: 25, charisma: 20, luck: 20, health: 60, special: 25 },
        exclusiveEvents: ["academy_life", "ability_dev"],
        specialTrait: '大小姐',
        spawnWeight: 18,
      },
      {
        id: 'judgement',
        name: '风纪委员',
        description: '维护学园都市治安的风纪委员，正义感强烈。',
        baseStats: { strength: 20, intelligence: 20, charisma: 20, luck: 15, health: 70, special: 20 },
        exclusiveEvents: ["judgement_duty", "city_patrol"],
        specialTrait: '正义',
        spawnWeight: 12,
      },
      {
        id: 'dark_side',
        name: '暗部成员',
        description: '在学园都市暗处活动的特殊成员，手段冷酷。',
        baseStats: { strength: 25, intelligence: 20, charisma: 5, luck: 15, health: 65, special: 25 },
        exclusiveEvents: ["dark_mission", "underground_world"],
        specialTrait: '暗影',
        spawnWeight: 8,
      },
      {
        id: 'researcher',
        name: '研究员',
        description: '研究超能力的科学家，为了科学不惜一切代价。',
        baseStats: { strength: 10, intelligence: 35, charisma: 10, luck: 15, health: 50, special: 25 },
        exclusiveEvents: ["ability_research", "experiment_subject"],
        specialTrait: '科学狂',
        spawnWeight: 8,
      },
      {
        id: 'level_0',
        name: '无能力者',
        description: '没有能力等级的普通人，在学园都市的底层挣扎。',
        baseStats: { strength: 15, intelligence: 15, charisma: 15, luck: 20, health: 55, special: 5 },
        exclusiveEvents: ["level_0_struggle", "ordinary_hero"],
        specialTrait: '无能力',
        spawnWeight: 15,
      },
      {
        id: 'esper',
        name: '能力者',
        description: '拥有超能力的学生，能力各不相同。',
        baseStats: { strength: 20, intelligence: 20, charisma: 15, luck: 15, health: 65, special: 30 },
        exclusiveEvents: ["ability_awakening", "power_training"],
        specialTrait: '能力者',
        spawnWeight: 15,
      },
      {
        id: 'teacher',
        name: '教师',
        description: '学园都市的教师，负责指导学生开发能力。',
        baseStats: { strength: 15, intelligence: 25, charisma: 20, luck: 10, health: 60, special: 20 },
        exclusiveEvents: ["teaching_life", "student_guidance"],
        specialTrait: '良师',
        spawnWeight: 10,
      },
      {
        id: 'merchant_rg',
        name: '商人',
        description: '在学园都市经营店铺的普通商人。',
        baseStats: { strength: 10, intelligence: 20, charisma: 25, luck: 20, health: 55, special: 10 },
        exclusiveEvents: ["shop_management", "city_commerce"],
        specialTrait: '精明',
        spawnWeight: 10,
      },
      {
        id: 'hacker_rg',
        name: '黑客',
        description: '擅长侵入学园都市网络系统的黑客。',
        baseStats: { strength: 10, intelligence: 30, charisma: 10, luck: 20, health: 50, special: 20 },
        exclusiveEvents: ["network_intrusion", "info_warfare"],
        specialTrait: '黑客',
        spawnWeight: 8,
      },
      {
        id: 'reporter_rg',
        name: '记者',
        description: '报道学园都市内幕的记者，冒着危险追寻真相。',
        baseStats: { strength: 10, intelligence: 25, charisma: 20, luck: 20, health: 50, special: 15 },
        exclusiveEvents: ["city_report", "conspiracy_uncover"],
        specialTrait: '真相',
        spawnWeight: 16,
      },
    ],
    npcs: [
      {
        id: 'misaka',
        name: '御坂美琴',
        type: 'mentor',
        description: '学园都市第三位的超电磁炮，最强的电击使',
        avatar: '👤',
        introEvent: '硬币在御坂美琴指尖旋转，电光在她周围噼啪作响。',
        maxRelationshipEvents: ["御坂美琴第一次露出了安心的笑容，说：有你在，我就不会输。"],
      },
      {
        id: 'touma',
        name: '上条当麻',
        type: 'mentor',
        description: '拥有幻想杀手的无能力者，用右手打破一切异能',
        avatar: '👤',
        introEvent: '上条当麻挠挠头，右手的绷带下隐藏着改变命运的力量。',
        maxRelationshipEvents: ["上条当麻笑着说：只要没有放弃，就一定还有希望。"],
      },
      {
        id: 'kuroko',
        name: '白井黑子',
        type: 'romance',
        description: '空间移动能力者，对美琴有着特殊的感情',
        avatar: '💕',
        introEvent: '白井黑子突然出现在你面前，目光中带着审视与好奇。',
        maxRelationshipEvents: ["白井黑子红着脸说：就算是姐姐大人以外的人，你...你也还不错啦。"],
      },
      {
        id: 'misaki',
        name: '食蜂操祈',
        type: 'rival',
        description: '学园都市第五位的心理掌握，女王般的存在',
        avatar: '⚔️',
        introEvent: '食蜂操祈用星星眼注视着你，仿佛要看透你的内心。',
        maxRelationshipEvents: ["食蜂操祈第一次放下了女王的架子，露出了真实的笑容。"],
      },
      {
        id: 'accelerator',
        name: '一方通行',
        type: 'rival',
        description: '学园都市第一位的矢量操作，最强也最孤独',
        avatar: '⚔️',
        introEvent: '一方通行冷笑着，脚下的地面因矢量操控而碎裂。',
        maxRelationshipEvents: ["一方通行别过脸说：哼，你这家伙...还算有点意思。"],
      },
      {
        id: 'uiharu',
        name: '初春饰利',
        type: 'romance',
        description: '风纪委员，擅长情报处理的少女，头上总是戴着花环',
        avatar: '💕',
        introEvent: '初春饰利在电脑前忙碌着，头上的花环随着动作轻轻晃动。',
        maxRelationshipEvents: ["初春饰利笑着说：能遇到你，是我最大的幸运。"],
      },
    ],
  },
  // ============================================================
  // Fate/stay night
  // ============================================================
  {
    id: 'fate',
    name: 'Fate/stay night',
    nameEn: 'Fate/stay night',
    description: '圣杯战争，七位魔术师与七位从者之间的生死厮杀。在欲望与理想交织的战场上，少年做出了自己的选择。',
    themeColor: '#C0392B',
    statNames: {
      strength: '魔力',
      intelligence: '魔术回路',
      charisma: '家世',
      luck: '命运',
      health: '生命力',
      special: '宝具',
    },
    identities: [
      {
        id: 'master',
        name: '御主',
        description: '参加圣杯战争的魔术师，与从者缔结契约。',
        baseStats: { strength: 15, intelligence: 25, charisma: 15, luck: 20, health: 60, special: 25 },
        exclusiveEvents: ["command_spell", "servant_summon"],
        specialTrait: '令咒',
        spawnWeight: 18,
      },
      {
        id: 'servant',
        name: '从者',
        description: '被召唤的英灵，为实现御主的愿望而战。',
        baseStats: { strength: 30, intelligence: 15, charisma: 20, luck: 15, health: 85, special: 35 },
        exclusiveEvents: ["heroic_spirit", "noble_phantasm"],
        specialTrait: '英灵',
        spawnWeight: 10,
      },
      {
        id: 'magus',
        name: '魔术师',
        description: '追求根源的魔术师，为了到达真理不择手段。',
        baseStats: { strength: 15, intelligence: 30, charisma: 15, luck: 15, health: 55, special: 30 },
        exclusiveEvents: ["magic_research", "root_pursuit"],
        specialTrait: '根源',
        spawnWeight: 12,
      },
      {
        id: 'church',
        name: '教会代行者',
        description: '圣堂教会的代行者，负责监督圣杯战争。',
        baseStats: { strength: 20, intelligence: 20, charisma: 20, luck: 15, health: 70, special: 20 },
        exclusiveEvents: ["church_duty", "heretic_judgement"],
        specialTrait: '代行',
        spawnWeight: 8,
      },
      {
        id: 'dead_apostle',
        name: '死徒',
        description: '吸血鬼化的存在，在黑暗中寻求永生。',
        baseStats: { strength: 25, intelligence: 20, charisma: 5, luck: 15, health: 90, special: 30 },
        exclusiveEvents: ["vampire_awakening", "blood_thirst"],
        specialTrait: '吸血',
        spawnWeight: 5,
      },
      {
        id: 'guardian_fate',
        name: '守护者',
        description: '抑止力的守护者，在时空的夹缝中消灭威胁人理的存在。',
        baseStats: { strength: 25, intelligence: 20, charisma: 10, luck: 10, health: 80, special: 35 },
        exclusiveEvents: ["counter_guardian", "timeless_battle"],
        specialTrait: '守护',
        spawnWeight: 5,
      },
      {
        id: 'ordinary_fate',
        name: '普通人',
        description: '被卷入圣杯战争的普通人，在魔术与英灵的世界中挣扎求生。',
        baseStats: { strength: 10, intelligence: 15, charisma: 15, luck: 25, health: 50, special: 10 },
        exclusiveEvents: ["accidental_war", "ordinary_courage"],
        specialTrait: '平凡',
        spawnWeight: 15,
      },
      {
        id: 'alchemist_fate',
        name: '炼金术师',
        description: '钻研炼金术的魔术师，追求物质的转化与黄金的完美。',
        baseStats: { strength: 15, intelligence: 30, charisma: 10, luck: 15, health: 55, special: 25 },
        exclusiveEvents: ["alchemy_research", "perfect_gold"],
        specialTrait: '炼金',
        spawnWeight: 8,
      },
      {
        id: 'archaeologist_fate',
        name: '考古学家',
        description: '研究英灵与圣遗物的考古学家，知晓许多被遗忘的历史。',
        baseStats: { strength: 10, intelligence: 30, charisma: 15, luck: 20, health: 50, special: 20 },
        exclusiveEvents: ["relic_discovery", "ancient_hero"],
        specialTrait: '考古',
        spawnWeight: 9,
      },
      {
        id: 'supervisor',
        name: '圣杯战争监督',
        description: '监督圣杯战争公正进行的监督者，维持着表面上的秩序。',
        baseStats: { strength: 20, intelligence: 25, charisma: 20, luck: 10, health: 65, special: 20 },
        exclusiveEvents: ["war_supervision", "rule_enforcement"],
        specialTrait: '监督',
        spawnWeight: 10,
      },
    ],
    npcs: [
      {
        id: 'shirou',
        name: '卫宫士郎',
        type: 'mentor',
        description: '理想主义的少年，想要成为正义的伙伴',
        avatar: '👤',
        introEvent: '卫宫士郎在仓库中练习着投影魔术，目光坚定而单纯。',
        maxRelationshipEvents: ["卫宫士郎微笑着说：我终于明白了，正义的伙伴，就是保护重要的人。"],
      },
      {
        id: 'saber',
        name: '阿尔托莉雅',
        type: 'romance',
        description: '古不列颠的骑士王，手持誓约胜利之剑',
        avatar: '💕',
        introEvent: '金色的光芒中，一位银发少女骑士显现，目光如剑般锐利。',
        maxRelationshipEvents: ["阿尔托莉雅卸下了王者的铠甲，第一次以少女的身份笑了。"],
      },
      {
        id: 'rin',
        name: '远坂凛',
        type: 'romance',
        description: '远坂家的继承人，天才魔术师，傲娇而善良',
        avatar: '💕',
        introEvent: '远坂凛叉着腰瞪着你，红宝石般的眼眸中闪过一丝慌乱。',
        maxRelationshipEvents: ["远坂凛红着脸转过头：笨蛋，才不是因为喜欢你呢！"],
      },
      {
        id: 'gilgamesh',
        name: '吉尔伽美什',
        type: 'rival',
        description: '最古老的英雄王，拥有世间所有的宝具',
        avatar: '⚔️',
        introEvent: '金色的涟漪在空间中展开，英雄王居高临下地俯视着你。',
        maxRelationshipEvents: ["吉尔伽美什第一次认可了人类，说：杂修，你是本王唯一承认的对手。"],
      },
      {
        id: 'kotomine',
        name: '言峰绮礼',
        type: 'rival',
        description: '圣杯战争的监督者，追求愉悦的扭曲神父',
        avatar: '⚔️',
        introEvent: '言峰绮礼露出了意味深长的笑容，仿佛在欣赏一场戏剧。',
        maxRelationshipEvents: ["言峰绮礼在最后的时刻，终于理解了真正的愉悦是什么。"],
      },
      {
        id: 'illya',
        name: '伊莉雅',
        type: 'romance',
        description: '爱因兹贝伦的人造人，既是御主也是从者',
        avatar: '💕',
        introEvent: '伊莉雅坐在城堡的窗边，紫色的眼眸中满是对亲情的渴望。',
        maxRelationshipEvents: ["伊莉雅第一次感受到了真正的温暖，那是家人的感觉。"],
      },
    ],
  },
  // ============================================================
  // 辉夜大小姐想让我告白
  // ============================================================
  {
    id: 'kaguya',
    name: '辉夜大小姐想让我告白',
    nameEn: 'Kaguya-sama: Love is War',
    description: '秀知院学园，天才们的聚集地。在这里，恋爱不是甜蜜的告白，而是一场高智商的头脑战争。先告白的人就输了。',
    themeColor: '#E91E63',
    statNames: {
      strength: '策略',
      intelligence: '谋略',
      charisma: '魅力',
      luck: '恋爱运',
      health: '精力',
      special: '头脑战',
    },
    identities: [
      {
        id: 'president',
        name: '学生会会长',
        description: '秀知院的学生会会长，文武双全的完美天才。',
        baseStats: { strength: 20, intelligence: 30, charisma: 25, luck: 15, health: 70, special: 30 },
        exclusiveEvents: ["president_duty", "perfect_image"],
        specialTrait: '全能',
        spawnWeight: 12,
      },
      {
        id: 'vice_president',
        name: '学生会副会长',
        description: '学生会的副会长，与会长暗中较劲的天才。',
        baseStats: { strength: 25, intelligence: 30, charisma: 20, luck: 15, health: 65, special: 30 },
        exclusiveEvents: ["vice_scheme", "rivalry_game"],
        specialTrait: '傲娇',
        spawnWeight: 12,
      },
      {
        id: 'secretary',
        name: '书记',
        description: '学生会的书记，纯真而活泼，是气氛的制造者。',
        baseStats: { strength: 10, intelligence: 20, charisma: 30, luck: 20, health: 60, special: 20 },
        exclusiveEvents: ["secretary_song", "pure_chaos"],
        specialTrait: '纯真',
        spawnWeight: 15,
      },
      {
        id: 'accountant',
        name: '会计',
        description: '学生会的会计，表面阴郁实则内心温柔的少年。',
        baseStats: { strength: 15, intelligence: 25, charisma: 10, luck: 20, health: 55, special: 25 },
        exclusiveEvents: ["accountant_dark", "hidden_kindness"],
        specialTrait: '阴郁',
        spawnWeight: 12,
      },
      {
        id: 'ordinary_student',
        name: '普通学生',
        description: '秀知院的普通学生，在天才们之间努力生存。',
        baseStats: { strength: 10, intelligence: 15, charisma: 15, luck: 20, health: 55, special: 10 },
        exclusiveEvents: ["ordinary_life", "school_days"],
        specialTrait: '平凡',
        spawnWeight: 20,
      },
      {
        id: 'special_student',
        name: '特招生',
        description: '通过特招进入秀知院的学生，用努力弥补天赋的差距。',
        baseStats: { strength: 15, intelligence: 20, charisma: 15, luck: 15, health: 60, special: 15 },
        exclusiveEvents: ["special_exam", "hard_work"],
        specialTrait: '努力',
        spawnWeight: 15,
      },
      {
        id: 'teacher_kg',
        name: '教师',
        description: '秀知院的教师，在天才学生们之间维持着微妙的平衡。',
        baseStats: { strength: 15, intelligence: 25, charisma: 20, luck: 10, health: 60, special: 20 },
        exclusiveEvents: ["teaching_genius", "class_management"],
        specialTrait: '良师',
        spawnWeight: 10,
      },
      {
        id: 'butler',
        name: '管家',
        description: '服务于大财阀的管家，精通一切杂务与情报工作。',
        baseStats: { strength: 20, intelligence: 20, charisma: 15, luck: 15, health: 65, special: 20 },
        exclusiveEvents: ["butler_duty", "master_service"],
        specialTrait: '全能执事',
        spawnWeight: 8,
      },
      {
        id: 'reporter_kg',
        name: '记者',
        description: '学园新闻部的记者，追逐着学生会长的八卦新闻。',
        baseStats: { strength: 10, intelligence: 20, charisma: 20, luck: 25, health: 50, special: 15 },
        exclusiveEvents: ["scoop_hunt", "love_rumor"],
        specialTrait: '八卦',
        spawnWeight: 10,
      },
      {
        id: 'rich_second',
        name: '富二代',
        description: '大财阀的继承人，在金钱与权力中长大。',
        baseStats: { strength: 15, intelligence: 20, charisma: 25, luck: 15, health: 65, special: 20 },
        exclusiveEvents: ["rich_life", "inheritance_pressure"],
        specialTrait: '金汤匙',
        spawnWeight: 16,
      },
    ],
    npcs: [
      {
        id: 'kaguya_npc',
        name: '四宫辉夜',
        type: 'mentor',
        description: '四宫家的大小姐，学生会的副会长，傲娇的恋爱天才',
        avatar: '👤',
        introEvent: '四宫辉夜优雅地端起茶杯，目光中却闪过一丝不易察觉的慌乱。',
        maxRelationshipEvents: ["四宫辉夜第一次坦率地说：我...我想和你在一起。"],
      },
      {
        id: 'miyuki',
        name: '白银御行',
        type: 'mentor',
        description: '秀知院的学生会会长，靠努力弥补家境的天才',
        avatar: '👤',
        introEvent: '白银御行认真地整理着文件，眼中满是不服输的倔强。',
        maxRelationshipEvents: ["白银御行露出了释然的笑容：无论是会长还是普通人，我都想站在你身边。"],
      },
      {
        id: 'chika',
        name: '藤原千花',
        type: 'romance',
        description: '学生会的书记，纯真活泼的天然系',
        avatar: '💕',
        introEvent: '藤原千花突然从门后跳出来，脸上挂着灿烂的笑容。',
        maxRelationshipEvents: ["藤原千花眨着眼睛说：要不要跟我一起去做些有趣的事情？"],
      },
      {
        id: 'ishigami',
        name: '石上优',
        type: 'rival',
        description: '学生会的会计，被误解的不良少年，内心温柔',
        avatar: '⚔️',
        introEvent: '石上优阴郁地低着头，仿佛整个世界都与他为敌。',
        maxRelationshipEvents: ["石上优第一次露出了真心的笑容：谢谢你，没有放弃我。"],
      },
      {
        id: 'hayasa',
        name: '早坂爱',
        type: 'romance',
        description: '辉夜的侍女，多才多艺的完美女仆',
        avatar: '💕',
        introEvent: '早坂爱以完美的微笑为你端上红茶，眼中却藏着试探。',
        maxRelationshipEvents: ["早坂爱卸下了女仆的面具，露出了真实的自我：这是我第一次为自己而活。"],
      },
      {
        id: 'ino',
        name: '伊井野弥子',
        type: 'rival',
        description: '风纪委员长，正义感爆棚的认真少女',
        avatar: '⚔️',
        introEvent: '伊井野弥子手持风纪手册，一脸严肃地盯着你。',
        maxRelationshipEvents: ["伊井野弥子红着脸说：虽然你违反了风纪...但我不讨厌你。"],
      },
    ],
  },
];

export function getWorldById(id: string): World | undefined {
  return worlds.find((w) => w.id === id);
}
