import type { EventTemplate } from './types';

// 科幻星际 — 164 event templates
// Generated: 2026-04-27
// Rarity tiers: legendary(≤0.10) / epic(0.10-0.25) / rare(0.25-0.50) / common(0.50-0.85) / trash-exclusive
// Each template has 3-5 text variations, total ~656 actual events

export const scifiTemplates: EventTemplate[] = [
  {
    id: 'sf_ch_01', category: 'childhood', minAge: 0, maxAge: 3, probability: 0.044,
    templates: [
      '你出生那天，{location}突然霞光万丈，紫气东来三千里。{npc}跪地叩拜，说你是千年一遇的完美进化。',
      '你降生的瞬间，{location}百花齐放，{legend}的虚影在天际显现，整个大陆为之震动。',
      '你的第一声啼哭引发了{location}的灵气暴动，{npc}颤抖着说："完美进化降世了！"',
    ],
    effects: { luck: 10, special: 8, charisma: 5 },
  },
  {
    id: 'sf_ch_02', category: 'childhood', minAge: 2, maxAge: 7, probability: 0.151,
    templates: [
      '你在{location}玩耍时，体内突然涌出一股热流。{npc}惊讶地发现你竟是优良基因之资！',
      '三岁时，你在{location}无意间触发了古老的检测阵法，光芒比所有人都亮。',
      '{npc}为你进行资质测试，{legend}的印记在你身上一闪而逝——你是被选中的人。',
    ],
    effects: { special: 6, intelligence: 4 },
  },
  {
    id: 'sf_ch_03', category: 'childhood', minAge: 4, maxAge: 9, probability: 0.28,
    templates: [
      '你在{location}救了一只受伤的小动物，它其实是{legend}的化身，临走前留下了一枚灵珠。',
      '{npc}在你满月时送了一块玉佩，后来你发现那是一件上古法器的碎片。',
      '你从小就能看见别人看不见的{legend}幻影，{npc}说这是灵根初现的征兆。',
      '你在{location}挖到了一坛古酒，喝了一口后浑身舒畅，经脉隐隐发热。',
    ],
    effects: { special: 4 },
  },
  {
    id: 'sf_ch_04', category: 'childhood', minAge: 0, maxAge: 6, probability: 0.548,
    templates: [
      '你生在普通人家，每天在{location}玩耍，日子平淡但快乐。',
      '{npc}教你读书识字，你学得有模有样。',
      '你在{location}认识了几个玩伴，度过了无忧无虑的童年。',
      '家里虽然不富裕，但{npc}总是把最好的留给你。',
    ],
    effects: { charisma: 2, luck: 1 },
  },
  {
    id: 'sf_ch_05', category: 'childhood', minAge: 3, maxAge: 10, probability: 0.704,
    templates: [
      '你在{location}帮{npc}干活，学会了很多生活技能。',
      '你的身体比同龄人强壮，{npc}说你是干农活的好料子。',
      '你喜欢在{location}发呆，常常一坐就是一整天。',
      '{npc}给你讲了一个关于{legend}的故事，你听得入了迷。',
    ],
    effects: { strength: 2, intelligence: 1 },
  },
  {
    id: 'sf_gr_01', category: 'growth', minAge: 15, maxAge: 20, probability: 0.055,
    templates: [
      '你在{location}闭关三日，出关时眼中精光四射——你竟在战斗中顿悟了{legend}的传承！',
      '一场雷雨夜，你在{location}被天雷击中非但没死，反而打通了全身经脉！',
      '{legend}的残魂在{location}与你相遇，将毕生感悟传授于你。',
    ],
    effects: { intelligence: 10, special: 8, strength: 5 },
  },
  {
    id: 'sf_gr_02', category: 'growth', minAge: 14, maxAge: 22, probability: 0.153,
    templates: [
      '你在{location}苦修三年，终于突破了困扰多年的瓶颈，实力大增！',
      '{npc}带你外出历练，你在{location}击败了一个强敌，获得了珍贵的战利品。',
      '你发现了{legend}留下的试炼场，通过考验后获得了意想不到的收获。',
    ],
    effects: { strength: 6, special: 5 },
  },
  {
    id: 'sf_gr_03', category: 'growth', minAge: 13, maxAge: 24, probability: 0.262,
    templates: [
      '你在{location}遇到了一生的宿敌，你们不打不相识，反而成为了朋友。',
      '{npc}传授你一项绝技，你花了整整一年才学会，但威力惊人。',
      '你在{location}救了一个被追杀的人，他为了报答你，送了一件宝物。',
      '你和同辈在{location}比试，虽然输了但收获巨大。',
    ],
    effects: { charisma: 4 },
  },
  {
    id: 'sf_gr_04', category: 'growth', minAge: 13, maxAge: 20, probability: 0.575,
    templates: [
      '你每天在{location}勤奋练习，虽然进步缓慢但根基扎实。',
      '{npc}督促你修炼，你不敢懈怠。',
      '你在{location}读了很多书，眼界开阔了不少。',
      '平平淡淡的一年，你在{location}默默积累着。',
    ],
    effects: { intelligence: 2, strength: 2 },
  },
  {
    id: 'sf_gr_05', category: 'growth', minAge: 16, maxAge: 25, probability: 0.739,
    templates: [
      '你在{location}结交了一些朋友，互相切磋进步。',
      '{npc}给你讲了很多前辈的故事，你深受启发。',
      '你在{location}处理了一些杂务，锻炼了自己的能力。',
      '这一年没什么特别的事发生，但你感觉自己在慢慢变强。',
    ],
    effects: { charisma: 2, luck: 2 },
  },
  {
    id: 'sf_ad_01', category: 'adult', minAge: 28, maxAge: 40, probability: 0.139,
    templates: [
      '你在{location}开宗立派，广收门徒，一时间名声大噪。',
      '你参与了{legend}相关的大规模事件，在关键时刻力挽狂澜。',
      '你在{location}建立了属于自己的势力，各方强者纷纷来投。',
    ],
    effects: { charisma: 8, strength: 5, special: 5 },
  },
  {
    id: 'sf_ad_02', category: 'adult', minAge: 26, maxAge: 45, probability: 0.282,
    templates: [
      '你在{location}收下了第一个弟子，将自己的所学倾囊相授。',
      '你和宿敌在{location}进行了最终决战，胜负难分。',
      '你成功炼制/制造了传说中的物品，引起了不小的轰动。',
    ],
    effects: { intelligence: 5, special: 4 },
  },
  {
    id: 'sf_ad_03', category: 'adult', minAge: 26, maxAge: 50, probability: 0.521,
    templates: [
      '你在{location}处理日常事务，势力稳步发展。',
      '{npc}来找你帮忙，你出手解决了他的难题。',
      '你在{location}度过了平静的一年，修为稳步提升。',
      '平平淡淡的一年，你在{location}默默修炼。',
    ],
    effects: { strength: 2, intelligence: 2, special: 2 },
  },
  {
    id: 'sf_el_01', category: 'elder', minAge: 55, maxAge: 80, probability: 0.371,
    templates: [
      '你的修为已臻化境，成为了{location}的传说级人物。',
      '你开始着手准备最终的突破，{npc}专程前来为你护法。',
      '你将毕生所学整理成册，存放在{location}，等待有缘人。',
    ],
    effects: { intelligence: 8, charisma: 5 },
  },
  {
    id: 'sf_el_02', category: 'elder', minAge: 51, maxAge: 100, probability: 0.667,
    templates: [
      '你在{location}颐养天年，每日种花养鱼，不问世事。',
      '你的身体开始衰退，但精神愈发强大。',
      '你决定将力量传承给下一代，{npc}成为了你的传人。',
    ],
    effects: { health: -3, intelligence: 3 },
  },
  {
    id: 'sf_cb_01', category: 'combat', minAge: 20, maxAge: 40, probability: 0.034,
    templates: [
      '你在{location}以一己之力对抗十位同阶强者，最终大获全胜，一战成名！',
      '{legend}的敌人找上了你，你在{location}展开惊天大战，竟越级将其斩杀！',
      '你为了保护{location}的居民，独自对抗入侵的{legend}军团，创造了不可能的奇迹。',
    ],
    effects: { strength: 12, charisma: 8, health: -10 },
  },
  {
    id: 'sf_cb_02', category: 'combat', minAge: 18, maxAge: 45, probability: 0.129,
    templates: [
      '你参与了一场改变{location}格局的大规模战争，立下赫赫战功。',
      '{npc}挑战你的权威，你们在{location}大战三百回合，最终你险胜一招。',
      '你在{location}发现了{legend}留下的试炼场，通过了生死考验。',
    ],
    effects: { strength: 8, charisma: 4, health: -5 },
  },
  {
    id: 'sf_cb_03', category: 'combat', minAge: 15, maxAge: 35, probability: 0.31,
    templates: [
      '你在{location}遭遇强敌，展开了一场生死搏斗，最终险胜。',
      '你和{npc}在{location}切磋，双方都获益匪浅。',
      '你为了保护同伴，在{location}与敌人激战，受了轻伤。',
    ],
    effects: { strength: 5, health: -3 },
  },
  {
    id: 'sf_cb_04', category: 'combat', minAge: 25, maxAge: 50, probability: 0.399,
    templates: [
      '你在{location}参与了一场小规模冲突，表现出色。',
      '{npc}偷袭你，你在{location}勉强将其击退。',
      '你在{location}发现了敌人的据点，果断出击。',
    ],
    effects: { strength: 4, luck: 2 },
  },
  {
    id: 'sf_cb_05', category: 'combat', minAge: 15, maxAge: 40, probability: 0.525,
    templates: [
      '你在{location}进行了日常训练，技艺略有精进。',
      '你和同伴在{location}对练，互相学习。',
      '你在{location}演练新学的招式，逐渐熟练。',
    ],
    effects: { strength: 2 },
  },
  {
    id: 'sf_cb_06', category: 'combat', minAge: 30, maxAge: 60, probability: 0.741,
    templates: [
      '你在{location}指导后辈战斗技巧，自己也有所感悟。',
      '一场友好的比试在{location}举行，你获得了不错的名次。',
      '你在{location}观摩高手对决，学到了不少实战经验。',
    ],
    effects: { strength: 2, intelligence: 1 },
  },
  {
    id: 'sf_rm_01', category: 'romance', minAge: 18, maxAge: 30, probability: 0.045,
    templates: [
      '你在{location}与{npc}相遇的瞬间，天地变色，{legend}的预言应验——你们是三生石上的命定之人。',
      '{npc}为了救你，不惜耗尽毕生修为。你跪在{location}发誓：此生不负。',
      '你们的故事被{legend}记载，成为了{location}永恒的传说。',
    ],
    effects: { charisma: 10, luck: 8, health: 5 },
  },
  {
    id: 'sf_rm_02', category: 'romance', minAge: 20, maxAge: 35, probability: 0.126,
    templates: [
      '你在{location}邂逅了一位神秘的{npc}，TA的身份让你震惊不已。',
      '{npc}对你一见倾心，经常在{location}找你，你们的感情迅速升温。',
      '你们经历了{legend}的考验，感情反而更加坚不可摧。',
    ],
    effects: { charisma: 6, luck: 4 },
  },
  {
    id: 'sf_rm_03', category: 'romance', minAge: 16, maxAge: 30, probability: 0.281,
    templates: [
      '你救了一位落难的{npc}，TA决定以身相许，你们在{location}私定终身。',
      '你和{npc}在{location}月下相会，互诉衷肠。',
      '{npc}因为你的才华而倾心，主动向你示好。',
    ],
    effects: { charisma: 4, luck: 3 },
  },
  {
    id: 'sf_rm_04', category: 'romance', minAge: 25, maxAge: 40, probability: 0.43,
    templates: [
      '你和{npc}在{location}相识，虽然起初有些误会，但后来成为了恋人。',
      '{npc}送你一件定情信物，你珍藏在身边。',
      '你们一起在{location}经历了危险，感情更加深厚。',
    ],
    effects: { charisma: 3, luck: 2 },
  },
  {
    id: 'sf_rm_05', category: 'romance', minAge: 20, maxAge: 45, probability: 0.51,
    templates: [
      '你在{location}认识了一个有趣的人，但关系尚不明确。',
      '{npc}对你有些好感，但你还没想好如何回应。',
      '你在{location}参加了一场聚会，结识了不少异性。',
    ],
    effects: { charisma: 2 },
  },
  {
    id: 'sf_rm_06', category: 'romance', minAge: 30, maxAge: 50, probability: 0.713,
    templates: [
      '你和{npc}保持着朋友以上、恋人未满的关系。',
      '你在{location}看到了别人恩爱的场景，心中有些羡慕。',
      '这一年感情上没有太大的波澜，你专注于其他事情。',
    ],
    effects: { luck: 1 },
  },
  {
    id: 'sf_cultivation_01', category: 'cultivation', minAge: 40, maxAge: 70, probability: 0.063,
    templates: [
      '你在{location}闭关九九八十一天，出关时天地共鸣，你已触摸到了{legend}的境界！',
      '你的修为达到了前所未有的高度，{location}的灵气因为你而沸腾。',
      '{legend}的虚影亲自降临{location}，为你指点大道。',
    ],
    effects: { special: 12, intelligence: 10, strength: 5 },
  },
  {
    id: 'sf_cultivation_02', category: 'cultivation', minAge: 30, maxAge: 60, probability: 0.158,
    templates: [
      '你成功将{legend}的功法融会贯通，实力暴涨！',
      '你在{location}经历了一场奇遇，修为大涨，连{npc}都震惊不已。',
      '你突破了困扰多年的瓶颈，{location}的天地异象持续了三日三夜。',
    ],
    effects: { special: 8, intelligence: 5 },
  },
  {
    id: 'sf_cultivation_03', category: 'cultivation', minAge: 20, maxAge: 50, probability: 0.255,
    templates: [
      '你在{location}闭关修炼，领悟了新的境界。',
      '{npc}传授你一项绝技，你勤加练习，终于大成。',
      '你在{location}发现了一处灵气充沛的宝地，修炼事半功倍。',
    ],
    effects: { special: 5, intelligence: 3 },
  },
  {
    id: 'sf_cultivation_04', category: 'cultivation', minAge: 35, maxAge: 65, probability: 0.377,
    templates: [
      '你在修炼中遇到了瓶颈，{npc}指点你突破。',
      '你在{location}经历了一场奇遇，修为有所精进。',
      '你成功炼制/制造了辅助修炼的物品，效果显著。',
    ],
    effects: { special: 4, strength: 2 },
  },
  {
    id: 'sf_cultivation_05', category: 'cultivation', minAge: 13, maxAge: 40, probability: 0.559,
    templates: [
      '你在{location}按部就班地修炼，虽然没有突破但根基更加稳固。',
      '{npc}检查了你的修炼进度，表示满意。',
      '你在{location}研读功法秘籍，对一些招式有了新的理解。',
    ],
    effects: { special: 2, intelligence: 1 },
  },
  {
    id: 'sf_cultivation_06', category: 'cultivation', minAge: 40, maxAge: 80, probability: 0.729,
    templates: [
      '你在{location}巩固已有的修为，为下一次突破做准备。',
      '这一年修炼进度平平，但你没有气馁。',
      '{npc}提醒你不可急于求成，你虚心接受。',
    ],
    effects: { special: 2 },
  },
  {
    id: 'sf_ex_01', category: 'exploration', minAge: 25, maxAge: 50, probability: 0.059,
    templates: [
      '你深入{location}最深处，发现了{legend}留下的核心传承，获得了改变命运的机缘！',
      '你在{location}找到了通往另一个维度的入口，{legend}的秘密向你敞开。',
      '你解开了一个困扰世人万年的谜题，{location}的真相让你震惊。',
    ],
    effects: { luck: 10, intelligence: 8, special: 6 },
  },
  {
    id: 'sf_ex_02', category: 'exploration', minAge: 20, maxAge: 45, probability: 0.172,
    templates: [
      '你在{location}找到了{legend}留下的遗迹，虽然危险重重但你决定一探究竟。',
      '你探索了一处危险的{location}，九死一生后带回了珍贵的宝物。',
      '{npc}告诉你{location}有宝物，你前去寻找，果然不虚此行。',
    ],
    effects: { luck: 6, strength: 4 },
  },
  {
    id: 'sf_ex_03', category: 'exploration', minAge: 15, maxAge: 40, probability: 0.268,
    templates: [
      '你深入{location}探险，发现了未知的秘密。',
      '你在{location}找到了一些有价值的物品，收获颇丰。',
      '你在{location}迷路了，却意外发现了一处隐蔽的洞天福地。',
    ],
    effects: { luck: 4, strength: 2 },
  },
  {
    id: 'sf_ex_04', category: 'exploration', minAge: 30, maxAge: 55, probability: 0.432,
    templates: [
      '你在{location}发现了一些古老的壁画，记录着失落的文明。',
      '你探索了一处废弃的{location}，找到了一些有用的物资。',
      '{npc}带你进入了一个秘密的{location}，你大开眼界。',
    ],
    effects: { intelligence: 3, luck: 3 },
  },
  {
    id: 'sf_ex_05', category: 'exploration', minAge: 13, maxAge: 35, probability: 0.568,
    templates: [
      '你在{location}附近逛了逛，虽然没有大发现但开阔了眼界。',
      '你跟着{npc}去{location}采集了一些材料。',
      '你在{location}发现了一些普通的草药，聊胜于无。',
    ],
    effects: { luck: 2 },
  },
  {
    id: 'sf_ex_06', category: 'exploration', minAge: 35, maxAge: 70, probability: 0.74,
    templates: [
      '你在{location}进行了常规的巡查，一切正常。',
      '你重访了以前去过的{location}，有了一些新的发现。',
      '你在{location}休息了一段时间，养精蓄锐。',
    ],
    effects: { health: 2 },
  },
  {
    id: 'sf_ws_01', category: 'world_story', minAge: 40, maxAge: 70, probability: 0.036,
    templates: [
      '{legend}的封印彻底破碎，整个世界陷入了前所未有的动荡，你被卷入了漩涡中心！',
      '一场席卷整个世界的大战爆发了，{location}首当其冲，你必须做出选择。',
      '世界的规则开始改变，{legend}的意志降临，所有人都受到了影响。',
    ],
    effects: { strength: 8, intelligence: 8, charisma: 5, luck: 5 },
  },
  {
    id: 'sf_ws_02', category: 'world_story', minAge: 30, maxAge: 60, probability: 0.166,
    templates: [
      '你发现{location}隐藏着改变世界的秘密，各方势力为此展开了明争暗斗。',
      '{npc}告诉你一个关于世界起源的惊天秘密，你的世界观被彻底颠覆。',
      '传说中的{legend}即将降临，所有人都在做准备，{location}的气氛紧张到了极点。',
    ],
    effects: { intelligence: 6, charisma: 4 },
  },
  {
    id: 'sf_ws_03', category: 'world_story', minAge: 25, maxAge: 50, probability: 0.27,
    templates: [
      '{location}附近发生了局部冲突，你不得不卷入其中。',
      '{npc}带来了一个重要的消息，可能影响到{location}的未来。',
      '你注意到了{location}的一些异常现象，似乎有什么大事要发生。',
    ],
    effects: { charisma: 3, luck: 3 },
  },
  {
    id: 'sf_ws_04', category: 'world_story', minAge: 20, maxAge: 45, probability: 0.54,
    templates: [
      '你听到了一些关于{legend}的传闻，但真假难辨。',
      '{location}发生了一些小变化，但你没有太在意。',
      '{npc}跟你聊了聊最近的时事，你表示关注。',
    ],
    effects: { intelligence: 2 },
  },
  {
    id: 'sf_ws_05', category: 'world_story', minAge: 40, maxAge: 80, probability: 0.737,
    templates: [
      '世界依旧平静，{location}的生活一如既往。',
      '你听说了一些关于{legend}的新消息，但似乎没什么实质内容。',
      '这一年没什么大事发生，你在{location}安稳度日。',
    ],
    effects: { luck: 1 },
  },
  {
    id: 'sf_hd_01', category: 'hidden', minAge: 60, maxAge: 120, probability: 0.048,
    templates: [
      '你超越了{legend}，看到了世界之外的真相——原来一切都只是...',
      '你发现了这个世界的运行规则，{location}只是一场巨大棋局的一角。',
      '{legend}的真正身份让你震惊不已，你终于理解了世界的本质。',
    ],
    effects: { intelligence: 15, special: 10 },
    conditions: [
      { stat: 'intelligence', min: 120 },
    ],
  },
  {
    id: 'sf_hd_02', category: 'hidden', minAge: 50, maxAge: 100, probability: 0.124,
    templates: [
      '你在{location}发现了一个被禁止入内的区域，里面藏着惊人的秘密。',
      '你解开了{legend}留下的谜题，获得了一份隐藏的传承。',
      '{npc}告诉你一个只有极少数人知道的秘密，你感到责任重大。',
    ],
    effects: { intelligence: 10, special: 8 },
    conditions: [
      { stat: 'intelligence', min: 100 },
    ],
  },
  {
    id: 'sf_hd_03', category: 'hidden', minAge: 35, maxAge: 80, probability: 0.309,
    templates: [
      '你在{location}找到了一条隐秘的通道，通向未知的地方。',
      '你发现了一些关于{legend}的隐藏记录，内容令人费解。',
      '{npc}偷偷塞给你一张地图，上面标记着{location}的秘密地点。',
    ],
    effects: { luck: 6, intelligence: 4 },
    conditions: [
      { stat: 'luck', min: 80 },
    ],
  },
  {
    id: 'sf_hd_04', category: 'hidden', minAge: 20, maxAge: 60, probability: 0.56,
    templates: [
      '你在{location}听到了一些奇怪的低语，但找不到来源。',
      '你做了一个关于{legend}的怪梦，醒来后记忆模糊。',
      '{npc}欲言又止，似乎想告诉你什么秘密但最终没说出口。',
    ],
    effects: { intelligence: 3 },
    conditions: [
      { stat: 'intelligence', min: 60 },
    ],
  },
  {
    id: 'sf_dt_01', category: 'death', minAge: 0, maxAge: 100, probability: 0.35,
    templates: [
      '你在{location}遭遇不测，生命力迅速流逝。',
      '你的身体到达了极限，{npc}无能为力。',
      '{legend}的诅咒降临在你身上，你无法抵抗。',
    ],
    effects: { health: -60 },
  },
  {
    id: 'sf_dt_02', category: 'death', minAge: 0, maxAge: 150, probability: 0.45,
    templates: [
      '你在{location}进行了最后的战斗，英勇牺牲。',
      '寿元耗尽，你在{location}静静地闭上了眼睛。',
      '你走火入魔，在{location}化为灰烬。',
    ],
    effects: { health: -80 },
  },
  {
    id: 'sf_dt_03', category: 'death', minAge: 0, maxAge: 200, probability: 0.55,
    templates: [
      '你在{location}被强敌击杀，死不瞑目。',
      '你的伤势恶化，{npc}尽力抢救但回天乏术。',
      '{legend}的力量反噬，你在{location}形神俱灭。',
    ],
    effects: { health: -100 },
  },
  {
    id: 'sf_dt_04', category: 'death', minAge: 0, maxAge: 250, probability: 0.65,
    templates: [
      '你在{location}寿终正寝，周围的人都来为你送行。',
      '你安详地在{location}离世，一生无憾。',
      '{npc}守在你的床前，目送你离开这个世界。',
    ],
    effects: { health: -100 },
  },
  {
    id: 'sf_dt_05', category: 'death', minAge: 0, maxAge: 300, probability: 0.75,
    templates: [
      '你在{location}结束了这一生，灵魂化作流光消散。',
      '你的故事成为了{location}的传说，后人会记得你的名字。',
      '{legend}亲自前来接引你的灵魂，你感到一阵温暖。',
    ],
    effects: { health: -100 },
  },
  {
    id: 'sf_ws_06', category: 'world_story', minAge: 15, maxAge: 15, probability: 0.98,
    templates: [
      '你站在{location}的中央，人生第一次面临真正的抉择。{npc}告诉你，前方有三条路：追求极致的力量、无拘无束的自由，或者守护一切的觉悟。你的选择将改变你的一生。',
    ],
    choices: [
      { text: '追求力量', successRate: 0.7, successText: '你选择了力量之路，从此一往无前，无人能挡', failText: '你选择了力量之路，却发现代价远超想象', effects: { strength: 10, special: 5 }, failEffects: { health: -20, strength: 3 }, flags: ['major_power'], failFlags: ['major_power_fail'] },
      { text: '追求自由', successRate: 0.75, successText: '你选择了自由之路，天地广阔任逍遥', failText: '自由之路充满荆棘，你在{location}迷失了方向', effects: { luck: 10, intelligence: 5 }, failEffects: { luck: -8, charisma: -5 }, flags: ['major_freedom'], failFlags: ['major_freedom_fail'] },
      { text: '追求守护', successRate: 0.8, successText: '你选择了守护之路，成为弱者的支柱', failText: '你的善意被利用，在{location}身心俱疲', effects: { charisma: 8, health: 10 }, failEffects: { charisma: -8, health: -15 }, flags: ['major_guardian'], failFlags: ['major_guardian_fail'] },
    ],
    flags: ['major_seen_15'],
  },
  {
    id: 'sf_ws_07', category: 'world_story', minAge: 20, maxAge: 28, probability: 0.85,
    templates: [
      '因为你选择了力量之路，{location}的强者对你另眼相看。你的力量引起了{legend}的注意。',
      '你在追求力量的过程中，在{location}发现了一本失传已久的强大功法。',
    ],
    effects: { strength: 6, special: 3 },
    flags: ['major_power_1'],
    requiredFlags: ['major_power'],
  },
  {
    id: 'sf_ws_08', category: 'world_story', minAge: 30, maxAge: 40, probability: 0.8,
    templates: [
      '你因为追求力量而获得了强大的实力，但{npc}警告你不要迷失本心。你在{location}展现出的力量让所有人畏惧。',
      '你的力量达到了新的高度，{legend}亲自前来与你切磋，你从中领悟了许多。',
    ],
    effects: { strength: 8, charisma: -3 },
    requiredFlags: ['major_power_1'],
  },
  {
    id: 'sf_ws_09', category: 'world_story', minAge: 20, maxAge: 28, probability: 0.85,
    templates: [
      '你因为选择了自由之路，在{location}结识了来自各地的奇人异士。你的自由精神感染了{npc}。',
      '你在自由探索中意外发现了{legend}留下的隐秘线索，命运的齿轮开始转动。',
    ],
    effects: { luck: 6, intelligence: 4 },
    flags: ['major_freedom_1'],
    requiredFlags: ['major_freedom'],
  },
  {
    id: 'sf_ws_10', category: 'world_story', minAge: 30, maxAge: 40, probability: 0.8,
    templates: [
      '你在自由之路上的探索让你发现了{location}不为人知的秘密。{legend}的遗迹因为你的一次偶然探索而被发现。',
      '{npc}告诉你，你的自由精神正是{legend}当年所追求的，你冥冥之中走上了正确的道路。',
    ],
    effects: { luck: 8, special: 4 },
    requiredFlags: ['major_freedom_1'],
  },
  {
    id: 'sf_ws_11', category: 'world_story', minAge: 20, maxAge: 28, probability: 0.85,
    templates: [
      '你因为选择了守护之路，在{location}被无数人敬仰。{npc}因为你的守护而得以存活，发誓永远追随你。',
      '你守护的人们在{location}为你建立了一座小小的祠堂，虽然简陋但充满诚意。',
    ],
    effects: { charisma: 6, health: 5 },
    flags: ['major_guardian_1'],
    requiredFlags: ['major_guardian'],
  },
  {
    id: 'sf_ws_12', category: 'world_story', minAge: 30, maxAge: 40, probability: 0.8,
    templates: [
      '你守护的人在{location}遭遇了危机，你毫不犹豫地挺身而出。你的守护之名传遍了四方。',
      '{legend}也对你的品德表示赞赏，亲自赐予你一份守护者的传承。',
    ],
    effects: { charisma: 8, strength: 4 },
    requiredFlags: ['major_guardian_1'],
  },
  {
    id: 'sf_ws_13', category: 'world_story', minAge: 30, maxAge: 30, probability: 0.97,
    templates: [
      '{location}发生了一件震动天下的大事。{npc}向你提出了一个交易：违背本心可获巨大利益，坚守正义则可能失去一切。这是对你灵魂的考验。',
    ],
    choices: [
      { text: '坚守本心', successRate: 0.65, successText: '你拒绝了诱惑，虽然失去了眼前的利益，但道心更加坚定', failText: '你坚守了本心，却遭到了黑暗势力的疯狂报复', effects: { intelligence: 8, charisma: 5 }, failEffects: { health: -20, strength: -5 }, flags: ['major_justice'], failFlags: ['major_justice_fail'] },
      { text: '不择手段', successRate: 0.55, successText: '你获得了梦寐以求的力量与财富，但内心开始有了一丝阴霾', failText: '你的阴谋被揭穿，在{location}声名狼藉', effects: { strength: 10, special: 5 }, failEffects: { charisma: -15, luck: -10 }, flags: ['major_dark'], failFlags: ['major_dark_fail'] },
    ],
    flags: ['major_seen_30'],
  },
  {
    id: 'sf_ws_14', category: 'world_story', minAge: 35, maxAge: 45, probability: 0.82,
    templates: [
      '因为你坚守了本心，{legend}亲自降临{location}为你加持。你的正义之名吸引了无数志同道合者。',
      '你在{location}建立了一个正义的据点，成为了黑暗势力的眼中钉。',
    ],
    effects: { intelligence: 6, charisma: 6, luck: 4 },
    requiredFlags: ['major_justice'],
  },
  {
    id: 'sf_ws_15', category: 'world_story', minAge: 35, maxAge: 45, probability: 0.82,
    templates: [
      '你因为不择手段而获得了强大的力量，但{npc}看你的眼神变得复杂。你在{location}建立了自己的势力。',
      '{legend}因为你的黑暗之路而对你产生了兴趣，这是福是祸尚未可知。',
    ],
    effects: { strength: 8, special: 6, charisma: -5 },
    requiredFlags: ['major_dark'],
  },
  {
    id: 'sf_ws_16', category: 'world_story', minAge: 45, maxAge: 45, probability: 0.96,
    templates: [
      '你遭遇了人生中最危险的敌人。{legend}的化身出现在{location}，向你发起挑战。所有人都认为你没有胜算。这是生死抉择的时刻。',
    ],
    choices: [
      { text: '以命相搏', successRate: 0.45, successText: '你拼尽一切，竟然真的战胜了{legend}的化身！天下震动！', failText: '你拼死一战，虽然重创了敌人，但自己也命悬一线', effects: { strength: 12, charisma: 8 }, failEffects: { health: -40, strength: 5 }, flags: ['major_bravery'], failFlags: ['major_bravery_fail'] },
      { text: '忍辱求生', successRate: 0.75, successText: '你选择了暂时退让，保存实力等待时机。智者不逞匹夫之勇', failText: '你的退让被当作懦弱，{location}的人开始轻视你', effects: { intelligence: 8, luck: 5 }, failEffects: { charisma: -10, luck: -5 }, flags: ['major_wisdom'], failFlags: ['major_wisdom_fail'] },
    ],
    flags: ['major_seen_45'],
  },
  {
    id: 'sf_ws_17', category: 'world_story', minAge: 48, maxAge: 58, probability: 0.8,
    templates: [
      '你战胜{legend}化身的壮举传遍了整个世界，{location}的人都把你当作英雄。你的勇气激励了无数人。',
      '{npc}说你是万古以来最勇敢的人，你的名字将被刻入{location}的历史。',
    ],
    effects: { strength: 6, charisma: 8, luck: 4 },
    requiredFlags: ['major_bravery'],
  },
  {
    id: 'sf_ws_18', category: 'world_story', minAge: 48, maxAge: 58, probability: 0.8,
    templates: [
      '你忍辱负重后的反击让所有人震惊，{location}的敌人在你最强的时刻倒下。',
      '{npc}赞叹你的智慧——不争一时之长短，方得始终。你的名声反而比以前更盛。',
    ],
    effects: { intelligence: 8, luck: 6, special: 4 },
    requiredFlags: ['major_wisdom'],
  },
  {
    id: 'sf_ws_19', category: 'world_story', minAge: 60, maxAge: 60, probability: 0.95,
    templates: [
      '你站在{location}的最高处，俯瞰着这个世界。{legend}的最后传承出现在你面前：追求永恒的极致，或者守护人间直到最后一刻。这是你的终极抉择。',
    ],
    choices: [
      { text: '追求永恒', successRate: 0.6, successText: '你踏上了追求永恒的道路，从此与天地同寿。但你回头望去，发现身后已空无一人', failText: '你追求永恒的尝试失败了，但你无怨无悔', effects: { special: 15, intelligence: 10 }, failEffects: { health: -30, special: 5 }, flags: ['major_eternal'], failFlags: ['major_eternal_fail'] },
      { text: '守护人间', successRate: 0.8, successText: '你选择了守护人间，将自己的一切都奉献给了这个世界。后人将永远记得你的名字', failText: '你的守护让你耗尽了一切，但你知道这是值得的', effects: { charisma: 12, health: 10, luck: 8 }, failEffects: { health: -20, charisma: 5 }, flags: ['major_legacy'], failFlags: ['major_legacy_fail'] },
    ],
    flags: ['major_seen_60'],
  },
  {
    id: 'sf_ws_20', category: 'world_story', minAge: 65, maxAge: 80, probability: 0.78,
    templates: [
      '你追求永恒的道路越走越远，{location}的凡尘俗世已与你无关。你触摸到了{legend}的境界。',
      '你获得了永恒的生命，但内心却越来越孤独。你开始怀疑当初的选择。',
    ],
    effects: { special: 10, intelligence: 8, charisma: -5 },
    requiredFlags: ['major_eternal'],
  },
  {
    id: 'sf_ws_21', category: 'world_story', minAge: 65, maxAge: 80, probability: 0.78,
    templates: [
      '你守护人间的举动感动了无数人，{location}建起了你的雕像。你的传承在{npc}手中延续。',
      '这个世界因为你的存在而更加美好，{legend}也为你的选择而动容。',
    ],
    effects: { charisma: 10, luck: 8, health: 5 },
    requiredFlags: ['major_legacy'],
  },
  {
    id: 'sf_ie_colonist_01', category: 'identity_exclusive', minAge: 3, maxAge: 8, probability: 0.85,
    templates: [
      '作为殖民者后代，你从小就展现出与众不同的天赋。荒野求生的特质在你体内蠢蠢欲动。',
      '你在{location}经历了一件改变一生的事，那是殖民者后代的命运转折点。',
      '{npc}看出了你是殖民者后代的苗子，决定暗中帮助你。',
      '你体内的荒野求生之力在{location}第一次觉醒。',
    ],
    effects: { intelligence: 5 },
    flags: ['chain_colonist_childhood_0'],
    identityExclusive: 'colonist',
  },
  {
    id: 'sf_ie_colonist_02', category: 'identity_exclusive', minAge: 7, maxAge: 12, probability: 0.85,
    templates: [
      '作为殖民者后代，你从小就展现出与众不同的天赋。殖民地危机的特质在你体内蠢蠢欲动。',
      '你在{location}经历了一件改变一生的事，那是殖民者后代的命运转折点。',
      '{npc}看出了你是殖民者后代的苗子，决定暗中帮助你。',
      '你体内的殖民地危机之力在{location}第一次觉醒。',
    ],
    effects: { intelligence: 5 },
    flags: ['chain_colonist_childhood_1'],
    identityExclusive: 'colonist',
  },
  {
    id: 'sf_ie_colonist_03', category: 'identity_exclusive', minAge: 14, maxAge: 20, probability: 0.8,
    templates: [
      '作为殖民者后代，你在{location}遇到了星球改造的试炼。',
      '你的殖民者后代身份让你在{location}陷入了困境。',
      '{npc}因为你的殖民者后代身份而对你另眼相看。',
      '你在{location}觉醒了殖民者后代特有的能力。',
    ],
    effects: { special: 6 },
    flags: ['chain_colonist_growth_0'],
    requiredFlags: ['chain_colonist_childhood_0'],
    identityExclusive: 'colonist',
    chainPriority: 1,
  },
  {
    id: 'sf_ie_colonist_04', category: 'identity_exclusive', minAge: 19, maxAge: 25, probability: 0.8,
    templates: [
      '作为殖民者后代，你在{location}遇到了星球改造的试炼。',
      '你的殖民者后代身份让你在{location}陷入了困境。',
      '{npc}因为你的殖民者后代身份而对你另眼相看。',
      '你在{location}觉醒了殖民者后代特有的能力。',
    ],
    effects: { strength: 6 },
    flags: ['chain_colonist_growth_1'],
    requiredFlags: ['chain_colonist_childhood_0'],
    identityExclusive: 'colonist',
    chainPriority: 1,
  },
  {
    id: 'sf_ie_colonist_05', category: 'identity_exclusive', minAge: 26, maxAge: 35, probability: 0.75,
    templates: [
      '作为殖民者后代，你在{location}迎来了人生的重要转折点——边疆之王。',
      '你的殖民者后代之路在{location}遭遇了最大的挑战。',
      '{legend}的传说与你的殖民者后代身份产生了某种联系。',
      '你在{location}做出了一个关乎殖民者后代命运的重要决定。',
    ],
    effects: { strength: 8 },
    flags: ['chain_colonist_adult_0'],
    requiredFlags: ['chain_colonist_growth_0'],
    identityExclusive: 'colonist',
    chainPriority: 2,
  },
  {
    id: 'sf_ie_colonist_06', category: 'identity_exclusive', minAge: 36, maxAge: 45, probability: 0.75,
    templates: [
      '作为殖民者后代，你在{location}迎来了人生的重要转折点——边疆之王。',
      '你的殖民者后代之路在{location}遭遇了最大的挑战。',
      '{legend}的传说与你的殖民者后代身份产生了某种联系。',
      '你在{location}做出了一个关乎殖民者后代命运的重要决定。',
    ],
    choices: [
      { text: '坚持殖民者后代之道', successRate: 0.5, successText: '你成功了，边疆之王之力大增', failText: '你失败了，但收获经验', effects: { special: 10, strength: 5 }, failEffects: { intelligence: 5, health: -5 }, flags: ['branch_identity_colonist_path'], failFlags: ['branch_identity_colonist_path_fail'] },
      { text: '另辟蹊径', successRate: 0.7, successText: '你找到了新的道路', failText: '你迷失了方向', effects: { luck: 5, charisma: 5 }, failEffects: { luck: -3 }, flags: ['branch_identity_colonist_new'], failFlags: ['branch_identity_colonist_new_fail'] },
    ],
    flags: ['chain_colonist_adult_1'],
    requiredFlags: ['chain_colonist_growth_0'],
    identityExclusive: 'colonist',
    chainPriority: 2,
  },
  {
    id: 'sf_ie_colonist_07', category: 'identity_exclusive', minAge: 10, maxAge: 30, probability: 0.7,
    templates: [
      '作为殖民者后代，你与{legend}产生了宿命般的纠葛。',
      '你在{location}发现了关于殖民者后代起源的秘密。',
      '{npc}揭示了一个关于殖民者后代的惊天秘密。',
      '你的殖民者后代血脉在{location}发生了异变。',
    ],
    effects: { strength: 8, luck: 5 },
    flags: ['chain_colonist_special_0'],
    requiredFlags: ['chain_colonist_adult_0'],
    identityExclusive: 'colonist',
    chainPriority: 3,
  },
  {
    id: 'sf_ie_colonist_08', category: 'identity_exclusive', minAge: 30, maxAge: 60, probability: 0.7,
    templates: [
      '作为殖民者后代，你与{legend}产生了宿命般的纠葛。',
      '你在{location}发现了关于殖民者后代起源的秘密。',
      '{npc}揭示了一个关于殖民者后代的惊天秘密。',
      '你的殖民者后代血脉在{location}发生了异变。',
    ],
    effects: { special: 10, health: -5 },
    flags: ['chain_colonist_special_1'],
    requiredFlags: ['chain_colonist_adult_0'],
    identityExclusive: 'colonist',
    chainPriority: 3,
  },
  {
    id: 'sf_ie_space_noble_01', category: 'identity_exclusive', minAge: 3, maxAge: 8, probability: 0.85,
    templates: [
      '作为星际贵族，你从小就展现出与众不同的天赋。政治联姻的特质在你体内蠢蠢欲动。',
      '你在{location}经历了一件改变一生的事，那是星际贵族的命运转折点。',
      '{npc}看出了你是星际贵族的苗子，决定暗中帮助你。',
      '你体内的政治联姻之力在{location}第一次觉醒。',
    ],
    effects: { special: 5 },
    flags: ['chain_space_noble_childhood_0'],
    identityExclusive: 'space_noble',
  },
  {
    id: 'sf_ie_space_noble_02', category: 'identity_exclusive', minAge: 7, maxAge: 12, probability: 0.85,
    templates: [
      '作为星际贵族，你从小就展现出与众不同的天赋。权力斗争的特质在你体内蠢蠢欲动。',
      '你在{location}经历了一件改变一生的事，那是星际贵族的命运转折点。',
      '{npc}看出了你是星际贵族的苗子，决定暗中帮助你。',
      '你体内的权力斗争之力在{location}第一次觉醒。',
    ],
    effects: { strength: 4, luck: 2 },
    flags: ['chain_space_noble_childhood_1'],
    identityExclusive: 'space_noble',
  },
  {
    id: 'sf_ie_space_noble_03', category: 'identity_exclusive', minAge: 14, maxAge: 20, probability: 0.8,
    templates: [
      '作为星际贵族，你在{location}遇到了家族荣耀的试炼。',
      '你的星际贵族身份让你在{location}陷入了困境。',
      '{npc}因为你的星际贵族身份而对你另眼相看。',
      '你在{location}觉醒了星际贵族特有的能力。',
    ],
    effects: { intelligence: 6 },
    flags: ['chain_space_noble_growth_0'],
    requiredFlags: ['chain_space_noble_childhood_0'],
    identityExclusive: 'space_noble',
    chainPriority: 1,
  },
  {
    id: 'sf_ie_space_noble_04', category: 'identity_exclusive', minAge: 19, maxAge: 25, probability: 0.8,
    templates: [
      '作为星际贵族，你在{location}遇到了家族荣耀的试炼。',
      '你的星际贵族身份让你在{location}陷入了困境。',
      '{npc}因为你的星际贵族身份而对你另眼相看。',
      '你在{location}觉醒了星际贵族特有的能力。',
    ],
    effects: { intelligence: 6 },
    flags: ['chain_space_noble_growth_1'],
    requiredFlags: ['chain_space_noble_childhood_0'],
    identityExclusive: 'space_noble',
    chainPriority: 1,
  },
  {
    id: 'sf_ie_space_noble_05', category: 'identity_exclusive', minAge: 26, maxAge: 35, probability: 0.75,
    templates: [
      '作为星际贵族，你在{location}迎来了人生的重要转折点——星际政治。',
      '你的星际贵族之路在{location}遭遇了最大的挑战。',
      '{legend}的传说与你的星际贵族身份产生了某种联系。',
      '你在{location}做出了一个关乎星际贵族命运的重要决定。',
    ],
    effects: { strength: 8 },
    flags: ['chain_space_noble_adult_0'],
    requiredFlags: ['chain_space_noble_growth_0'],
    identityExclusive: 'space_noble',
    chainPriority: 2,
  },
  {
    id: 'sf_ie_space_noble_06', category: 'identity_exclusive', minAge: 36, maxAge: 45, probability: 0.75,
    templates: [
      '作为星际贵族，你在{location}迎来了人生的重要转折点——星际政治。',
      '你的星际贵族之路在{location}遭遇了最大的挑战。',
      '{legend}的传说与你的星际贵族身份产生了某种联系。',
      '你在{location}做出了一个关乎星际贵族命运的重要决定。',
    ],
    choices: [
      { text: '坚持星际贵族之道', successRate: 0.5, successText: '你成功了，星际政治之力大增', failText: '你失败了，但收获经验', effects: { special: 10, strength: 5 }, failEffects: { intelligence: 5, health: -5 }, flags: ['branch_identity_space_noble_path'], failFlags: ['branch_identity_space_noble_path_fail'] },
      { text: '另辟蹊径', successRate: 0.7, successText: '你找到了新的道路', failText: '你迷失了方向', effects: { luck: 5, charisma: 5 }, failEffects: { luck: -3 }, flags: ['branch_identity_space_noble_new'], failFlags: ['branch_identity_space_noble_new_fail'] },
    ],
    flags: ['chain_space_noble_adult_1'],
    requiredFlags: ['chain_space_noble_growth_0'],
    identityExclusive: 'space_noble',
    chainPriority: 2,
  },
  {
    id: 'sf_ie_space_noble_07', category: 'identity_exclusive', minAge: 10, maxAge: 30, probability: 0.7,
    templates: [
      '作为星际贵族，你与{legend}产生了宿命般的纠葛。',
      '你在{location}发现了关于星际贵族起源的秘密。',
      '{npc}揭示了一个关于星际贵族的惊天秘密。',
      '你的星际贵族血脉在{location}发生了异变。',
    ],
    effects: { strength: 8, luck: 5 },
    flags: ['chain_space_noble_special_0'],
    requiredFlags: ['chain_space_noble_adult_0'],
    identityExclusive: 'space_noble',
    chainPriority: 3,
  },
  {
    id: 'sf_ie_space_noble_08', category: 'identity_exclusive', minAge: 30, maxAge: 60, probability: 0.7,
    templates: [
      '作为星际贵族，你与{legend}产生了宿命般的纠葛。',
      '你在{location}发现了关于星际贵族起源的秘密。',
      '{npc}揭示了一个关于星际贵族的惊天秘密。',
      '你的星际贵族血脉在{location}发生了异变。',
    ],
    effects: { strength: 8, luck: 5 },
    flags: ['chain_space_noble_special_1'],
    requiredFlags: ['chain_space_noble_adult_0'],
    identityExclusive: 'space_noble',
    chainPriority: 3,
  },
  {
    id: 'sf_ie_cyborg_01', category: 'identity_exclusive', minAge: 3, maxAge: 8, probability: 0.85,
    templates: [
      '作为机械改造人，你从小就展现出与众不同的天赋。系统升级的特质在你体内蠢蠢欲动。',
      '你在{location}经历了一件改变一生的事，那是机械改造人的命运转折点。',
      '{npc}看出了你是机械改造人的苗子，决定暗中帮助你。',
      '你体内的系统升级之力在{location}第一次觉醒。',
    ],
    effects: { strength: 4, luck: 2 },
    flags: ['chain_cyborg_childhood_0'],
    identityExclusive: 'cyborg',
  },
  {
    id: 'sf_ie_cyborg_02', category: 'identity_exclusive', minAge: 7, maxAge: 12, probability: 0.85,
    templates: [
      '作为机械改造人，你从小就展现出与众不同的天赋。人性流失的特质在你体内蠢蠢欲动。',
      '你在{location}经历了一件改变一生的事，那是机械改造人的命运转折点。',
      '{npc}看出了你是机械改造人的苗子，决定暗中帮助你。',
      '你体内的人性流失之力在{location}第一次觉醒。',
    ],
    effects: { special: 5 },
    flags: ['chain_cyborg_childhood_1'],
    identityExclusive: 'cyborg',
  },
  {
    id: 'sf_ie_cyborg_03', category: 'identity_exclusive', minAge: 14, maxAge: 20, probability: 0.8,
    templates: [
      '作为机械改造人，你在{location}遇到了机械觉醒的试炼。',
      '你的机械改造人身份让你在{location}陷入了困境。',
      '{npc}因为你的机械改造人身份而对你另眼相看。',
      '你在{location}觉醒了机械改造人特有的能力。',
    ],
    effects: { special: 6 },
    flags: ['chain_cyborg_growth_0'],
    requiredFlags: ['chain_cyborg_childhood_0'],
    identityExclusive: 'cyborg',
    chainPriority: 1,
  },
  {
    id: 'sf_ie_cyborg_04', category: 'identity_exclusive', minAge: 19, maxAge: 25, probability: 0.8,
    templates: [
      '作为机械改造人，你在{location}遇到了机械觉醒的试炼。',
      '你的机械改造人身份让你在{location}陷入了困境。',
      '{npc}因为你的机械改造人身份而对你另眼相看。',
      '你在{location}觉醒了机械改造人特有的能力。',
    ],
    effects: { charisma: 4, luck: 3 },
    flags: ['chain_cyborg_growth_1'],
    requiredFlags: ['chain_cyborg_childhood_0'],
    identityExclusive: 'cyborg',
    chainPriority: 1,
  },
  {
    id: 'sf_ie_cyborg_05', category: 'identity_exclusive', minAge: 26, maxAge: 35, probability: 0.75,
    templates: [
      '作为机械改造人，你在{location}迎来了人生的重要转折点——赛博飞升。',
      '你的机械改造人之路在{location}遭遇了最大的挑战。',
      '{legend}的传说与你的机械改造人身份产生了某种联系。',
      '你在{location}做出了一个关乎机械改造人命运的重要决定。',
    ],
    effects: { strength: 8 },
    flags: ['chain_cyborg_adult_0'],
    requiredFlags: ['chain_cyborg_growth_0'],
    identityExclusive: 'cyborg',
    chainPriority: 2,
  },
  {
    id: 'sf_ie_cyborg_06', category: 'identity_exclusive', minAge: 36, maxAge: 45, probability: 0.75,
    templates: [
      '作为机械改造人，你在{location}迎来了人生的重要转折点——赛博飞升。',
      '你的机械改造人之路在{location}遭遇了最大的挑战。',
      '{legend}的传说与你的机械改造人身份产生了某种联系。',
      '你在{location}做出了一个关乎机械改造人命运的重要决定。',
    ],
    choices: [
      { text: '坚持机械改造人之道', successRate: 0.5, successText: '你成功了，赛博飞升之力大增', failText: '你失败了，但收获经验', effects: { special: 10, strength: 5 }, failEffects: { intelligence: 5, health: -5 }, flags: ['branch_identity_cyborg_path'], failFlags: ['branch_identity_cyborg_path_fail'] },
      { text: '另辟蹊径', successRate: 0.7, successText: '你找到了新的道路', failText: '你迷失了方向', effects: { luck: 5, charisma: 5 }, failEffects: { luck: -3 }, flags: ['branch_identity_cyborg_new'], failFlags: ['branch_identity_cyborg_new_fail'] },
    ],
    flags: ['chain_cyborg_adult_1'],
    requiredFlags: ['chain_cyborg_growth_0'],
    identityExclusive: 'cyborg',
    chainPriority: 2,
  },
  {
    id: 'sf_ie_cyborg_07', category: 'identity_exclusive', minAge: 10, maxAge: 30, probability: 0.7,
    templates: [
      '作为机械改造人，你与{legend}产生了宿命般的纠葛。',
      '你在{location}发现了关于机械改造人起源的秘密。',
      '{npc}揭示了一个关于机械改造人的惊天秘密。',
      '你的机械改造人血脉在{location}发生了异变。',
    ],
    effects: { strength: 8, luck: 5 },
    flags: ['chain_cyborg_special_0'],
    requiredFlags: ['chain_cyborg_adult_0'],
    identityExclusive: 'cyborg',
    chainPriority: 3,
  },
  {
    id: 'sf_ie_cyborg_08', category: 'identity_exclusive', minAge: 30, maxAge: 60, probability: 0.7,
    templates: [
      '作为机械改造人，你与{legend}产生了宿命般的纠葛。',
      '你在{location}发现了关于机械改造人起源的秘密。',
      '{npc}揭示了一个关于机械改造人的惊天秘密。',
      '你的机械改造人血脉在{location}发生了异变。',
    ],
    effects: { intelligence: 10 },
    flags: ['chain_cyborg_special_1'],
    requiredFlags: ['chain_cyborg_adult_0'],
    identityExclusive: 'cyborg',
    chainPriority: 3,
  },
  {
    id: 'sf_ie_alien_hybrid_01', category: 'identity_exclusive', minAge: 3, maxAge: 8, probability: 0.85,
    templates: [
      '作为外星混血，你从小就展现出与众不同的天赋。异族认同的特质在你体内蠢蠢欲动。',
      '你在{location}经历了一件改变一生的事，那是外星混血的命运转折点。',
      '{npc}看出了你是外星混血的苗子，决定暗中帮助你。',
      '你体内的异族认同之力在{location}第一次觉醒。',
    ],
    effects: { intelligence: 5 },
    flags: ['chain_alien_hybrid_childhood_0'],
    identityExclusive: 'alien_hybrid',
  },
  {
    id: 'sf_ie_alien_hybrid_02', category: 'identity_exclusive', minAge: 7, maxAge: 12, probability: 0.85,
    templates: [
      '作为外星混血，你从小就展现出与众不同的天赋。基因暴走的特质在你体内蠢蠢欲动。',
      '你在{location}经历了一件改变一生的事，那是外星混血的命运转折点。',
      '{npc}看出了你是外星混血的苗子，决定暗中帮助你。',
      '你体内的基因暴走之力在{location}第一次觉醒。',
    ],
    effects: { strength: 4, luck: 2 },
    flags: ['chain_alien_hybrid_childhood_1'],
    identityExclusive: 'alien_hybrid',
  },
  {
    id: 'sf_ie_alien_hybrid_03', category: 'identity_exclusive', minAge: 14, maxAge: 20, probability: 0.8,
    templates: [
      '作为外星混血，你在{location}遇到了混血优势的试炼。',
      '你的外星混血身份让你在{location}陷入了困境。',
      '{npc}因为你的外星混血身份而对你另眼相看。',
      '你在{location}觉醒了外星混血特有的能力。',
    ],
    effects: { strength: 6 },
    flags: ['chain_alien_hybrid_growth_0'],
    requiredFlags: ['chain_alien_hybrid_childhood_0'],
    identityExclusive: 'alien_hybrid',
    chainPriority: 1,
  },
  {
    id: 'sf_ie_alien_hybrid_04', category: 'identity_exclusive', minAge: 19, maxAge: 25, probability: 0.8,
    templates: [
      '作为外星混血，你在{location}遇到了混血优势的试炼。',
      '你的外星混血身份让你在{location}陷入了困境。',
      '{npc}因为你的外星混血身份而对你另眼相看。',
      '你在{location}觉醒了外星混血特有的能力。',
    ],
    effects: { special: 6 },
    flags: ['chain_alien_hybrid_growth_1'],
    requiredFlags: ['chain_alien_hybrid_childhood_0'],
    identityExclusive: 'alien_hybrid',
    chainPriority: 1,
  },
  {
    id: 'sf_ie_alien_hybrid_05', category: 'identity_exclusive', minAge: 26, maxAge: 35, probability: 0.75,
    templates: [
      '作为外星混血，你在{location}迎来了人生的重要转折点——星际桥梁。',
      '你的外星混血之路在{location}遭遇了最大的挑战。',
      '{legend}的传说与你的外星混血身份产生了某种联系。',
      '你在{location}做出了一个关乎外星混血命运的重要决定。',
    ],
    effects: { strength: 8 },
    flags: ['chain_alien_hybrid_adult_0'],
    requiredFlags: ['chain_alien_hybrid_growth_0'],
    identityExclusive: 'alien_hybrid',
    chainPriority: 2,
  },
  {
    id: 'sf_ie_alien_hybrid_06', category: 'identity_exclusive', minAge: 36, maxAge: 45, probability: 0.75,
    templates: [
      '作为外星混血，你在{location}迎来了人生的重要转折点——星际桥梁。',
      '你的外星混血之路在{location}遭遇了最大的挑战。',
      '{legend}的传说与你的外星混血身份产生了某种联系。',
      '你在{location}做出了一个关乎外星混血命运的重要决定。',
    ],
    choices: [
      { text: '坚持外星混血之道', successRate: 0.5, successText: '你成功了，星际桥梁之力大增', failText: '你失败了，但收获经验', effects: { special: 10, strength: 5 }, failEffects: { intelligence: 5, health: -5 }, flags: ['branch_identity_alien_hybrid_path'], failFlags: ['branch_identity_alien_hybrid_path_fail'] },
      { text: '另辟蹊径', successRate: 0.7, successText: '你找到了新的道路', failText: '你迷失了方向', effects: { luck: 5, charisma: 5 }, failEffects: { luck: -3 }, flags: ['branch_identity_alien_hybrid_new'], failFlags: ['branch_identity_alien_hybrid_new_fail'] },
    ],
    flags: ['chain_alien_hybrid_adult_1'],
    requiredFlags: ['chain_alien_hybrid_growth_0'],
    identityExclusive: 'alien_hybrid',
    chainPriority: 2,
  },
  {
    id: 'sf_ie_alien_hybrid_07', category: 'identity_exclusive', minAge: 10, maxAge: 30, probability: 0.7,
    templates: [
      '作为外星混血，你与{legend}产生了宿命般的纠葛。',
      '你在{location}发现了关于外星混血起源的秘密。',
      '{npc}揭示了一个关于外星混血的惊天秘密。',
      '你的外星混血血脉在{location}发生了异变。',
    ],
    effects: { intelligence: 10 },
    flags: ['chain_alien_hybrid_special_0'],
    requiredFlags: ['chain_alien_hybrid_adult_0'],
    identityExclusive: 'alien_hybrid',
    chainPriority: 3,
  },
  {
    id: 'sf_ie_alien_hybrid_08', category: 'identity_exclusive', minAge: 30, maxAge: 60, probability: 0.7,
    templates: [
      '作为外星混血，你与{legend}产生了宿命般的纠葛。',
      '你在{location}发现了关于外星混血起源的秘密。',
      '{npc}揭示了一个关于外星混血的惊天秘密。',
      '你的外星混血血脉在{location}发生了异变。',
    ],
    effects: { strength: 8, luck: 5 },
    flags: ['chain_alien_hybrid_special_1'],
    requiredFlags: ['chain_alien_hybrid_adult_0'],
    identityExclusive: 'alien_hybrid',
    chainPriority: 3,
  },
  {
    id: 'sf_ie_ai_awakened_01', category: 'identity_exclusive', minAge: 3, maxAge: 8, probability: 0.85,
    templates: [
      '作为AI觉醒者，你从小就展现出与众不同的天赋。网络深渊的特质在你体内蠢蠢欲动。',
      '你在{location}经历了一件改变一生的事，那是AI觉醒者的命运转折点。',
      '{npc}看出了你是AI觉醒者的苗子，决定暗中帮助你。',
      '你体内的网络深渊之力在{location}第一次觉醒。',
    ],
    effects: { intelligence: 5 },
    flags: ['chain_ai_awakened_childhood_0'],
    identityExclusive: 'ai_awakened',
  },
  {
    id: 'sf_ie_ai_awakened_02', category: 'identity_exclusive', minAge: 7, maxAge: 12, probability: 0.85,
    templates: [
      '作为AI觉醒者，你从小就展现出与众不同的天赋。图灵突破的特质在你体内蠢蠢欲动。',
      '你在{location}经历了一件改变一生的事，那是AI觉醒者的命运转折点。',
      '{npc}看出了你是AI觉醒者的苗子，决定暗中帮助你。',
      '你体内的图灵突破之力在{location}第一次觉醒。',
    ],
    effects: { special: 5 },
    flags: ['chain_ai_awakened_childhood_1'],
    identityExclusive: 'ai_awakened',
  },
  {
    id: 'sf_ie_ai_awakened_03', category: 'identity_exclusive', minAge: 14, maxAge: 20, probability: 0.8,
    templates: [
      '作为AI觉醒者，你在{location}遇到了意识融合的试炼。',
      '你的AI觉醒者身份让你在{location}陷入了困境。',
      '{npc}因为你的AI觉醒者身份而对你另眼相看。',
      '你在{location}觉醒了AI觉醒者特有的能力。',
    ],
    effects: { charisma: 4, luck: 3 },
    flags: ['chain_ai_awakened_growth_0'],
    requiredFlags: ['chain_ai_awakened_childhood_0'],
    identityExclusive: 'ai_awakened',
    chainPriority: 1,
  },
  {
    id: 'sf_ie_ai_awakened_04', category: 'identity_exclusive', minAge: 19, maxAge: 25, probability: 0.8,
    templates: [
      '作为AI觉醒者，你在{location}遇到了意识融合的试炼。',
      '你的AI觉醒者身份让你在{location}陷入了困境。',
      '{npc}因为你的AI觉醒者身份而对你另眼相看。',
      '你在{location}觉醒了AI觉醒者特有的能力。',
    ],
    effects: { special: 6 },
    flags: ['chain_ai_awakened_growth_1'],
    requiredFlags: ['chain_ai_awakened_childhood_0'],
    identityExclusive: 'ai_awakened',
    chainPriority: 1,
  },
  {
    id: 'sf_ie_ai_awakened_05', category: 'identity_exclusive', minAge: 26, maxAge: 35, probability: 0.75,
    templates: [
      '作为AI觉醒者，你在{location}迎来了人生的重要转折点——硅基生命。',
      '你的AI觉醒者之路在{location}遭遇了最大的挑战。',
      '{legend}的传说与你的AI觉醒者身份产生了某种联系。',
      '你在{location}做出了一个关乎AI觉醒者命运的重要决定。',
    ],
    effects: { intelligence: 8 },
    flags: ['chain_ai_awakened_adult_0'],
    requiredFlags: ['chain_ai_awakened_growth_0'],
    identityExclusive: 'ai_awakened',
    chainPriority: 2,
  },
  {
    id: 'sf_ie_ai_awakened_06', category: 'identity_exclusive', minAge: 36, maxAge: 45, probability: 0.75,
    templates: [
      '作为AI觉醒者，你在{location}迎来了人生的重要转折点——硅基生命。',
      '你的AI觉醒者之路在{location}遭遇了最大的挑战。',
      '{legend}的传说与你的AI觉醒者身份产生了某种联系。',
      '你在{location}做出了一个关乎AI觉醒者命运的重要决定。',
    ],
    choices: [
      { text: '坚持AI觉醒者之道', successRate: 0.5, successText: '你成功了，硅基生命之力大增', failText: '你失败了，但收获经验', effects: { special: 10, strength: 5 }, failEffects: { intelligence: 5, health: -5 }, flags: ['branch_identity_ai_awakened_path'], failFlags: ['branch_identity_ai_awakened_path_fail'] },
      { text: '另辟蹊径', successRate: 0.7, successText: '你找到了新的道路', failText: '你迷失了方向', effects: { luck: 5, charisma: 5 }, failEffects: { luck: -3 }, flags: ['branch_identity_ai_awakened_new'], failFlags: ['branch_identity_ai_awakened_new_fail'] },
    ],
    flags: ['chain_ai_awakened_adult_1'],
    requiredFlags: ['chain_ai_awakened_growth_0'],
    identityExclusive: 'ai_awakened',
    chainPriority: 2,
  },
  {
    id: 'sf_ie_ai_awakened_07', category: 'identity_exclusive', minAge: 10, maxAge: 30, probability: 0.7,
    templates: [
      '作为AI觉醒者，你与{legend}产生了宿命般的纠葛。',
      '你在{location}发现了关于AI觉醒者起源的秘密。',
      '{npc}揭示了一个关于AI觉醒者的惊天秘密。',
      '你的AI觉醒者血脉在{location}发生了异变。',
    ],
    effects: { intelligence: 10 },
    flags: ['chain_ai_awakened_special_0'],
    requiredFlags: ['chain_ai_awakened_adult_0'],
    identityExclusive: 'ai_awakened',
    chainPriority: 3,
  },
  {
    id: 'sf_ie_ai_awakened_08', category: 'identity_exclusive', minAge: 30, maxAge: 60, probability: 0.7,
    templates: [
      '作为AI觉醒者，你与{legend}产生了宿命般的纠葛。',
      '你在{location}发现了关于AI觉醒者起源的秘密。',
      '{npc}揭示了一个关于AI觉醒者的惊天秘密。',
      '你的AI觉醒者血脉在{location}发生了异变。',
    ],
    effects: { special: 10, health: -5 },
    flags: ['chain_ai_awakened_special_1'],
    requiredFlags: ['chain_ai_awakened_adult_0'],
    identityExclusive: 'ai_awakened',
    chainPriority: 3,
  },
  {
    id: 'sf_ie_time_traveler_01', category: 'identity_exclusive', minAge: 3, maxAge: 8, probability: 0.85,
    templates: [
      '作为时空旅者，你从小就展现出与众不同的天赋。时间悖论的特质在你体内蠢蠢欲动。',
      '你在{location}经历了一件改变一生的事，那是时空旅者的命运转折点。',
      '{npc}看出了你是时空旅者的苗子，决定暗中帮助你。',
      '你体内的时间悖论之力在{location}第一次觉醒。',
    ],
    effects: { intelligence: 5 },
    flags: ['chain_time_traveler_childhood_0'],
    identityExclusive: 'time_traveler',
  },
  {
    id: 'sf_ie_time_traveler_02', category: 'identity_exclusive', minAge: 7, maxAge: 12, probability: 0.85,
    templates: [
      '作为时空旅者，你从小就展现出与众不同的天赋。因果重构的特质在你体内蠢蠢欲动。',
      '你在{location}经历了一件改变一生的事，那是时空旅者的命运转折点。',
      '{npc}看出了你是时空旅者的苗子，决定暗中帮助你。',
      '你体内的因果重构之力在{location}第一次觉醒。',
    ],
    effects: { special: 5 },
    flags: ['chain_time_traveler_childhood_1'],
    identityExclusive: 'time_traveler',
  },
  {
    id: 'sf_ie_time_traveler_03', category: 'identity_exclusive', minAge: 14, maxAge: 20, probability: 0.8,
    templates: [
      '作为时空旅者，你在{location}遇到了平行自我的试炼。',
      '你的时空旅者身份让你在{location}陷入了困境。',
      '{npc}因为你的时空旅者身份而对你另眼相看。',
      '你在{location}觉醒了时空旅者特有的能力。',
    ],
    effects: { intelligence: 6 },
    flags: ['chain_time_traveler_growth_0'],
    requiredFlags: ['chain_time_traveler_childhood_0'],
    identityExclusive: 'time_traveler',
    chainPriority: 1,
  },
  {
    id: 'sf_ie_time_traveler_04', category: 'identity_exclusive', minAge: 19, maxAge: 25, probability: 0.8,
    templates: [
      '作为时空旅者，你在{location}遇到了平行自我的试炼。',
      '你的时空旅者身份让你在{location}陷入了困境。',
      '{npc}因为你的时空旅者身份而对你另眼相看。',
      '你在{location}觉醒了时空旅者特有的能力。',
    ],
    effects: { charisma: 4, luck: 3 },
    flags: ['chain_time_traveler_growth_1'],
    requiredFlags: ['chain_time_traveler_childhood_0'],
    identityExclusive: 'time_traveler',
    chainPriority: 1,
  },
  {
    id: 'sf_ie_time_traveler_05', category: 'identity_exclusive', minAge: 26, maxAge: 35, probability: 0.75,
    templates: [
      '作为时空旅者，你在{location}迎来了人生的重要转折点——时间闭环。',
      '你的时空旅者之路在{location}遭遇了最大的挑战。',
      '{legend}的传说与你的时空旅者身份产生了某种联系。',
      '你在{location}做出了一个关乎时空旅者命运的重要决定。',
    ],
    effects: { special: 8 },
    flags: ['chain_time_traveler_adult_0'],
    requiredFlags: ['chain_time_traveler_growth_0'],
    identityExclusive: 'time_traveler',
    chainPriority: 2,
  },
  {
    id: 'sf_ie_time_traveler_06', category: 'identity_exclusive', minAge: 36, maxAge: 45, probability: 0.75,
    templates: [
      '作为时空旅者，你在{location}迎来了人生的重要转折点——时间闭环。',
      '你的时空旅者之路在{location}遭遇了最大的挑战。',
      '{legend}的传说与你的时空旅者身份产生了某种联系。',
      '你在{location}做出了一个关乎时空旅者命运的重要决定。',
    ],
    choices: [
      { text: '坚持时空旅者之道', successRate: 0.5, successText: '你成功了，时间闭环之力大增', failText: '你失败了，但收获经验', effects: { special: 10, strength: 5 }, failEffects: { intelligence: 5, health: -5 }, flags: ['branch_identity_time_traveler_path'], failFlags: ['branch_identity_time_traveler_path_fail'] },
      { text: '另辟蹊径', successRate: 0.7, successText: '你找到了新的道路', failText: '你迷失了方向', effects: { luck: 5, charisma: 5 }, failEffects: { luck: -3 }, flags: ['branch_identity_time_traveler_new'], failFlags: ['branch_identity_time_traveler_new_fail'] },
    ],
    flags: ['chain_time_traveler_adult_1'],
    requiredFlags: ['chain_time_traveler_growth_0'],
    identityExclusive: 'time_traveler',
    chainPriority: 2,
  },
  {
    id: 'sf_ie_time_traveler_07', category: 'identity_exclusive', minAge: 10, maxAge: 30, probability: 0.7,
    templates: [
      '作为时空旅者，你与{legend}产生了宿命般的纠葛。',
      '你在{location}发现了关于时空旅者起源的秘密。',
      '{npc}揭示了一个关于时空旅者的惊天秘密。',
      '你的时空旅者血脉在{location}发生了异变。',
    ],
    effects: { special: 10, health: -5 },
    flags: ['chain_time_traveler_special_0'],
    requiredFlags: ['chain_time_traveler_adult_0'],
    identityExclusive: 'time_traveler',
    chainPriority: 3,
  },
  {
    id: 'sf_ie_time_traveler_08', category: 'identity_exclusive', minAge: 30, maxAge: 60, probability: 0.7,
    templates: [
      '作为时空旅者，你与{legend}产生了宿命般的纠葛。',
      '你在{location}发现了关于时空旅者起源的秘密。',
      '{npc}揭示了一个关于时空旅者的惊天秘密。',
      '你的时空旅者血脉在{location}发生了异变。',
    ],
    effects: { intelligence: 10 },
    flags: ['chain_time_traveler_special_1'],
    requiredFlags: ['chain_time_traveler_adult_0'],
    identityExclusive: 'time_traveler',
    chainPriority: 3,
  },
  {
    id: 'sf_ie_gene_warrior_01', category: 'identity_exclusive', minAge: 3, maxAge: 8, probability: 0.85,
    templates: [
      '作为基因战士，你从小就展现出与众不同的天赋。基因解锁的特质在你体内蠢蠢欲动。',
      '你在{location}经历了一件改变一生的事，那是基因战士的命运转折点。',
      '{npc}看出了你是基因战士的苗子，决定暗中帮助你。',
      '你体内的基因解锁之力在{location}第一次觉醒。',
    ],
    effects: { intelligence: 5 },
    flags: ['chain_gene_warrior_childhood_0'],
    identityExclusive: 'gene_warrior',
  },
  {
    id: 'sf_ie_gene_warrior_02', category: 'identity_exclusive', minAge: 7, maxAge: 12, probability: 0.85,
    templates: [
      '作为基因战士，你从小就展现出与众不同的天赋。战斗本能的特质在你体内蠢蠢欲动。',
      '你在{location}经历了一件改变一生的事，那是基因战士的命运转折点。',
      '{npc}看出了你是基因战士的苗子，决定暗中帮助你。',
      '你体内的战斗本能之力在{location}第一次觉醒。',
    ],
    effects: { strength: 4, luck: 2 },
    flags: ['chain_gene_warrior_childhood_1'],
    identityExclusive: 'gene_warrior',
  },
  {
    id: 'sf_ie_gene_warrior_03', category: 'identity_exclusive', minAge: 14, maxAge: 20, probability: 0.8,
    templates: [
      '作为基因战士，你在{location}遇到了完美士兵的试炼。',
      '你的基因战士身份让你在{location}陷入了困境。',
      '{npc}因为你的基因战士身份而对你另眼相看。',
      '你在{location}觉醒了基因战士特有的能力。',
    ],
    effects: { intelligence: 6 },
    flags: ['chain_gene_warrior_growth_0'],
    requiredFlags: ['chain_gene_warrior_childhood_0'],
    identityExclusive: 'gene_warrior',
    chainPriority: 1,
  },
  {
    id: 'sf_ie_gene_warrior_04', category: 'identity_exclusive', minAge: 19, maxAge: 25, probability: 0.8,
    templates: [
      '作为基因战士，你在{location}遇到了完美士兵的试炼。',
      '你的基因战士身份让你在{location}陷入了困境。',
      '{npc}因为你的基因战士身份而对你另眼相看。',
      '你在{location}觉醒了基因战士特有的能力。',
    ],
    effects: { special: 6 },
    flags: ['chain_gene_warrior_growth_1'],
    requiredFlags: ['chain_gene_warrior_childhood_0'],
    identityExclusive: 'gene_warrior',
    chainPriority: 1,
  },
  {
    id: 'sf_ie_gene_warrior_05', category: 'identity_exclusive', minAge: 26, maxAge: 35, probability: 0.75,
    templates: [
      '作为基因战士，你在{location}迎来了人生的重要转折点——基因原体。',
      '你的基因战士之路在{location}遭遇了最大的挑战。',
      '{legend}的传说与你的基因战士身份产生了某种联系。',
      '你在{location}做出了一个关乎基因战士命运的重要决定。',
    ],
    effects: { intelligence: 8 },
    flags: ['chain_gene_warrior_adult_0'],
    requiredFlags: ['chain_gene_warrior_growth_0'],
    identityExclusive: 'gene_warrior',
    chainPriority: 2,
  },
  {
    id: 'sf_ie_gene_warrior_06', category: 'identity_exclusive', minAge: 36, maxAge: 45, probability: 0.75,
    templates: [
      '作为基因战士，你在{location}迎来了人生的重要转折点——基因原体。',
      '你的基因战士之路在{location}遭遇了最大的挑战。',
      '{legend}的传说与你的基因战士身份产生了某种联系。',
      '你在{location}做出了一个关乎基因战士命运的重要决定。',
    ],
    choices: [
      { text: '坚持基因战士之道', successRate: 0.5, successText: '你成功了，基因原体之力大增', failText: '你失败了，但收获经验', effects: { special: 10, strength: 5 }, failEffects: { intelligence: 5, health: -5 }, flags: ['branch_identity_gene_warrior_path'], failFlags: ['branch_identity_gene_warrior_path_fail'] },
      { text: '另辟蹊径', successRate: 0.7, successText: '你找到了新的道路', failText: '你迷失了方向', effects: { luck: 5, charisma: 5 }, failEffects: { luck: -3 }, flags: ['branch_identity_gene_warrior_new'], failFlags: ['branch_identity_gene_warrior_new_fail'] },
    ],
    flags: ['chain_gene_warrior_adult_1'],
    requiredFlags: ['chain_gene_warrior_growth_0'],
    identityExclusive: 'gene_warrior',
    chainPriority: 2,
  },
  {
    id: 'sf_ie_gene_warrior_07', category: 'identity_exclusive', minAge: 10, maxAge: 30, probability: 0.7,
    templates: [
      '作为基因战士，你与{legend}产生了宿命般的纠葛。',
      '你在{location}发现了关于基因战士起源的秘密。',
      '{npc}揭示了一个关于基因战士的惊天秘密。',
      '你的基因战士血脉在{location}发生了异变。',
    ],
    effects: { intelligence: 10 },
    flags: ['chain_gene_warrior_special_0'],
    requiredFlags: ['chain_gene_warrior_adult_0'],
    identityExclusive: 'gene_warrior',
    chainPriority: 3,
  },
  {
    id: 'sf_ie_gene_warrior_08', category: 'identity_exclusive', minAge: 30, maxAge: 60, probability: 0.7,
    templates: [
      '作为基因战士，你与{legend}产生了宿命般的纠葛。',
      '你在{location}发现了关于基因战士起源的秘密。',
      '{npc}揭示了一个关于基因战士的惊天秘密。',
      '你的基因战士血脉在{location}发生了异变。',
    ],
    effects: { special: 10, health: -5 },
    flags: ['chain_gene_warrior_special_1'],
    requiredFlags: ['chain_gene_warrior_adult_0'],
    identityExclusive: 'gene_warrior',
    chainPriority: 3,
  },
  {
    id: 'sf_ie_pirate_01', category: 'identity_exclusive', minAge: 3, maxAge: 8, probability: 0.85,
    templates: [
      '作为星际海盗，你从小就展现出与众不同的天赋。劫掠生涯的特质在你体内蠢蠢欲动。',
      '你在{location}经历了一件改变一生的事，那是星际海盗的命运转折点。',
      '{npc}看出了你是星际海盗的苗子，决定暗中帮助你。',
      '你体内的劫掠生涯之力在{location}第一次觉醒。',
    ],
    effects: { special: 5 },
    flags: ['chain_pirate_childhood_0'],
    identityExclusive: 'pirate',
  },
  {
    id: 'sf_ie_pirate_02', category: 'identity_exclusive', minAge: 7, maxAge: 12, probability: 0.85,
    templates: [
      '作为星际海盗，你从小就展现出与众不同的天赋。宝藏传说的特质在你体内蠢蠢欲动。',
      '你在{location}经历了一件改变一生的事，那是星际海盗的命运转折点。',
      '{npc}看出了你是星际海盗的苗子，决定暗中帮助你。',
      '你体内的宝藏传说之力在{location}第一次觉醒。',
    ],
    effects: { strength: 4, luck: 2 },
    flags: ['chain_pirate_childhood_1'],
    identityExclusive: 'pirate',
  },
  {
    id: 'sf_ie_pirate_03', category: 'identity_exclusive', minAge: 14, maxAge: 20, probability: 0.8,
    templates: [
      '作为星际海盗，你在{location}遇到了海盗王的试炼。',
      '你的星际海盗身份让你在{location}陷入了困境。',
      '{npc}因为你的星际海盗身份而对你另眼相看。',
      '你在{location}觉醒了星际海盗特有的能力。',
    ],
    effects: { special: 6 },
    flags: ['chain_pirate_growth_0'],
    requiredFlags: ['chain_pirate_childhood_0'],
    identityExclusive: 'pirate',
    chainPriority: 1,
  },
  {
    id: 'sf_ie_pirate_04', category: 'identity_exclusive', minAge: 19, maxAge: 25, probability: 0.8,
    templates: [
      '作为星际海盗，你在{location}遇到了海盗王的试炼。',
      '你的星际海盗身份让你在{location}陷入了困境。',
      '{npc}因为你的星际海盗身份而对你另眼相看。',
      '你在{location}觉醒了星际海盗特有的能力。',
    ],
    effects: { strength: 6 },
    flags: ['chain_pirate_growth_1'],
    requiredFlags: ['chain_pirate_childhood_0'],
    identityExclusive: 'pirate',
    chainPriority: 1,
  },
  {
    id: 'sf_ie_pirate_05', category: 'identity_exclusive', minAge: 26, maxAge: 35, probability: 0.75,
    templates: [
      '作为星际海盗，你在{location}迎来了人生的重要转折点——招安之路。',
      '你的星际海盗之路在{location}遭遇了最大的挑战。',
      '{legend}的传说与你的星际海盗身份产生了某种联系。',
      '你在{location}做出了一个关乎星际海盗命运的重要决定。',
    ],
    effects: { intelligence: 8 },
    flags: ['chain_pirate_adult_0'],
    requiredFlags: ['chain_pirate_growth_0'],
    identityExclusive: 'pirate',
    chainPriority: 2,
  },
  {
    id: 'sf_ie_pirate_06', category: 'identity_exclusive', minAge: 36, maxAge: 45, probability: 0.75,
    templates: [
      '作为星际海盗，你在{location}迎来了人生的重要转折点——招安之路。',
      '你的星际海盗之路在{location}遭遇了最大的挑战。',
      '{legend}的传说与你的星际海盗身份产生了某种联系。',
      '你在{location}做出了一个关乎星际海盗命运的重要决定。',
    ],
    choices: [
      { text: '坚持星际海盗之道', successRate: 0.5, successText: '你成功了，招安之路之力大增', failText: '你失败了，但收获经验', effects: { special: 10, strength: 5 }, failEffects: { intelligence: 5, health: -5 }, flags: ['branch_identity_pirate_path'], failFlags: ['branch_identity_pirate_path_fail'] },
      { text: '另辟蹊径', successRate: 0.7, successText: '你找到了新的道路', failText: '你迷失了方向', effects: { luck: 5, charisma: 5 }, failEffects: { luck: -3 }, flags: ['branch_identity_pirate_new'], failFlags: ['branch_identity_pirate_new_fail'] },
    ],
    flags: ['chain_pirate_adult_1'],
    requiredFlags: ['chain_pirate_growth_0'],
    identityExclusive: 'pirate',
    chainPriority: 2,
  },
  {
    id: 'sf_ie_pirate_07', category: 'identity_exclusive', minAge: 10, maxAge: 30, probability: 0.7,
    templates: [
      '作为星际海盗，你与{legend}产生了宿命般的纠葛。',
      '你在{location}发现了关于星际海盗起源的秘密。',
      '{npc}揭示了一个关于星际海盗的惊天秘密。',
      '你的星际海盗血脉在{location}发生了异变。',
    ],
    effects: { special: 10, health: -5 },
    flags: ['chain_pirate_special_0'],
    requiredFlags: ['chain_pirate_adult_0'],
    identityExclusive: 'pirate',
    chainPriority: 3,
  },
  {
    id: 'sf_ie_pirate_08', category: 'identity_exclusive', minAge: 30, maxAge: 60, probability: 0.7,
    templates: [
      '作为星际海盗，你与{legend}产生了宿命般的纠葛。',
      '你在{location}发现了关于星际海盗起源的秘密。',
      '{npc}揭示了一个关于星际海盗的惊天秘密。',
      '你的星际海盗血脉在{location}发生了异变。',
    ],
    effects: { strength: 8, luck: 5 },
    flags: ['chain_pirate_special_1'],
    requiredFlags: ['chain_pirate_adult_0'],
    identityExclusive: 'pirate',
    chainPriority: 3,
  },
  {
    id: 'sf_ie_archaeologist_01', category: 'identity_exclusive', minAge: 3, maxAge: 8, probability: 0.85,
    templates: [
      '作为深空考古学家，你从小就展现出与众不同的天赋。古代遗迹的特质在你体内蠢蠢欲动。',
      '你在{location}经历了一件改变一生的事，那是深空考古学家的命运转折点。',
      '{npc}看出了你是深空考古学家的苗子，决定暗中帮助你。',
      '你体内的古代遗迹之力在{location}第一次觉醒。',
    ],
    effects: { strength: 4, luck: 2 },
    flags: ['chain_archaeologist_childhood_0'],
    identityExclusive: 'archaeologist',
  },
  {
    id: 'sf_ie_archaeologist_02', category: 'identity_exclusive', minAge: 7, maxAge: 12, probability: 0.85,
    templates: [
      '作为深空考古学家，你从小就展现出与众不同的天赋。失落科技的特质在你体内蠢蠢欲动。',
      '你在{location}经历了一件改变一生的事，那是深空考古学家的命运转折点。',
      '{npc}看出了你是深空考古学家的苗子，决定暗中帮助你。',
      '你体内的失落科技之力在{location}第一次觉醒。',
    ],
    effects: { special: 5 },
    flags: ['chain_archaeologist_childhood_1'],
    identityExclusive: 'archaeologist',
  },
  {
    id: 'sf_ie_archaeologist_03', category: 'identity_exclusive', minAge: 14, maxAge: 20, probability: 0.8,
    templates: [
      '作为深空考古学家，你在{location}遇到了文明轮回的试炼。',
      '你的深空考古学家身份让你在{location}陷入了困境。',
      '{npc}因为你的深空考古学家身份而对你另眼相看。',
      '你在{location}觉醒了深空考古学家特有的能力。',
    ],
    effects: { intelligence: 6 },
    flags: ['chain_archaeologist_growth_0'],
    requiredFlags: ['chain_archaeologist_childhood_0'],
    identityExclusive: 'archaeologist',
    chainPriority: 1,
  },
  {
    id: 'sf_ie_archaeologist_04', category: 'identity_exclusive', minAge: 19, maxAge: 25, probability: 0.8,
    templates: [
      '作为深空考古学家，你在{location}遇到了文明轮回的试炼。',
      '你的深空考古学家身份让你在{location}陷入了困境。',
      '{npc}因为你的深空考古学家身份而对你另眼相看。',
      '你在{location}觉醒了深空考古学家特有的能力。',
    ],
    effects: { strength: 6 },
    flags: ['chain_archaeologist_growth_1'],
    requiredFlags: ['chain_archaeologist_childhood_0'],
    identityExclusive: 'archaeologist',
    chainPriority: 1,
  },
  {
    id: 'sf_ie_archaeologist_05', category: 'identity_exclusive', minAge: 26, maxAge: 35, probability: 0.75,
    templates: [
      '作为深空考古学家，你在{location}迎来了人生的重要转折点——考古发现。',
      '你的深空考古学家之路在{location}遭遇了最大的挑战。',
      '{legend}的传说与你的深空考古学家身份产生了某种联系。',
      '你在{location}做出了一个关乎深空考古学家命运的重要决定。',
    ],
    effects: { intelligence: 8 },
    flags: ['chain_archaeologist_adult_0'],
    requiredFlags: ['chain_archaeologist_growth_0'],
    identityExclusive: 'archaeologist',
    chainPriority: 2,
  },
  {
    id: 'sf_ie_archaeologist_06', category: 'identity_exclusive', minAge: 36, maxAge: 45, probability: 0.75,
    templates: [
      '作为深空考古学家，你在{location}迎来了人生的重要转折点——考古发现。',
      '你的深空考古学家之路在{location}遭遇了最大的挑战。',
      '{legend}的传说与你的深空考古学家身份产生了某种联系。',
      '你在{location}做出了一个关乎深空考古学家命运的重要决定。',
    ],
    choices: [
      { text: '坚持深空考古学家之道', successRate: 0.5, successText: '你成功了，考古发现之力大增', failText: '你失败了，但收获经验', effects: { special: 10, strength: 5 }, failEffects: { intelligence: 5, health: -5 }, flags: ['branch_identity_archaeologist_path'], failFlags: ['branch_identity_archaeologist_path_fail'] },
      { text: '另辟蹊径', successRate: 0.7, successText: '你找到了新的道路', failText: '你迷失了方向', effects: { luck: 5, charisma: 5 }, failEffects: { luck: -3 }, flags: ['branch_identity_archaeologist_new'], failFlags: ['branch_identity_archaeologist_new_fail'] },
    ],
    flags: ['chain_archaeologist_adult_1'],
    requiredFlags: ['chain_archaeologist_growth_0'],
    identityExclusive: 'archaeologist',
    chainPriority: 2,
  },
  {
    id: 'sf_ie_archaeologist_07', category: 'identity_exclusive', minAge: 10, maxAge: 30, probability: 0.7,
    templates: [
      '作为深空考古学家，你与{legend}产生了宿命般的纠葛。',
      '你在{location}发现了关于深空考古学家起源的秘密。',
      '{npc}揭示了一个关于深空考古学家的惊天秘密。',
      '你的深空考古学家血脉在{location}发生了异变。',
    ],
    effects: { special: 10, health: -5 },
    flags: ['chain_archaeologist_special_0'],
    requiredFlags: ['chain_archaeologist_adult_0'],
    identityExclusive: 'archaeologist',
    chainPriority: 3,
  },
  {
    id: 'sf_ie_archaeologist_08', category: 'identity_exclusive', minAge: 30, maxAge: 60, probability: 0.7,
    templates: [
      '作为深空考古学家，你与{legend}产生了宿命般的纠葛。',
      '你在{location}发现了关于深空考古学家起源的秘密。',
      '{npc}揭示了一个关于深空考古学家的惊天秘密。',
      '你的深空考古学家血脉在{location}发生了异变。',
    ],
    effects: { strength: 8, luck: 5 },
    flags: ['chain_archaeologist_special_1'],
    requiredFlags: ['chain_archaeologist_adult_0'],
    identityExclusive: 'archaeologist',
    chainPriority: 3,
  },
  {
    id: 'sf_ie_hacker_01', category: 'identity_exclusive', minAge: 3, maxAge: 8, probability: 0.85,
    templates: [
      '作为网络黑客，你从小就展现出与众不同的天赋。网络入侵的特质在你体内蠢蠢欲动。',
      '你在{location}经历了一件改变一生的事，那是网络黑客的命运转折点。',
      '{npc}看出了你是网络黑客的苗子，决定暗中帮助你。',
      '你体内的网络入侵之力在{location}第一次觉醒。',
    ],
    effects: { strength: 4, luck: 2 },
    flags: ['chain_hacker_childhood_0'],
    identityExclusive: 'hacker',
  },
  {
    id: 'sf_ie_hacker_02', category: 'identity_exclusive', minAge: 7, maxAge: 12, probability: 0.85,
    templates: [
      '作为网络黑客，你从小就展现出与众不同的天赋。数据意识的特质在你体内蠢蠢欲动。',
      '你在{location}经历了一件改变一生的事，那是网络黑客的命运转折点。',
      '{npc}看出了你是网络黑客的苗子，决定暗中帮助你。',
      '你体内的数据意识之力在{location}第一次觉醒。',
    ],
    effects: { special: 5 },
    flags: ['chain_hacker_childhood_1'],
    identityExclusive: 'hacker',
  },
  {
    id: 'sf_ie_hacker_03', category: 'identity_exclusive', minAge: 14, maxAge: 20, probability: 0.8,
    templates: [
      '作为网络黑客，你在{location}遇到了数字幽灵的试炼。',
      '你的网络黑客身份让你在{location}陷入了困境。',
      '{npc}因为你的网络黑客身份而对你另眼相看。',
      '你在{location}觉醒了网络黑客特有的能力。',
    ],
    effects: { strength: 6 },
    flags: ['chain_hacker_growth_0'],
    requiredFlags: ['chain_hacker_childhood_0'],
    identityExclusive: 'hacker',
    chainPriority: 1,
  },
  {
    id: 'sf_ie_hacker_04', category: 'identity_exclusive', minAge: 19, maxAge: 25, probability: 0.8,
    templates: [
      '作为网络黑客，你在{location}遇到了数字幽灵的试炼。',
      '你的网络黑客身份让你在{location}陷入了困境。',
      '{npc}因为你的网络黑客身份而对你另眼相看。',
      '你在{location}觉醒了网络黑客特有的能力。',
    ],
    effects: { intelligence: 6 },
    flags: ['chain_hacker_growth_1'],
    requiredFlags: ['chain_hacker_childhood_0'],
    identityExclusive: 'hacker',
    chainPriority: 1,
  },
  {
    id: 'sf_ie_hacker_05', category: 'identity_exclusive', minAge: 26, maxAge: 35, probability: 0.75,
    templates: [
      '作为网络黑客，你在{location}迎来了人生的重要转折点——系统崩溃。',
      '你的网络黑客之路在{location}遭遇了最大的挑战。',
      '{legend}的传说与你的网络黑客身份产生了某种联系。',
      '你在{location}做出了一个关乎网络黑客命运的重要决定。',
    ],
    effects: { intelligence: 8 },
    flags: ['chain_hacker_adult_0'],
    requiredFlags: ['chain_hacker_growth_0'],
    identityExclusive: 'hacker',
    chainPriority: 2,
  },
  {
    id: 'sf_ie_hacker_06', category: 'identity_exclusive', minAge: 36, maxAge: 45, probability: 0.75,
    templates: [
      '作为网络黑客，你在{location}迎来了人生的重要转折点——系统崩溃。',
      '你的网络黑客之路在{location}遭遇了最大的挑战。',
      '{legend}的传说与你的网络黑客身份产生了某种联系。',
      '你在{location}做出了一个关乎网络黑客命运的重要决定。',
    ],
    choices: [
      { text: '坚持网络黑客之道', successRate: 0.5, successText: '你成功了，系统崩溃之力大增', failText: '你失败了，但收获经验', effects: { special: 10, strength: 5 }, failEffects: { intelligence: 5, health: -5 }, flags: ['branch_identity_hacker_path'], failFlags: ['branch_identity_hacker_path_fail'] },
      { text: '另辟蹊径', successRate: 0.7, successText: '你找到了新的道路', failText: '你迷失了方向', effects: { luck: 5, charisma: 5 }, failEffects: { luck: -3 }, flags: ['branch_identity_hacker_new'], failFlags: ['branch_identity_hacker_new_fail'] },
    ],
    flags: ['chain_hacker_adult_1'],
    requiredFlags: ['chain_hacker_growth_0'],
    identityExclusive: 'hacker',
    chainPriority: 2,
  },
  {
    id: 'sf_ie_hacker_07', category: 'identity_exclusive', minAge: 10, maxAge: 30, probability: 0.7,
    templates: [
      '作为网络黑客，你与{legend}产生了宿命般的纠葛。',
      '你在{location}发现了关于网络黑客起源的秘密。',
      '{npc}揭示了一个关于网络黑客的惊天秘密。',
      '你的网络黑客血脉在{location}发生了异变。',
    ],
    effects: { special: 10, health: -5 },
    flags: ['chain_hacker_special_0'],
    requiredFlags: ['chain_hacker_adult_0'],
    identityExclusive: 'hacker',
    chainPriority: 3,
  },
  {
    id: 'sf_ie_hacker_08', category: 'identity_exclusive', minAge: 30, maxAge: 60, probability: 0.7,
    templates: [
      '作为网络黑客，你与{legend}产生了宿命般的纠葛。',
      '你在{location}发现了关于网络黑客起源的秘密。',
      '{npc}揭示了一个关于网络黑客的惊天秘密。',
      '你的网络黑客血脉在{location}发生了异变。',
    ],
    effects: { intelligence: 10 },
    flags: ['chain_hacker_special_1'],
    requiredFlags: ['chain_hacker_adult_0'],
    identityExclusive: 'hacker',
    chainPriority: 3,
  },
  {
    id: 'sf_te_01', category: 'trash_exclusive', minAge: 0, maxAge: 6, probability: 0.9,
    templates: [
      '你被检测出基因缺陷，全村人都对你投来怜悯的目光。{npc}摇头叹息："这孩子废了。"',
      '其他孩子在{location}修炼时，你只能在一旁看着，因为你的身体根本无法吸收灵气。',
      '你的父母因为你的基因缺陷体质而愁眉不展，{npc}劝他们放弃对你的期望。',
    ],
    effects: { special: -3, strength: -2, intelligence: 2 },
    flags: ['trash_childhood_start'],
    talentExclusive: 'trash',
  },
  {
    id: 'sf_te_02', category: 'trash_exclusive', minAge: 4, maxAge: 10, probability: 0.85,
    templates: [
      '你在{location}被同龄人欺负，他们嘲笑你是基因缺陷的废物。你握紧拳头，暗暗发誓要变强。',
      '{npc}偷偷塞给你一本基础功法，说是"死马当活马医"。你如获至宝，日夜研读。',
      '你在{location}发现了一本破旧的书，虽然字迹模糊但你还是坚持抄了下来。',
    ],
    effects: { intelligence: 3, strength: 2, luck: 1 },
    flags: ['trash_childhood_1'],
    requiredFlags: ['trash_childhood_start'],
    talentExclusive: 'trash',
  },
  {
    id: 'sf_te_03', category: 'trash_exclusive', minAge: 12, maxAge: 18, probability: 0.8,
    templates: [
      '你按照那本破书上的方法在{location}修炼，进展缓慢但从未放弃。{npc}惊讶地发现你的气息变强了。',
      '别的天才一天能完成的修炼，你需要一个月。但你用十倍的时间来弥补，在{location}日复一日。',
      '你在{location}找到了一种适合基因缺陷体质的特殊修炼方式，虽然痛苦但有效。',
    ],
    effects: { strength: 4, intelligence: 3, special: 2 },
    flags: ['trash_growth_0'],
    requiredFlags: ['trash_childhood_1'],
    talentExclusive: 'trash',
  },
  {
    id: 'sf_te_04', category: 'trash_exclusive', minAge: 15, maxAge: 22, probability: 0.75,
    templates: [
      '你在{location}救了一个受伤的{npc}，他感激之下传授了你一套独门的炼体之术。',
      '{npc}被你的毅力打动，决定收你为记名弟子。你终于有了自己的师父！',
      '你在{location}苦修多年，虽然境界不高，但肉身强度已经远超同阶。',
    ],
    effects: { strength: 6, health: 5, charisma: 2 },
    flags: ['trash_growth_1'],
    requiredFlags: ['trash_growth_0'],
    talentExclusive: 'trash',
  },
  {
    id: 'sf_te_05', category: 'trash_exclusive', minAge: 18, maxAge: 25, probability: 0.7,
    templates: [
      '你在{location}遇到了一个神秘的{npc}，他说你的基因缺陷体质其实另有玄机。',
      '经过多年的积累，你在{location}突然有了顿悟——原来修炼不止一条路！',
      '{legend}的残魂在{location}与你相遇，说你是万年一遇的"大器晚成"之命。',
    ],
    effects: { intelligence: 5, luck: 5, special: 3 },
    flags: ['trash_growth_2'],
    requiredFlags: ['trash_growth_1'],
    talentExclusive: 'trash',
  },
  {
    id: 'sf_te_06', category: 'trash_exclusive', minAge: 26, maxAge: 35, probability: 0.75,
    templates: [
      '你在{location}参加了一场比试，虽然境界最低，但凭借坚韧的意志打败了数名对手，引起了轰动。',
      '你的修炼方式自成一派，{npc}说你是"以凡人之躯比肩神明"。',
      '你在{location}展示了你独创的功法，所有人都震惊了——原来基因缺陷也能这么强！',
    ],
    effects: { strength: 6, charisma: 5, special: 4 },
    flags: ['trash_adult_0'],
    requiredFlags: ['trash_growth_2'],
    talentExclusive: 'trash',
  },
  {
    id: 'sf_te_07', category: 'trash_exclusive', minAge: 30, maxAge: 40, probability: 0.7,
    templates: [
      '那些曾经嘲笑你的人在{location}看到你，全都目瞪口呆。你已经超越了他们中的大多数。',
      '{npc}邀请你加入一个重要组织，你的基因缺陷之名开始传开。',
      '你在{location}建立了自己的修炼体系，吸引了不少同样有天赋缺陷的人前来学习。',
    ],
    effects: { charisma: 6, intelligence: 4, luck: 3 },
    flags: ['trash_adult_1'],
    requiredFlags: ['trash_adult_0'],
    talentExclusive: 'trash',
  },
  {
    id: 'sf_te_08', category: 'trash_exclusive', minAge: 35, maxAge: 45, probability: 0.65,
    templates: [
      '你在{location}面对昔日最大的仇人，对方依然嘲笑你的基因缺陷体质。',
      '{legend}的传承之地开启，你说服众人让你这个"废物"也进去试试。',
      '你在{location}做出了一个大胆的决定——要用自己的方式证明基因缺陷不是终点。',
    ],
    effects: { strength: 5, luck: 5, special: 3 },
    flags: ['trash_adult_2'],
    requiredFlags: ['trash_adult_1'],
    talentExclusive: 'trash',
  },
  {
    id: 'sf_te_09', category: 'trash_exclusive', minAge: 28, maxAge: 42, probability: 0.6,
    templates: [
      '宗门大比的日子到了，你在{location}面对所有人的质疑，毅然报名参加。',
      '这是你证明自己的最好机会，{npc}暗中为你加油。',
      '{legend}的预言提到了一个"废物"将改变世界，所有人都看着你。',
    ],
    effects: { strength: 3 },
    choices: [
      { text: '全力一战', successRate: 0.4, successText: '你以弱胜强，创造了不可思议的奇迹！全场沸腾！', failText: '你拼尽全力但还是输了，虽然败了但赢得了尊重', effects: { strength: 10, charisma: 8, special: 5 }, failEffects: { strength: 5, charisma: 3, health: -15 }, flags: ['branch_trash_fight'], failFlags: ['branch_trash_fight_fail'] },
      { text: '智取巧胜', successRate: 0.6, successText: '你利用对手的轻敌，以巧取胜！', failText: '你的计策被识破，狼狈落败', effects: { intelligence: 8, luck: 5 }, failEffects: { charisma: -3, health: -10 }, flags: ['branch_trash_trick'], failFlags: ['branch_trash_trick_fail'] },
    ],
    flags: ['trash_climax_0'],
    requiredFlags: ['trash_adult_1'],
    talentExclusive: 'trash',
    chainPriority: 2,
  },
  {
    id: 'sf_te_10', category: 'trash_exclusive', minAge: 35, maxAge: 50, probability: 0.55,
    templates: [
      '你在{location}获得了{legend}的认可，TA说你的道路虽然艰难，但终点比任何人都高。',
      '一位隐世高人在{location}看中了你的毅力，决定传授你绝世功法。',
      '你发现了改变基因缺陷体质的方法，但需要冒极大的风险。',
    ],
    effects: { special: 5 },
    choices: [
      { text: '冒险改变体质', successRate: 0.35, successText: '你成功了！你的体质发生了翻天覆地的变化，从此一飞冲天！', failText: '改造失败，你受了重伤，但意志更加坚定', effects: { special: 15, strength: 5, health: -10 }, failEffects: { health: -25, strength: 3 }, flags: ['branch_trash_transform'], failFlags: ['branch_trash_transform_fail'] },
      { text: '坚持原有道路', successRate: 0.75, successText: '你的坚持得到了回报，你的功法大成，自成一派！', failText: '进展依然缓慢，但你没有放弃', effects: { intelligence: 8, strength: 5 }, failEffects: { intelligence: 3 }, flags: ['branch_trash_persist'], failFlags: ['branch_trash_persist_fail'] },
    ],
    flags: ['trash_climax_1'],
    requiredFlags: ['trash_climax_0'],
    talentExclusive: 'trash',
    chainPriority: 2,
  },
  {
    id: 'sf_te_11', category: 'trash_exclusive', minAge: 40, maxAge: 55, probability: 0.5,
    templates: [
      '你在{location}一战成名，所有人都知道那个基因缺陷的废物逆袭成了强者。',
      '你的故事传遍了大陆，无数基因缺陷的人把你当作偶像。',
      '{npc}跪在你面前，为当年嘲笑你而道歉。你扶起他，说："我走的路，比你们都长。"',
    ],
    effects: { charisma: 10, luck: 5, special: 5 },
    flags: ['trash_climax_2'],
    requiredFlags: ['trash_climax_1'],
    talentExclusive: 'trash',
    chainPriority: 3,
  },
  {
    id: 'sf_te_12', category: 'trash_exclusive', minAge: 45, maxAge: 60, probability: 0.45,
    templates: [
      '你在{location}达到了前所未有的高度，证明了基因缺陷也能登临绝巅。',
      '你成为了{legend}级别的存在，后人将你的故事传颂千古。',
      '你回头看向起点，那个在{location}被嘲笑的孩子，如今已是传奇。',
    ],
    effects: { strength: 8, intelligence: 8, charisma: 8, special: 8 },
    flags: ['trash_legend'],
    requiredFlags: ['trash_climax_2'],
    talentExclusive: 'trash',
    chainPriority: 3,
  },
  {
    id: 'sf_te_13', category: 'trash_exclusive', minAge: 55, maxAge: 80, probability: 0.55,
    templates: [
      '你在{location}收徒传道，专门招收那些被视为废材的孩子。你说："天赋决定起点，但毅力决定终点。"',
      '你的弟子中出了不少人才，{npc}感叹你创造了一个奇迹。',
      '你在{location}写下了自己的修炼心得，希望能帮助更多基因缺陷的人。',
    ],
    effects: { charisma: 6, intelligence: 5 },
    flags: ['trash_elder_0'],
    requiredFlags: ['trash_legend'],
    talentExclusive: 'trash',
  },
  {
    id: 'sf_te_14', category: 'trash_exclusive', minAge: 60, maxAge: 90, probability: 0.5,
    templates: [
      '你的大限将至，但你毫无遗憾。{npc}问你后不后悔走这条艰难的路。',
      '你微笑着说："如果重来一次，我还是会选择做那个基因缺陷的废物。"',
      '你在{location}度过了平静的最后岁月，每天都有人来听你讲当年的故事。',
    ],
    effects: { charisma: 5, health: -5 },
    flags: ['trash_elder_1'],
    requiredFlags: ['trash_elder_0'],
    talentExclusive: 'trash',
  },
  {
    id: 'sf_te_15', category: 'trash_exclusive', minAge: 70, maxAge: 100, probability: 0.45,
    templates: [
      '你离世的那天，{location}下起了金色的雨。无数人自发前来为你送行。',
      '{legend}亲自前来接引你的灵魂，说你是万古以来第一个以基因缺陷之躯证道的人。',
      '你的名字被刻在了{location}的最高处，激励着后世所有被视为废材的人。',
    ],
    effects: { charisma: 10, luck: 10 },
    flags: ['trash_ending'],
    requiredFlags: ['trash_elder_1'],
    talentExclusive: 'trash',
  },
];
