import type { EventTemplate } from './types';

// 古代武侠 — 164 event templates
// Generated: 2026-04-27
// Rarity tiers: legendary(≤0.10) / epic(0.10-0.25) / rare(0.25-0.50) / common(0.50-0.85) / trash-exclusive
// Each template has 3-5 text variations, total ~656 actual events

export const wuxiaTemplates: EventTemplate[] = [
  {
    id: 'wx_ch_01', category: 'childhood', minAge: 0, maxAge: 3, probability: 0.042,
    templates: [
      '你出生那天，{location}突然霞光万丈，紫气东来三千里。{npc}跪地叩拜，说你是千年一遇的武道通神。',
      '你降生的瞬间，{location}百花齐放，{legend}的虚影在天际显现，整个大陆为之震动。',
      '你的第一声啼哭引发了{location}的灵气暴动，{npc}颤抖着说："武道通神降世了！"',
    ],
    effects: { luck: 10, special: 8, charisma: 5 },
  },
  {
    id: 'wx_ch_02', category: 'childhood', minAge: 2, maxAge: 7, probability: 0.115,
    templates: [
      '你在{location}玩耍时，体内突然涌出一股热流。{npc}惊讶地发现你竟是武学奇才之资！',
      '三岁时，你在{location}无意间触发了古老的检测阵法，光芒比所有人都亮。',
      '{npc}为你进行资质测试，{legend}的印记在你身上一闪而逝——你是被选中的人。',
    ],
    effects: { special: 6, intelligence: 4 },
  },
  {
    id: 'wx_ch_03', category: 'childhood', minAge: 4, maxAge: 9, probability: 0.285,
    templates: [
      '你在{location}救了一只受伤的小动物，它其实是{legend}的化身，临走前留下了一枚灵珠。',
      '{npc}在你满月时送了一块玉佩，后来你发现那是一件上古法器的碎片。',
      '你从小就能看见别人看不见的{legend}幻影，{npc}说这是灵根初现的征兆。',
      '你在{location}挖到了一坛古酒，喝了一口后浑身舒畅，经脉隐隐发热。',
    ],
    effects: { special: 4 },
  },
  {
    id: 'wx_ch_04', category: 'childhood', minAge: 0, maxAge: 6, probability: 0.512,
    templates: [
      '你生在普通人家，每天在{location}玩耍，日子平淡但快乐。',
      '{npc}教你读书识字，你学得有模有样。',
      '你在{location}认识了几个玩伴，度过了无忧无虑的童年。',
      '家里虽然不富裕，但{npc}总是把最好的留给你。',
    ],
    effects: { charisma: 2, luck: 1 },
  },
  {
    id: 'wx_ch_05', category: 'childhood', minAge: 3, maxAge: 10, probability: 0.69,
    templates: [
      '你在{location}帮{npc}干活，学会了很多生活技能。',
      '你的身体比同龄人强壮，{npc}说你是干农活的好料子。',
      '你喜欢在{location}发呆，常常一坐就是一整天。',
      '{npc}给你讲了一个关于{legend}的故事，你听得入了迷。',
    ],
    effects: { strength: 2, intelligence: 1 },
  },
  {
    id: 'wx_gr_01', category: 'growth', minAge: 15, maxAge: 20, probability: 0.042,
    templates: [
      '你在{location}闭关三日，出关时眼中精光四射——你竟在战斗中顿悟了{legend}的传承！',
      '一场雷雨夜，你在{location}被天雷击中非但没死，反而打通了全身经脉！',
      '{legend}的残魂在{location}与你相遇，将毕生感悟传授于你。',
    ],
    effects: { intelligence: 10, special: 8, strength: 5 },
  },
  {
    id: 'wx_gr_02', category: 'growth', minAge: 14, maxAge: 22, probability: 0.108,
    templates: [
      '你在{location}苦修三年，终于突破了困扰多年的瓶颈，实力大增！',
      '{npc}带你外出历练，你在{location}击败了一个强敌，获得了珍贵的战利品。',
      '你发现了{legend}留下的试炼场，通过考验后获得了意想不到的收获。',
    ],
    effects: { strength: 6, special: 5 },
  },
  {
    id: 'wx_gr_03', category: 'growth', minAge: 13, maxAge: 24, probability: 0.331,
    templates: [
      '你在{location}遇到了一生的宿敌，你们不打不相识，反而成为了朋友。',
      '{npc}传授你一项绝技，你花了整整一年才学会，但威力惊人。',
      '你在{location}救了一个被追杀的人，他为了报答你，送了一件宝物。',
      '你和同辈在{location}比试，虽然输了但收获巨大。',
    ],
    effects: { strength: 4, luck: 2 },
  },
  {
    id: 'wx_gr_04', category: 'growth', minAge: 13, maxAge: 20, probability: 0.562,
    templates: [
      '你每天在{location}勤奋练习，虽然进步缓慢但根基扎实。',
      '{npc}督促你修炼，你不敢懈怠。',
      '你在{location}读了很多书，眼界开阔了不少。',
      '平平淡淡的一年，你在{location}默默积累着。',
    ],
    effects: { intelligence: 2, strength: 2 },
  },
  {
    id: 'wx_gr_05', category: 'growth', minAge: 16, maxAge: 25, probability: 0.675,
    templates: [
      '你在{location}结交了一些朋友，互相切磋进步。',
      '{npc}给你讲了很多前辈的故事，你深受启发。',
      '你在{location}处理了一些杂务，锻炼了自己的能力。',
      '这一年没什么特别的事发生，但你感觉自己在慢慢变强。',
    ],
    effects: { charisma: 2, luck: 2 },
  },
  {
    id: 'wx_ad_01', category: 'adult', minAge: 28, maxAge: 40, probability: 0.116,
    templates: [
      '你在{location}开宗立派，广收门徒，一时间名声大噪。',
      '你参与了{legend}相关的大规模事件，在关键时刻力挽狂澜。',
      '你在{location}建立了属于自己的势力，各方强者纷纷来投。',
    ],
    effects: { charisma: 8, strength: 5, special: 5 },
  },
  {
    id: 'wx_ad_02', category: 'adult', minAge: 26, maxAge: 45, probability: 0.292,
    templates: [
      '你在{location}收下了第一个弟子，将自己的所学倾囊相授。',
      '你和宿敌在{location}进行了最终决战，胜负难分。',
      '你成功炼制/制造了传说中的物品，引起了不小的轰动。',
    ],
    effects: { intelligence: 5, special: 4 },
  },
  {
    id: 'wx_ad_03', category: 'adult', minAge: 26, maxAge: 50, probability: 0.594,
    templates: [
      '你在{location}处理日常事务，势力稳步发展。',
      '{npc}来找你帮忙，你出手解决了他的难题。',
      '你在{location}度过了平静的一年，修为稳步提升。',
      '平平淡淡的一年，你在{location}默默修炼。',
    ],
    effects: { strength: 2, intelligence: 2, special: 2 },
  },
  {
    id: 'wx_el_01', category: 'elder', minAge: 55, maxAge: 80, probability: 0.256,
    templates: [
      '你的修为已臻化境，成为了{location}的传说级人物。',
      '你开始着手准备最终的突破，{npc}专程前来为你护法。',
      '你将毕生所学整理成册，存放在{location}，等待有缘人。',
    ],
    effects: { intelligence: 8, charisma: 5 },
  },
  {
    id: 'wx_el_02', category: 'elder', minAge: 51, maxAge: 100, probability: 0.558,
    templates: [
      '你在{location}颐养天年，每日种花养鱼，不问世事。',
      '你的身体开始衰退，但精神愈发强大。',
      '你决定将力量传承给下一代，{npc}成为了你的传人。',
    ],
    effects: { health: -3, intelligence: 3 },
  },
  {
    id: 'wx_cb_01', category: 'combat', minAge: 20, maxAge: 40, probability: 0.038,
    templates: [
      '你在{location}以一己之力对抗十位同阶强者，最终大获全胜，一战成名！',
      '{legend}的敌人找上了你，你在{location}展开惊天大战，竟越级将其斩杀！',
      '你为了保护{location}的居民，独自对抗入侵的{legend}军团，创造了不可能的奇迹。',
    ],
    effects: { strength: 12, charisma: 8, health: -10 },
  },
  {
    id: 'wx_cb_02', category: 'combat', minAge: 18, maxAge: 45, probability: 0.144,
    templates: [
      '你参与了一场改变{location}格局的大规模战争，立下赫赫战功。',
      '{npc}挑战你的权威，你们在{location}大战三百回合，最终你险胜一招。',
      '你在{location}发现了{legend}留下的试炼场，通过了生死考验。',
    ],
    effects: { strength: 8, charisma: 4, health: -5 },
  },
  {
    id: 'wx_cb_03', category: 'combat', minAge: 15, maxAge: 35, probability: 0.279,
    templates: [
      '你在{location}遭遇强敌，展开了一场生死搏斗，最终险胜。',
      '你和{npc}在{location}切磋，双方都获益匪浅。',
      '你为了保护同伴，在{location}与敌人激战，受了轻伤。',
    ],
    effects: { strength: 5, health: -3 },
  },
  {
    id: 'wx_cb_04', category: 'combat', minAge: 25, maxAge: 50, probability: 0.382,
    templates: [
      '你在{location}参与了一场小规模冲突，表现出色。',
      '{npc}偷袭你，你在{location}勉强将其击退。',
      '你在{location}发现了敌人的据点，果断出击。',
    ],
    effects: { strength: 4, luck: 2 },
  },
  {
    id: 'wx_cb_05', category: 'combat', minAge: 15, maxAge: 40, probability: 0.544,
    templates: [
      '你在{location}进行了日常训练，技艺略有精进。',
      '你和同伴在{location}对练，互相学习。',
      '你在{location}演练新学的招式，逐渐熟练。',
    ],
    effects: { strength: 2 },
  },
  {
    id: 'wx_cb_06', category: 'combat', minAge: 30, maxAge: 60, probability: 0.715,
    templates: [
      '你在{location}指导后辈战斗技巧，自己也有所感悟。',
      '一场友好的比试在{location}举行，你获得了不错的名次。',
      '你在{location}观摩高手对决，学到了不少实战经验。',
    ],
    effects: { strength: 2, intelligence: 1 },
  },
  {
    id: 'wx_rm_01', category: 'romance', minAge: 18, maxAge: 30, probability: 0.042,
    templates: [
      '你在{location}与{npc}相遇的瞬间，天地变色，{legend}的预言应验——你们是三生石上的命定之人。',
      '{npc}为了救你，不惜耗尽毕生修为。你跪在{location}发誓：此生不负。',
      '你们的故事被{legend}记载，成为了{location}永恒的传说。',
    ],
    effects: { charisma: 10, luck: 8, health: 5 },
  },
  {
    id: 'wx_rm_02', category: 'romance', minAge: 20, maxAge: 35, probability: 0.126,
    templates: [
      '你在{location}邂逅了一位神秘的{npc}，TA的身份让你震惊不已。',
      '{npc}对你一见倾心，经常在{location}找你，你们的感情迅速升温。',
      '你们经历了{legend}的考验，感情反而更加坚不可摧。',
    ],
    effects: { charisma: 6, luck: 4 },
  },
  {
    id: 'wx_rm_03', category: 'romance', minAge: 16, maxAge: 30, probability: 0.283,
    templates: [
      '你救了一位落难的{npc}，TA决定以身相许，你们在{location}私定终身。',
      '你和{npc}在{location}月下相会，互诉衷肠。',
      '{npc}因为你的才华而倾心，主动向你示好。',
    ],
    effects: { charisma: 4, luck: 3 },
  },
  {
    id: 'wx_rm_04', category: 'romance', minAge: 25, maxAge: 40, probability: 0.418,
    templates: [
      '你和{npc}在{location}相识，虽然起初有些误会，但后来成为了恋人。',
      '{npc}送你一件定情信物，你珍藏在身边。',
      '你们一起在{location}经历了危险，感情更加深厚。',
    ],
    effects: { charisma: 3, luck: 2 },
  },
  {
    id: 'wx_rm_05', category: 'romance', minAge: 20, maxAge: 45, probability: 0.528,
    templates: [
      '你在{location}认识了一个有趣的人，但关系尚不明确。',
      '{npc}对你有些好感，但你还没想好如何回应。',
      '你在{location}参加了一场聚会，结识了不少异性。',
    ],
    effects: { charisma: 2 },
  },
  {
    id: 'wx_rm_06', category: 'romance', minAge: 30, maxAge: 50, probability: 0.716,
    templates: [
      '你和{npc}保持着朋友以上、恋人未满的关系。',
      '你在{location}看到了别人恩爱的场景，心中有些羡慕。',
      '这一年感情上没有太大的波澜，你专注于其他事情。',
    ],
    effects: { luck: 1 },
  },
  {
    id: 'wx_cultivation_01', category: 'cultivation', minAge: 40, maxAge: 70, probability: 0.037,
    templates: [
      '你在{location}闭关九九八十一天，出关时天地共鸣，你已触摸到了{legend}的境界！',
      '你的修为达到了前所未有的高度，{location}的灵气因为你而沸腾。',
      '{legend}的虚影亲自降临{location}，为你指点大道。',
    ],
    effects: { special: 12, intelligence: 10, strength: 5 },
  },
  {
    id: 'wx_cultivation_02', category: 'cultivation', minAge: 30, maxAge: 60, probability: 0.105,
    templates: [
      '你成功将{legend}的功法融会贯通，实力暴涨！',
      '你在{location}经历了一场奇遇，修为大涨，连{npc}都震惊不已。',
      '你突破了困扰多年的瓶颈，{location}的天地异象持续了三日三夜。',
    ],
    effects: { special: 8, intelligence: 5 },
  },
  {
    id: 'wx_cultivation_03', category: 'cultivation', minAge: 20, maxAge: 50, probability: 0.299,
    templates: [
      '你在{location}闭关修炼，领悟了新的境界。',
      '{npc}传授你一项绝技，你勤加练习，终于大成。',
      '你在{location}发现了一处灵气充沛的宝地，修炼事半功倍。',
    ],
    effects: { special: 5, intelligence: 3 },
  },
  {
    id: 'wx_cultivation_04', category: 'cultivation', minAge: 35, maxAge: 65, probability: 0.418,
    templates: [
      '你在修炼中遇到了瓶颈，{npc}指点你突破。',
      '你在{location}经历了一场奇遇，修为有所精进。',
      '你成功炼制/制造了辅助修炼的物品，效果显著。',
    ],
    effects: { special: 4, strength: 2 },
  },
  {
    id: 'wx_cultivation_05', category: 'cultivation', minAge: 13, maxAge: 40, probability: 0.525,
    templates: [
      '你在{location}按部就班地修炼，虽然没有突破但根基更加稳固。',
      '{npc}检查了你的修炼进度，表示满意。',
      '你在{location}研读功法秘籍，对一些招式有了新的理解。',
    ],
    effects: { special: 2, intelligence: 1 },
  },
  {
    id: 'wx_cultivation_06', category: 'cultivation', minAge: 40, maxAge: 80, probability: 0.751,
    templates: [
      '你在{location}巩固已有的修为，为下一次突破做准备。',
      '这一年修炼进度平平，但你没有气馁。',
      '{npc}提醒你不可急于求成，你虚心接受。',
    ],
    effects: { special: 2 },
  },
  {
    id: 'wx_ex_01', category: 'exploration', minAge: 25, maxAge: 50, probability: 0.033,
    templates: [
      '你深入{location}最深处，发现了{legend}留下的核心传承，获得了改变命运的机缘！',
      '你在{location}找到了通往另一个维度的入口，{legend}的秘密向你敞开。',
      '你解开了一个困扰世人万年的谜题，{location}的真相让你震惊。',
    ],
    effects: { luck: 10, intelligence: 8, special: 6 },
  },
  {
    id: 'wx_ex_02', category: 'exploration', minAge: 20, maxAge: 45, probability: 0.106,
    templates: [
      '你在{location}找到了{legend}留下的遗迹，虽然危险重重但你决定一探究竟。',
      '你探索了一处危险的{location}，九死一生后带回了珍贵的宝物。',
      '{npc}告诉你{location}有宝物，你前去寻找，果然不虚此行。',
    ],
    effects: { luck: 6, strength: 4 },
  },
  {
    id: 'wx_ex_03', category: 'exploration', minAge: 15, maxAge: 40, probability: 0.298,
    templates: [
      '你深入{location}探险，发现了未知的秘密。',
      '你在{location}找到了一些有价值的物品，收获颇丰。',
      '你在{location}迷路了，却意外发现了一处隐蔽的洞天福地。',
    ],
    effects: { luck: 4, strength: 2 },
  },
  {
    id: 'wx_ex_04', category: 'exploration', minAge: 30, maxAge: 55, probability: 0.404,
    templates: [
      '你在{location}发现了一些古老的壁画，记录着失落的文明。',
      '你探索了一处废弃的{location}，找到了一些有用的物资。',
      '{npc}带你进入了一个秘密的{location}，你大开眼界。',
    ],
    effects: { intelligence: 3, luck: 3 },
  },
  {
    id: 'wx_ex_05', category: 'exploration', minAge: 13, maxAge: 35, probability: 0.524,
    templates: [
      '你在{location}附近逛了逛，虽然没有大发现但开阔了眼界。',
      '你跟着{npc}去{location}采集了一些材料。',
      '你在{location}发现了一些普通的草药，聊胜于无。',
    ],
    effects: { luck: 2 },
  },
  {
    id: 'wx_ex_06', category: 'exploration', minAge: 35, maxAge: 70, probability: 0.761,
    templates: [
      '你在{location}进行了常规的巡查，一切正常。',
      '你重访了以前去过的{location}，有了一些新的发现。',
      '你在{location}休息了一段时间，养精蓄锐。',
    ],
    effects: { health: 2 },
  },
  {
    id: 'wx_ws_01', category: 'world_story', minAge: 40, maxAge: 70, probability: 0.035,
    templates: [
      '{legend}的封印彻底破碎，整个世界陷入了前所未有的动荡，你被卷入了漩涡中心！',
      '一场席卷整个世界的大战爆发了，{location}首当其冲，你必须做出选择。',
      '世界的规则开始改变，{legend}的意志降临，所有人都受到了影响。',
    ],
    effects: { strength: 8, intelligence: 8, charisma: 5, luck: 5 },
  },
  {
    id: 'wx_ws_02', category: 'world_story', minAge: 30, maxAge: 60, probability: 0.172,
    templates: [
      '你发现{location}隐藏着改变世界的秘密，各方势力为此展开了明争暗斗。',
      '{npc}告诉你一个关于世界起源的惊天秘密，你的世界观被彻底颠覆。',
      '传说中的{legend}即将降临，所有人都在做准备，{location}的气氛紧张到了极点。',
    ],
    effects: { intelligence: 6, charisma: 4 },
  },
  {
    id: 'wx_ws_03', category: 'world_story', minAge: 25, maxAge: 50, probability: 0.29,
    templates: [
      '{location}附近发生了局部冲突，你不得不卷入其中。',
      '{npc}带来了一个重要的消息，可能影响到{location}的未来。',
      '你注意到了{location}的一些异常现象，似乎有什么大事要发生。',
    ],
    effects: { charisma: 3, luck: 3 },
  },
  {
    id: 'wx_ws_04', category: 'world_story', minAge: 20, maxAge: 45, probability: 0.531,
    templates: [
      '你听到了一些关于{legend}的传闻，但真假难辨。',
      '{location}发生了一些小变化，但你没有太在意。',
      '{npc}跟你聊了聊最近的时事，你表示关注。',
    ],
    effects: { intelligence: 2 },
  },
  {
    id: 'wx_ws_05', category: 'world_story', minAge: 40, maxAge: 80, probability: 0.7,
    templates: [
      '世界依旧平静，{location}的生活一如既往。',
      '你听说了一些关于{legend}的新消息，但似乎没什么实质内容。',
      '这一年没什么大事发生，你在{location}安稳度日。',
    ],
    effects: { luck: 1 },
  },
  {
    id: 'wx_hd_01', category: 'hidden', minAge: 60, maxAge: 120, probability: 0.064,
    templates: [
      '你超越了{legend}，看到了世界之外的真相——原来一切都只是...',
      '你发现了这个世界的运行规则，{location}只是一场巨大棋局的一角。',
      '{legend}的真正身份让你震惊不已，你终于理解了世界的本质。',
    ],
    effects: { intelligence: 15, special: 10 },
    conditions: [
      { stat: 'intelligence', min: 120 },
    ],
  },
  {
    id: 'wx_hd_02', category: 'hidden', minAge: 50, maxAge: 100, probability: 0.126,
    templates: [
      '你在{location}发现了一个被禁止入内的区域，里面藏着惊人的秘密。',
      '你解开了{legend}留下的谜题，获得了一份隐藏的传承。',
      '{npc}告诉你一个只有极少数人知道的秘密，你感到责任重大。',
    ],
    effects: { intelligence: 10, special: 8 },
    conditions: [
      { stat: 'intelligence', min: 100 },
    ],
  },
  {
    id: 'wx_hd_03', category: 'hidden', minAge: 35, maxAge: 80, probability: 0.267,
    templates: [
      '你在{location}找到了一条隐秘的通道，通向未知的地方。',
      '你发现了一些关于{legend}的隐藏记录，内容令人费解。',
      '{npc}偷偷塞给你一张地图，上面标记着{location}的秘密地点。',
    ],
    effects: { luck: 6, intelligence: 4 },
    conditions: [
      { stat: 'luck', min: 80 },
    ],
  },
  {
    id: 'wx_hd_04', category: 'hidden', minAge: 20, maxAge: 60, probability: 0.622,
    templates: [
      '你在{location}听到了一些奇怪的低语，但找不到来源。',
      '你做了一个关于{legend}的怪梦，醒来后记忆模糊。',
      '{npc}欲言又止，似乎想告诉你什么秘密但最终没说出口。',
    ],
    effects: { intelligence: 3 },
    conditions: [
      { stat: 'intelligence', min: 60 },
    ],
  },
  {
    id: 'wx_dt_01', category: 'death', minAge: 0, maxAge: 100, probability: 0.35,
    templates: [
      '你在{location}遭遇不测，生命力迅速流逝。',
      '你的身体到达了极限，{npc}无能为力。',
      '{legend}的诅咒降临在你身上，你无法抵抗。',
    ],
    effects: { health: -60 },
  },
  {
    id: 'wx_dt_02', category: 'death', minAge: 0, maxAge: 150, probability: 0.45,
    templates: [
      '你在{location}进行了最后的战斗，英勇牺牲。',
      '寿元耗尽，你在{location}静静地闭上了眼睛。',
      '你走火入魔，在{location}化为灰烬。',
    ],
    effects: { health: -80 },
  },
  {
    id: 'wx_dt_03', category: 'death', minAge: 0, maxAge: 200, probability: 0.55,
    templates: [
      '你在{location}被强敌击杀，死不瞑目。',
      '你的伤势恶化，{npc}尽力抢救但回天乏术。',
      '{legend}的力量反噬，你在{location}形神俱灭。',
    ],
    effects: { health: -100 },
  },
  {
    id: 'wx_dt_04', category: 'death', minAge: 0, maxAge: 250, probability: 0.65,
    templates: [
      '你在{location}寿终正寝，周围的人都来为你送行。',
      '你安详地在{location}离世，一生无憾。',
      '{npc}守在你的床前，目送你离开这个世界。',
    ],
    effects: { health: -100 },
  },
  {
    id: 'wx_dt_05', category: 'death', minAge: 0, maxAge: 300, probability: 0.75,
    templates: [
      '你在{location}结束了这一生，灵魂化作流光消散。',
      '你的故事成为了{location}的传说，后人会记得你的名字。',
      '{legend}亲自前来接引你的灵魂，你感到一阵温暖。',
    ],
    effects: { health: -100 },
  },
  {
    id: 'wx_ws_06', category: 'world_story', minAge: 15, maxAge: 15, probability: 0.98,
    templates: [
      '你站在{location}的中央，人生第一次面临真正的抉择。{npc}告诉你，前方有三条路：追求极致的力量、无拘无束的自由，或者守护一切的觉悟。你的选择将改变你的一生。',
    ],
    choices: [
      { text: '追求力量', successRate: 0.7, successText: '你选择了力量之路，从此一往无前，无人能挡', failText: '你选择了力量之路，却发现代价远超想象', effects: { strength: 10, special: 5 }, failEffects: { health: -20, strength: 3 }, flags: ['major_power'], failFlags: ['major_power_fail'] },
      { text: '追求自由', successRate: 0.75, successText: '你选择了自由之路，天地广阔任逍遥', failText: '自由之路充满荆棘，你在{location}迷失了方向', effects: { luck: 10, intelligence: 5 }, failEffects: { luck: -8, charisma: -5 }, flags: ['major_freedom'], failFlags: ['major_freedom_fail'] },
      { text: '追求守护', successRate: 0.8, successText: '你选择了守护之路，成为弱者的支柱', failText: '你的善意被利用，在{location}身心俱疲', effects: { charisma: 8, health: 10 }, failEffects: { charisma: -8, health: -15 }, flags: ['major_guardian'], failFlags: ['major_guardian_fail'] },
    ],
    flags: ['major_seen_15'],
  },
  {
    id: 'wx_ws_07', category: 'world_story', minAge: 20, maxAge: 28, probability: 0.85,
    templates: [
      '因为你选择了力量之路，{location}的强者对你另眼相看。你的力量引起了{legend}的注意。',
      '你在追求力量的过程中，在{location}发现了一本失传已久的强大功法。',
    ],
    effects: { strength: 6, special: 3 },
    flags: ['major_power_1'],
    requiredFlags: ['major_power'],
  },
  {
    id: 'wx_ws_08', category: 'world_story', minAge: 30, maxAge: 40, probability: 0.8,
    templates: [
      '你因为追求力量而获得了强大的实力，但{npc}警告你不要迷失本心。你在{location}展现出的力量让所有人畏惧。',
      '你的力量达到了新的高度，{legend}亲自前来与你切磋，你从中领悟了许多。',
    ],
    effects: { strength: 8, charisma: -3 },
    requiredFlags: ['major_power_1'],
  },
  {
    id: 'wx_ws_09', category: 'world_story', minAge: 20, maxAge: 28, probability: 0.85,
    templates: [
      '你因为选择了自由之路，在{location}结识了来自各地的奇人异士。你的自由精神感染了{npc}。',
      '你在自由探索中意外发现了{legend}留下的隐秘线索，命运的齿轮开始转动。',
    ],
    effects: { luck: 6, intelligence: 4 },
    flags: ['major_freedom_1'],
    requiredFlags: ['major_freedom'],
  },
  {
    id: 'wx_ws_10', category: 'world_story', minAge: 30, maxAge: 40, probability: 0.8,
    templates: [
      '你在自由之路上的探索让你发现了{location}不为人知的秘密。{legend}的遗迹因为你的一次偶然探索而被发现。',
      '{npc}告诉你，你的自由精神正是{legend}当年所追求的，你冥冥之中走上了正确的道路。',
    ],
    effects: { luck: 8, special: 4 },
    requiredFlags: ['major_freedom_1'],
  },
  {
    id: 'wx_ws_11', category: 'world_story', minAge: 20, maxAge: 28, probability: 0.85,
    templates: [
      '你因为选择了守护之路，在{location}被无数人敬仰。{npc}因为你的守护而得以存活，发誓永远追随你。',
      '你守护的人们在{location}为你建立了一座小小的祠堂，虽然简陋但充满诚意。',
    ],
    effects: { charisma: 6, health: 5 },
    flags: ['major_guardian_1'],
    requiredFlags: ['major_guardian'],
  },
  {
    id: 'wx_ws_12', category: 'world_story', minAge: 30, maxAge: 40, probability: 0.8,
    templates: [
      '你守护的人在{location}遭遇了危机，你毫不犹豫地挺身而出。你的守护之名传遍了四方。',
      '{legend}也对你的品德表示赞赏，亲自赐予你一份守护者的传承。',
    ],
    effects: { charisma: 8, strength: 4 },
    requiredFlags: ['major_guardian_1'],
  },
  {
    id: 'wx_ws_13', category: 'world_story', minAge: 30, maxAge: 30, probability: 0.97,
    templates: [
      '{location}发生了一件震动天下的大事。{npc}向你提出了一个交易：违背本心可获巨大利益，坚守正义则可能失去一切。这是对你灵魂的考验。',
    ],
    choices: [
      { text: '坚守本心', successRate: 0.65, successText: '你拒绝了诱惑，虽然失去了眼前的利益，但道心更加坚定', failText: '你坚守了本心，却遭到了黑暗势力的疯狂报复', effects: { intelligence: 8, charisma: 5 }, failEffects: { health: -20, strength: -5 }, flags: ['major_justice'], failFlags: ['major_justice_fail'] },
      { text: '不择手段', successRate: 0.55, successText: '你获得了梦寐以求的力量与财富，但内心开始有了一丝阴霾', failText: '你的阴谋被揭穿，在{location}声名狼藉', effects: { strength: 10, special: 5 }, failEffects: { charisma: -15, luck: -10 }, flags: ['major_dark'], failFlags: ['major_dark_fail'] },
    ],
    flags: ['major_seen_30'],
  },
  {
    id: 'wx_ws_14', category: 'world_story', minAge: 35, maxAge: 45, probability: 0.82,
    templates: [
      '因为你坚守了本心，{legend}亲自降临{location}为你加持。你的正义之名吸引了无数志同道合者。',
      '你在{location}建立了一个正义的据点，成为了黑暗势力的眼中钉。',
    ],
    effects: { intelligence: 6, charisma: 6, luck: 4 },
    requiredFlags: ['major_justice'],
  },
  {
    id: 'wx_ws_15', category: 'world_story', minAge: 35, maxAge: 45, probability: 0.82,
    templates: [
      '你因为不择手段而获得了强大的力量，但{npc}看你的眼神变得复杂。你在{location}建立了自己的势力。',
      '{legend}因为你的黑暗之路而对你产生了兴趣，这是福是祸尚未可知。',
    ],
    effects: { strength: 8, special: 6, charisma: -5 },
    requiredFlags: ['major_dark'],
  },
  {
    id: 'wx_ws_16', category: 'world_story', minAge: 45, maxAge: 45, probability: 0.96,
    templates: [
      '你遭遇了人生中最危险的敌人。{legend}的化身出现在{location}，向你发起挑战。所有人都认为你没有胜算。这是生死抉择的时刻。',
    ],
    choices: [
      { text: '以命相搏', successRate: 0.45, successText: '你拼尽一切，竟然真的战胜了{legend}的化身！天下震动！', failText: '你拼死一战，虽然重创了敌人，但自己也命悬一线', effects: { strength: 12, charisma: 8 }, failEffects: { health: -40, strength: 5 }, flags: ['major_bravery'], failFlags: ['major_bravery_fail'] },
      { text: '忍辱求生', successRate: 0.75, successText: '你选择了暂时退让，保存实力等待时机。智者不逞匹夫之勇', failText: '你的退让被当作懦弱，{location}的人开始轻视你', effects: { intelligence: 8, luck: 5 }, failEffects: { charisma: -10, luck: -5 }, flags: ['major_wisdom'], failFlags: ['major_wisdom_fail'] },
    ],
    flags: ['major_seen_45'],
  },
  {
    id: 'wx_ws_17', category: 'world_story', minAge: 48, maxAge: 58, probability: 0.8,
    templates: [
      '你战胜{legend}化身的壮举传遍了整个世界，{location}的人都把你当作英雄。你的勇气激励了无数人。',
      '{npc}说你是万古以来最勇敢的人，你的名字将被刻入{location}的历史。',
    ],
    effects: { strength: 6, charisma: 8, luck: 4 },
    requiredFlags: ['major_bravery'],
  },
  {
    id: 'wx_ws_18', category: 'world_story', minAge: 48, maxAge: 58, probability: 0.8,
    templates: [
      '你忍辱负重后的反击让所有人震惊，{location}的敌人在你最强的时刻倒下。',
      '{npc}赞叹你的智慧——不争一时之长短，方得始终。你的名声反而比以前更盛。',
    ],
    effects: { intelligence: 8, luck: 6, special: 4 },
    requiredFlags: ['major_wisdom'],
  },
  {
    id: 'wx_ws_19', category: 'world_story', minAge: 60, maxAge: 60, probability: 0.95,
    templates: [
      '你站在{location}的最高处，俯瞰着这个世界。{legend}的最后传承出现在你面前：追求永恒的极致，或者守护人间直到最后一刻。这是你的终极抉择。',
    ],
    choices: [
      { text: '追求永恒', successRate: 0.6, successText: '你踏上了追求永恒的道路，从此与天地同寿。但你回头望去，发现身后已空无一人', failText: '你追求永恒的尝试失败了，但你无怨无悔', effects: { special: 15, intelligence: 10 }, failEffects: { health: -30, special: 5 }, flags: ['major_eternal'], failFlags: ['major_eternal_fail'] },
      { text: '守护人间', successRate: 0.8, successText: '你选择了守护人间，将自己的一切都奉献给了这个世界。后人将永远记得你的名字', failText: '你的守护让你耗尽了一切，但你知道这是值得的', effects: { charisma: 12, health: 10, luck: 8 }, failEffects: { health: -20, charisma: 5 }, flags: ['major_legacy'], failFlags: ['major_legacy_fail'] },
    ],
    flags: ['major_seen_60'],
  },
  {
    id: 'wx_ws_20', category: 'world_story', minAge: 65, maxAge: 80, probability: 0.78,
    templates: [
      '你追求永恒的道路越走越远，{location}的凡尘俗世已与你无关。你触摸到了{legend}的境界。',
      '你获得了永恒的生命，但内心却越来越孤独。你开始怀疑当初的选择。',
    ],
    effects: { special: 10, intelligence: 8, charisma: -5 },
    requiredFlags: ['major_eternal'],
  },
  {
    id: 'wx_ws_21', category: 'world_story', minAge: 65, maxAge: 80, probability: 0.78,
    templates: [
      '你守护人间的举动感动了无数人，{location}建起了你的雕像。你的传承在{npc}手中延续。',
      '这个世界因为你的存在而更加美好，{legend}也为你的选择而动容。',
    ],
    effects: { charisma: 10, luck: 8, health: 5 },
    requiredFlags: ['major_legacy'],
  },
  {
    id: 'wx_ie_farmers_son_01', category: 'identity_exclusive', minAge: 3, maxAge: 8, probability: 0.85,
    templates: [
      '作为农家少年，你从小就展现出与众不同的天赋。偶遇高人的特质在你体内蠢蠢欲动。',
      '你在{location}经历了一件改变一生的事，那是农家少年的命运转折点。',
      '{npc}看出了你是农家少年的苗子，决定暗中帮助你。',
      '你体内的偶遇高人之力在{location}第一次觉醒。',
    ],
    effects: { special: 5 },
    flags: ['chain_farmers_son_childhood_0'],
    identityExclusive: 'farmers_son',
  },
  {
    id: 'wx_ie_farmers_son_02', category: 'identity_exclusive', minAge: 7, maxAge: 12, probability: 0.85,
    templates: [
      '作为农家少年，你从小就展现出与众不同的天赋。山野奇遇的特质在你体内蠢蠢欲动。',
      '你在{location}经历了一件改变一生的事，那是农家少年的命运转折点。',
      '{npc}看出了你是农家少年的苗子，决定暗中帮助你。',
      '你体内的山野奇遇之力在{location}第一次觉醒。',
    ],
    effects: { strength: 4, luck: 2 },
    flags: ['chain_farmers_son_childhood_1'],
    identityExclusive: 'farmers_son',
  },
  {
    id: 'wx_ie_farmers_son_03', category: 'identity_exclusive', minAge: 14, maxAge: 20, probability: 0.8,
    templates: [
      '作为农家少年，你在{location}遇到了草根崛起的试炼。',
      '你的农家少年身份让你在{location}陷入了困境。',
      '{npc}因为你的农家少年身份而对你另眼相看。',
      '你在{location}觉醒了农家少年特有的能力。',
    ],
    effects: { special: 6 },
    flags: ['chain_farmers_son_growth_0'],
    requiredFlags: ['chain_farmers_son_childhood_0'],
    identityExclusive: 'farmers_son',
    chainPriority: 1,
  },
  {
    id: 'wx_ie_farmers_son_04', category: 'identity_exclusive', minAge: 19, maxAge: 25, probability: 0.8,
    templates: [
      '作为农家少年，你在{location}遇到了草根崛起的试炼。',
      '你的农家少年身份让你在{location}陷入了困境。',
      '{npc}因为你的农家少年身份而对你另眼相看。',
      '你在{location}觉醒了农家少年特有的能力。',
    ],
    effects: { charisma: 4, luck: 3 },
    flags: ['chain_farmers_son_growth_1'],
    requiredFlags: ['chain_farmers_son_childhood_0'],
    identityExclusive: 'farmers_son',
    chainPriority: 1,
  },
  {
    id: 'wx_ie_farmers_son_05', category: 'identity_exclusive', minAge: 26, maxAge: 35, probability: 0.75,
    templates: [
      '作为农家少年，你在{location}迎来了人生的重要转折点——田园归隐。',
      '你的农家少年之路在{location}遭遇了最大的挑战。',
      '{legend}的传说与你的农家少年身份产生了某种联系。',
      '你在{location}做出了一个关乎农家少年命运的重要决定。',
    ],
    effects: { intelligence: 8 },
    flags: ['chain_farmers_son_adult_0'],
    requiredFlags: ['chain_farmers_son_growth_0'],
    identityExclusive: 'farmers_son',
    chainPriority: 2,
  },
  {
    id: 'wx_ie_farmers_son_06', category: 'identity_exclusive', minAge: 36, maxAge: 45, probability: 0.75,
    templates: [
      '作为农家少年，你在{location}迎来了人生的重要转折点——田园归隐。',
      '你的农家少年之路在{location}遭遇了最大的挑战。',
      '{legend}的传说与你的农家少年身份产生了某种联系。',
      '你在{location}做出了一个关乎农家少年命运的重要决定。',
    ],
    choices: [
      { text: '坚持农家少年之道', successRate: 0.5, successText: '你成功了，田园归隐之力大增', failText: '你失败了，但收获经验', effects: { special: 10, strength: 5 }, failEffects: { intelligence: 5, health: -5 }, flags: ['branch_identity_farmers_son_path'], failFlags: ['branch_identity_farmers_son_path_fail'] },
      { text: '另辟蹊径', successRate: 0.7, successText: '你找到了新的道路', failText: '你迷失了方向', effects: { luck: 5, charisma: 5 }, failEffects: { luck: -3 }, flags: ['branch_identity_farmers_son_new'], failFlags: ['branch_identity_farmers_son_new_fail'] },
    ],
    flags: ['chain_farmers_son_adult_1'],
    requiredFlags: ['chain_farmers_son_growth_0'],
    identityExclusive: 'farmers_son',
    chainPriority: 2,
  },
  {
    id: 'wx_ie_farmers_son_07', category: 'identity_exclusive', minAge: 10, maxAge: 30, probability: 0.7,
    templates: [
      '作为农家少年，你与{legend}产生了宿命般的纠葛。',
      '你在{location}发现了关于农家少年起源的秘密。',
      '{npc}揭示了一个关于农家少年的惊天秘密。',
      '你的农家少年血脉在{location}发生了异变。',
    ],
    effects: { special: 10, health: -5 },
    flags: ['chain_farmers_son_special_0'],
    requiredFlags: ['chain_farmers_son_adult_0'],
    identityExclusive: 'farmers_son',
    chainPriority: 3,
  },
  {
    id: 'wx_ie_farmers_son_08', category: 'identity_exclusive', minAge: 30, maxAge: 60, probability: 0.7,
    templates: [
      '作为农家少年，你与{legend}产生了宿命般的纠葛。',
      '你在{location}发现了关于农家少年起源的秘密。',
      '{npc}揭示了一个关于农家少年的惊天秘密。',
      '你的农家少年血脉在{location}发生了异变。',
    ],
    effects: { strength: 8, luck: 5 },
    flags: ['chain_farmers_son_special_1'],
    requiredFlags: ['chain_farmers_son_adult_0'],
    identityExclusive: 'farmers_son',
    chainPriority: 3,
  },
  {
    id: 'wx_ie_aristocrat_01', category: 'identity_exclusive', minAge: 3, maxAge: 8, probability: 0.85,
    templates: [
      '作为世家子弟，你从小就展现出与众不同的天赋。家族使命的特质在你体内蠢蠢欲动。',
      '你在{location}经历了一件改变一生的事，那是世家子弟的命运转折点。',
      '{npc}看出了你是世家子弟的苗子，决定暗中帮助你。',
      '你体内的家族使命之力在{location}第一次觉醒。',
    ],
    effects: { strength: 4, luck: 2 },
    flags: ['chain_aristocrat_childhood_0'],
    identityExclusive: 'aristocrat',
  },
  {
    id: 'wx_ie_aristocrat_02', category: 'identity_exclusive', minAge: 7, maxAge: 12, probability: 0.85,
    templates: [
      '作为世家子弟，你从小就展现出与众不同的天赋。权谋斗争的特质在你体内蠢蠢欲动。',
      '你在{location}经历了一件改变一生的事，那是世家子弟的命运转折点。',
      '{npc}看出了你是世家子弟的苗子，决定暗中帮助你。',
      '你体内的权谋斗争之力在{location}第一次觉醒。',
    ],
    effects: { special: 5 },
    flags: ['chain_aristocrat_childhood_1'],
    identityExclusive: 'aristocrat',
  },
  {
    id: 'wx_ie_aristocrat_03', category: 'identity_exclusive', minAge: 14, maxAge: 20, probability: 0.8,
    templates: [
      '作为世家子弟，你在{location}遇到了世家责任的试炼。',
      '你的世家子弟身份让你在{location}陷入了困境。',
      '{npc}因为你的世家子弟身份而对你另眼相看。',
      '你在{location}觉醒了世家子弟特有的能力。',
    ],
    effects: { charisma: 4, luck: 3 },
    flags: ['chain_aristocrat_growth_0'],
    requiredFlags: ['chain_aristocrat_childhood_0'],
    identityExclusive: 'aristocrat',
    chainPriority: 1,
  },
  {
    id: 'wx_ie_aristocrat_04', category: 'identity_exclusive', minAge: 19, maxAge: 25, probability: 0.8,
    templates: [
      '作为世家子弟，你在{location}遇到了世家责任的试炼。',
      '你的世家子弟身份让你在{location}陷入了困境。',
      '{npc}因为你的世家子弟身份而对你另眼相看。',
      '你在{location}觉醒了世家子弟特有的能力。',
    ],
    effects: { special: 6 },
    flags: ['chain_aristocrat_growth_1'],
    requiredFlags: ['chain_aristocrat_childhood_0'],
    identityExclusive: 'aristocrat',
    chainPriority: 1,
  },
  {
    id: 'wx_ie_aristocrat_05', category: 'identity_exclusive', minAge: 26, maxAge: 35, probability: 0.75,
    templates: [
      '作为世家子弟，你在{location}迎来了人生的重要转折点——家族兴衰。',
      '你的世家子弟之路在{location}遭遇了最大的挑战。',
      '{legend}的传说与你的世家子弟身份产生了某种联系。',
      '你在{location}做出了一个关乎世家子弟命运的重要决定。',
    ],
    effects: { special: 8 },
    flags: ['chain_aristocrat_adult_0'],
    requiredFlags: ['chain_aristocrat_growth_0'],
    identityExclusive: 'aristocrat',
    chainPriority: 2,
  },
  {
    id: 'wx_ie_aristocrat_06', category: 'identity_exclusive', minAge: 36, maxAge: 45, probability: 0.75,
    templates: [
      '作为世家子弟，你在{location}迎来了人生的重要转折点——家族兴衰。',
      '你的世家子弟之路在{location}遭遇了最大的挑战。',
      '{legend}的传说与你的世家子弟身份产生了某种联系。',
      '你在{location}做出了一个关乎世家子弟命运的重要决定。',
    ],
    choices: [
      { text: '坚持世家子弟之道', successRate: 0.5, successText: '你成功了，家族兴衰之力大增', failText: '你失败了，但收获经验', effects: { special: 10, strength: 5 }, failEffects: { intelligence: 5, health: -5 }, flags: ['branch_identity_aristocrat_path'], failFlags: ['branch_identity_aristocrat_path_fail'] },
      { text: '另辟蹊径', successRate: 0.7, successText: '你找到了新的道路', failText: '你迷失了方向', effects: { luck: 5, charisma: 5 }, failEffects: { luck: -3 }, flags: ['branch_identity_aristocrat_new'], failFlags: ['branch_identity_aristocrat_new_fail'] },
    ],
    flags: ['chain_aristocrat_adult_1'],
    requiredFlags: ['chain_aristocrat_growth_0'],
    identityExclusive: 'aristocrat',
    chainPriority: 2,
  },
  {
    id: 'wx_ie_aristocrat_07', category: 'identity_exclusive', minAge: 10, maxAge: 30, probability: 0.7,
    templates: [
      '作为世家子弟，你与{legend}产生了宿命般的纠葛。',
      '你在{location}发现了关于世家子弟起源的秘密。',
      '{npc}揭示了一个关于世家子弟的惊天秘密。',
      '你的世家子弟血脉在{location}发生了异变。',
    ],
    effects: { intelligence: 10 },
    flags: ['chain_aristocrat_special_0'],
    requiredFlags: ['chain_aristocrat_adult_0'],
    identityExclusive: 'aristocrat',
    chainPriority: 3,
  },
  {
    id: 'wx_ie_aristocrat_08', category: 'identity_exclusive', minAge: 30, maxAge: 60, probability: 0.7,
    templates: [
      '作为世家子弟，你与{legend}产生了宿命般的纠葛。',
      '你在{location}发现了关于世家子弟起源的秘密。',
      '{npc}揭示了一个关于世家子弟的惊天秘密。',
      '你的世家子弟血脉在{location}发生了异变。',
    ],
    effects: { strength: 8, luck: 5 },
    flags: ['chain_aristocrat_special_1'],
    requiredFlags: ['chain_aristocrat_adult_0'],
    identityExclusive: 'aristocrat',
    chainPriority: 3,
  },
  {
    id: 'wx_ie_orphan_01', category: 'identity_exclusive', minAge: 3, maxAge: 8, probability: 0.85,
    templates: [
      '作为孤儿，你从小就展现出与众不同的天赋。街头生存的特质在你体内蠢蠢欲动。',
      '你在{location}经历了一件改变一生的事，那是孤儿的命运转折点。',
      '{npc}看出了你是孤儿的苗子，决定暗中帮助你。',
      '你体内的街头生存之力在{location}第一次觉醒。',
    ],
    effects: { special: 5 },
    flags: ['chain_orphan_childhood_0'],
    identityExclusive: 'orphan',
  },
  {
    id: 'wx_ie_orphan_02', category: 'identity_exclusive', minAge: 7, maxAge: 12, probability: 0.85,
    templates: [
      '作为孤儿，你从小就展现出与众不同的天赋。意外师承的特质在你体内蠢蠢欲动。',
      '你在{location}经历了一件改变一生的事，那是孤儿的命运转折点。',
      '{npc}看出了你是孤儿的苗子，决定暗中帮助你。',
      '你体内的意外师承之力在{location}第一次觉醒。',
    ],
    effects: { strength: 4, luck: 2 },
    flags: ['chain_orphan_childhood_1'],
    identityExclusive: 'orphan',
  },
  {
    id: 'wx_ie_orphan_03', category: 'identity_exclusive', minAge: 14, maxAge: 20, probability: 0.8,
    templates: [
      '作为孤儿，你在{location}遇到了无依无靠的试炼。',
      '你的孤儿身份让你在{location}陷入了困境。',
      '{npc}因为你的孤儿身份而对你另眼相看。',
      '你在{location}觉醒了孤儿特有的能力。',
    ],
    effects: { charisma: 4, luck: 3 },
    flags: ['chain_orphan_growth_0'],
    requiredFlags: ['chain_orphan_childhood_0'],
    identityExclusive: 'orphan',
    chainPriority: 1,
  },
  {
    id: 'wx_ie_orphan_04', category: 'identity_exclusive', minAge: 19, maxAge: 25, probability: 0.8,
    templates: [
      '作为孤儿，你在{location}遇到了无依无靠的试炼。',
      '你的孤儿身份让你在{location}陷入了困境。',
      '{npc}因为你的孤儿身份而对你另眼相看。',
      '你在{location}觉醒了孤儿特有的能力。',
    ],
    effects: { strength: 6 },
    flags: ['chain_orphan_growth_1'],
    requiredFlags: ['chain_orphan_childhood_0'],
    identityExclusive: 'orphan',
    chainPriority: 1,
  },
  {
    id: 'wx_ie_orphan_05', category: 'identity_exclusive', minAge: 26, maxAge: 35, probability: 0.75,
    templates: [
      '作为孤儿，你在{location}迎来了人生的重要转折点——自立门户。',
      '你的孤儿之路在{location}遭遇了最大的挑战。',
      '{legend}的传说与你的孤儿身份产生了某种联系。',
      '你在{location}做出了一个关乎孤儿命运的重要决定。',
    ],
    effects: { strength: 8 },
    flags: ['chain_orphan_adult_0'],
    requiredFlags: ['chain_orphan_growth_0'],
    identityExclusive: 'orphan',
    chainPriority: 2,
  },
  {
    id: 'wx_ie_orphan_06', category: 'identity_exclusive', minAge: 36, maxAge: 45, probability: 0.75,
    templates: [
      '作为孤儿，你在{location}迎来了人生的重要转折点——自立门户。',
      '你的孤儿之路在{location}遭遇了最大的挑战。',
      '{legend}的传说与你的孤儿身份产生了某种联系。',
      '你在{location}做出了一个关乎孤儿命运的重要决定。',
    ],
    choices: [
      { text: '坚持孤儿之道', successRate: 0.5, successText: '你成功了，自立门户之力大增', failText: '你失败了，但收获经验', effects: { special: 10, strength: 5 }, failEffects: { intelligence: 5, health: -5 }, flags: ['branch_identity_orphan_path'], failFlags: ['branch_identity_orphan_path_fail'] },
      { text: '另辟蹊径', successRate: 0.7, successText: '你找到了新的道路', failText: '你迷失了方向', effects: { luck: 5, charisma: 5 }, failEffects: { luck: -3 }, flags: ['branch_identity_orphan_new'], failFlags: ['branch_identity_orphan_new_fail'] },
    ],
    flags: ['chain_orphan_adult_1'],
    requiredFlags: ['chain_orphan_growth_0'],
    identityExclusive: 'orphan',
    chainPriority: 2,
  },
  {
    id: 'wx_ie_orphan_07', category: 'identity_exclusive', minAge: 10, maxAge: 30, probability: 0.7,
    templates: [
      '作为孤儿，你与{legend}产生了宿命般的纠葛。',
      '你在{location}发现了关于孤儿起源的秘密。',
      '{npc}揭示了一个关于孤儿的惊天秘密。',
      '你的孤儿血脉在{location}发生了异变。',
    ],
    effects: { intelligence: 10 },
    flags: ['chain_orphan_special_0'],
    requiredFlags: ['chain_orphan_adult_0'],
    identityExclusive: 'orphan',
    chainPriority: 3,
  },
  {
    id: 'wx_ie_orphan_08', category: 'identity_exclusive', minAge: 30, maxAge: 60, probability: 0.7,
    templates: [
      '作为孤儿，你与{legend}产生了宿命般的纠葛。',
      '你在{location}发现了关于孤儿起源的秘密。',
      '{npc}揭示了一个关于孤儿的惊天秘密。',
      '你的孤儿血脉在{location}发生了异变。',
    ],
    effects: { intelligence: 10 },
    flags: ['chain_orphan_special_1'],
    requiredFlags: ['chain_orphan_adult_0'],
    identityExclusive: 'orphan',
    chainPriority: 3,
  },
  {
    id: 'wx_ie_demon_disciple_01', category: 'identity_exclusive', minAge: 3, maxAge: 8, probability: 0.85,
    templates: [
      '作为魔教后人，你从小就展现出与众不同的天赋。身份暴露的特质在你体内蠢蠢欲动。',
      '你在{location}经历了一件改变一生的事，那是魔教后人的命运转折点。',
      '{npc}看出了你是魔教后人的苗子，决定暗中帮助你。',
      '你体内的身份暴露之力在{location}第一次觉醒。',
    ],
    effects: { intelligence: 5 },
    flags: ['chain_demon_disciple_childhood_0'],
    identityExclusive: 'demon_disciple',
  },
  {
    id: 'wx_ie_demon_disciple_02', category: 'identity_exclusive', minAge: 7, maxAge: 12, probability: 0.85,
    templates: [
      '作为魔教后人，你从小就展现出与众不同的天赋。正邪抉择的特质在你体内蠢蠢欲动。',
      '你在{location}经历了一件改变一生的事，那是魔教后人的命运转折点。',
      '{npc}看出了你是魔教后人的苗子，决定暗中帮助你。',
      '你体内的正邪抉择之力在{location}第一次觉醒。',
    ],
    effects: { intelligence: 5 },
    flags: ['chain_demon_disciple_childhood_1'],
    identityExclusive: 'demon_disciple',
  },
  {
    id: 'wx_ie_demon_disciple_03', category: 'identity_exclusive', minAge: 14, maxAge: 20, probability: 0.8,
    templates: [
      '作为魔教后人，你在{location}遇到了魔教复兴的试炼。',
      '你的魔教后人身份让你在{location}陷入了困境。',
      '{npc}因为你的魔教后人身份而对你另眼相看。',
      '你在{location}觉醒了魔教后人特有的能力。',
    ],
    effects: { charisma: 4, luck: 3 },
    flags: ['chain_demon_disciple_growth_0'],
    requiredFlags: ['chain_demon_disciple_childhood_0'],
    identityExclusive: 'demon_disciple',
    chainPriority: 1,
  },
  {
    id: 'wx_ie_demon_disciple_04', category: 'identity_exclusive', minAge: 19, maxAge: 25, probability: 0.8,
    templates: [
      '作为魔教后人，你在{location}遇到了魔教复兴的试炼。',
      '你的魔教后人身份让你在{location}陷入了困境。',
      '{npc}因为你的魔教后人身份而对你另眼相看。',
      '你在{location}觉醒了魔教后人特有的能力。',
    ],
    effects: { special: 6 },
    flags: ['chain_demon_disciple_growth_1'],
    requiredFlags: ['chain_demon_disciple_childhood_0'],
    identityExclusive: 'demon_disciple',
    chainPriority: 1,
  },
  {
    id: 'wx_ie_demon_disciple_05', category: 'identity_exclusive', minAge: 26, maxAge: 35, probability: 0.75,
    templates: [
      '作为魔教后人，你在{location}迎来了人生的重要转折点——洗白之路。',
      '你的魔教后人之路在{location}遭遇了最大的挑战。',
      '{legend}的传说与你的魔教后人身份产生了某种联系。',
      '你在{location}做出了一个关乎魔教后人命运的重要决定。',
    ],
    effects: { special: 8 },
    flags: ['chain_demon_disciple_adult_0'],
    requiredFlags: ['chain_demon_disciple_growth_0'],
    identityExclusive: 'demon_disciple',
    chainPriority: 2,
  },
  {
    id: 'wx_ie_demon_disciple_06', category: 'identity_exclusive', minAge: 36, maxAge: 45, probability: 0.75,
    templates: [
      '作为魔教后人，你在{location}迎来了人生的重要转折点——洗白之路。',
      '你的魔教后人之路在{location}遭遇了最大的挑战。',
      '{legend}的传说与你的魔教后人身份产生了某种联系。',
      '你在{location}做出了一个关乎魔教后人命运的重要决定。',
    ],
    choices: [
      { text: '坚持魔教后人之道', successRate: 0.5, successText: '你成功了，洗白之路之力大增', failText: '你失败了，但收获经验', effects: { special: 10, strength: 5 }, failEffects: { intelligence: 5, health: -5 }, flags: ['branch_identity_demon_disciple_path'], failFlags: ['branch_identity_demon_disciple_path_fail'] },
      { text: '另辟蹊径', successRate: 0.7, successText: '你找到了新的道路', failText: '你迷失了方向', effects: { luck: 5, charisma: 5 }, failEffects: { luck: -3 }, flags: ['branch_identity_demon_disciple_new'], failFlags: ['branch_identity_demon_disciple_new_fail'] },
    ],
    flags: ['chain_demon_disciple_adult_1'],
    requiredFlags: ['chain_demon_disciple_growth_0'],
    identityExclusive: 'demon_disciple',
    chainPriority: 2,
  },
  {
    id: 'wx_ie_demon_disciple_07', category: 'identity_exclusive', minAge: 10, maxAge: 30, probability: 0.7,
    templates: [
      '作为魔教后人，你与{legend}产生了宿命般的纠葛。',
      '你在{location}发现了关于魔教后人起源的秘密。',
      '{npc}揭示了一个关于魔教后人的惊天秘密。',
      '你的魔教后人血脉在{location}发生了异变。',
    ],
    effects: { intelligence: 10 },
    flags: ['chain_demon_disciple_special_0'],
    requiredFlags: ['chain_demon_disciple_adult_0'],
    identityExclusive: 'demon_disciple',
    chainPriority: 3,
  },
  {
    id: 'wx_ie_demon_disciple_08', category: 'identity_exclusive', minAge: 30, maxAge: 60, probability: 0.7,
    templates: [
      '作为魔教后人，你与{legend}产生了宿命般的纠葛。',
      '你在{location}发现了关于魔教后人起源的秘密。',
      '{npc}揭示了一个关于魔教后人的惊天秘密。',
      '你的魔教后人血脉在{location}发生了异变。',
    ],
    effects: { special: 10, health: -5 },
    flags: ['chain_demon_disciple_special_1'],
    requiredFlags: ['chain_demon_disciple_adult_0'],
    identityExclusive: 'demon_disciple',
    chainPriority: 3,
  },
  {
    id: 'wx_ie_spy_01', category: 'identity_exclusive', minAge: 3, maxAge: 8, probability: 0.85,
    templates: [
      '作为朝廷密探，你从小就展现出与众不同的天赋。双重身份的特质在你体内蠢蠢欲动。',
      '你在{location}经历了一件改变一生的事，那是朝廷密探的命运转折点。',
      '{npc}看出了你是朝廷密探的苗子，决定暗中帮助你。',
      '你体内的双重身份之力在{location}第一次觉醒。',
    ],
    effects: { intelligence: 5 },
    flags: ['chain_spy_childhood_0'],
    identityExclusive: 'spy',
  },
  {
    id: 'wx_ie_spy_02', category: 'identity_exclusive', minAge: 7, maxAge: 12, probability: 0.85,
    templates: [
      '作为朝廷密探，你从小就展现出与众不同的天赋。任务危机的特质在你体内蠢蠢欲动。',
      '你在{location}经历了一件改变一生的事，那是朝廷密探的命运转折点。',
      '{npc}看出了你是朝廷密探的苗子，决定暗中帮助你。',
      '你体内的任务危机之力在{location}第一次觉醒。',
    ],
    effects: { intelligence: 5 },
    flags: ['chain_spy_childhood_1'],
    identityExclusive: 'spy',
  },
  {
    id: 'wx_ie_spy_03', category: 'identity_exclusive', minAge: 14, maxAge: 20, probability: 0.8,
    templates: [
      '作为朝廷密探，你在{location}遇到了朝廷阴谋的试炼。',
      '你的朝廷密探身份让你在{location}陷入了困境。',
      '{npc}因为你的朝廷密探身份而对你另眼相看。',
      '你在{location}觉醒了朝廷密探特有的能力。',
    ],
    effects: { intelligence: 6 },
    flags: ['chain_spy_growth_0'],
    requiredFlags: ['chain_spy_childhood_0'],
    identityExclusive: 'spy',
    chainPriority: 1,
  },
  {
    id: 'wx_ie_spy_04', category: 'identity_exclusive', minAge: 19, maxAge: 25, probability: 0.8,
    templates: [
      '作为朝廷密探，你在{location}遇到了朝廷阴谋的试炼。',
      '你的朝廷密探身份让你在{location}陷入了困境。',
      '{npc}因为你的朝廷密探身份而对你另眼相看。',
      '你在{location}觉醒了朝廷密探特有的能力。',
    ],
    effects: { strength: 6 },
    flags: ['chain_spy_growth_1'],
    requiredFlags: ['chain_spy_childhood_0'],
    identityExclusive: 'spy',
    chainPriority: 1,
  },
  {
    id: 'wx_ie_spy_05', category: 'identity_exclusive', minAge: 26, maxAge: 35, probability: 0.75,
    templates: [
      '作为朝廷密探，你在{location}迎来了人生的重要转折点——身份认同。',
      '你的朝廷密探之路在{location}遭遇了最大的挑战。',
      '{legend}的传说与你的朝廷密探身份产生了某种联系。',
      '你在{location}做出了一个关乎朝廷密探命运的重要决定。',
    ],
    effects: { special: 8 },
    flags: ['chain_spy_adult_0'],
    requiredFlags: ['chain_spy_growth_0'],
    identityExclusive: 'spy',
    chainPriority: 2,
  },
  {
    id: 'wx_ie_spy_06', category: 'identity_exclusive', minAge: 36, maxAge: 45, probability: 0.75,
    templates: [
      '作为朝廷密探，你在{location}迎来了人生的重要转折点——身份认同。',
      '你的朝廷密探之路在{location}遭遇了最大的挑战。',
      '{legend}的传说与你的朝廷密探身份产生了某种联系。',
      '你在{location}做出了一个关乎朝廷密探命运的重要决定。',
    ],
    choices: [
      { text: '坚持朝廷密探之道', successRate: 0.5, successText: '你成功了，身份认同之力大增', failText: '你失败了，但收获经验', effects: { special: 10, strength: 5 }, failEffects: { intelligence: 5, health: -5 }, flags: ['branch_identity_spy_path'], failFlags: ['branch_identity_spy_path_fail'] },
      { text: '另辟蹊径', successRate: 0.7, successText: '你找到了新的道路', failText: '你迷失了方向', effects: { luck: 5, charisma: 5 }, failEffects: { luck: -3 }, flags: ['branch_identity_spy_new'], failFlags: ['branch_identity_spy_new_fail'] },
    ],
    flags: ['chain_spy_adult_1'],
    requiredFlags: ['chain_spy_growth_0'],
    identityExclusive: 'spy',
    chainPriority: 2,
  },
  {
    id: 'wx_ie_spy_07', category: 'identity_exclusive', minAge: 10, maxAge: 30, probability: 0.7,
    templates: [
      '作为朝廷密探，你与{legend}产生了宿命般的纠葛。',
      '你在{location}发现了关于朝廷密探起源的秘密。',
      '{npc}揭示了一个关于朝廷密探的惊天秘密。',
      '你的朝廷密探血脉在{location}发生了异变。',
    ],
    effects: { special: 10, health: -5 },
    flags: ['chain_spy_special_0'],
    requiredFlags: ['chain_spy_adult_0'],
    identityExclusive: 'spy',
    chainPriority: 3,
  },
  {
    id: 'wx_ie_spy_08', category: 'identity_exclusive', minAge: 30, maxAge: 60, probability: 0.7,
    templates: [
      '作为朝廷密探，你与{legend}产生了宿命般的纠葛。',
      '你在{location}发现了关于朝廷密探起源的秘密。',
      '{npc}揭示了一个关于朝廷密探的惊天秘密。',
      '你的朝廷密探血脉在{location}发生了异变。',
    ],
    effects: { intelligence: 10 },
    flags: ['chain_spy_special_1'],
    requiredFlags: ['chain_spy_adult_0'],
    identityExclusive: 'spy',
    chainPriority: 3,
  },
  {
    id: 'wx_ie_foreigner_01', category: 'identity_exclusive', minAge: 3, maxAge: 8, probability: 0.85,
    templates: [
      '作为异域来客，你从小就展现出与众不同的天赋。文化冲突的特质在你体内蠢蠢欲动。',
      '你在{location}经历了一件改变一生的事，那是异域来客的命运转折点。',
      '{npc}看出了你是异域来客的苗子，决定暗中帮助你。',
      '你体内的文化冲突之力在{location}第一次觉醒。',
    ],
    effects: { special: 5 },
    flags: ['chain_foreigner_childhood_0'],
    identityExclusive: 'foreigner',
  },
  {
    id: 'wx_ie_foreigner_02', category: 'identity_exclusive', minAge: 7, maxAge: 12, probability: 0.85,
    templates: [
      '作为异域来客，你从小就展现出与众不同的天赋。异域武功的特质在你体内蠢蠢欲动。',
      '你在{location}经历了一件改变一生的事，那是异域来客的命运转折点。',
      '{npc}看出了你是异域来客的苗子，决定暗中帮助你。',
      '你体内的异域武功之力在{location}第一次觉醒。',
    ],
    effects: { strength: 4, luck: 2 },
    flags: ['chain_foreigner_childhood_1'],
    identityExclusive: 'foreigner',
  },
  {
    id: 'wx_ie_foreigner_03', category: 'identity_exclusive', minAge: 14, maxAge: 20, probability: 0.8,
    templates: [
      '作为异域来客，你在{location}遇到了归乡之路的试炼。',
      '你的异域来客身份让你在{location}陷入了困境。',
      '{npc}因为你的异域来客身份而对你另眼相看。',
      '你在{location}觉醒了异域来客特有的能力。',
    ],
    effects: { special: 6 },
    flags: ['chain_foreigner_growth_0'],
    requiredFlags: ['chain_foreigner_childhood_0'],
    identityExclusive: 'foreigner',
    chainPriority: 1,
  },
  {
    id: 'wx_ie_foreigner_04', category: 'identity_exclusive', minAge: 19, maxAge: 25, probability: 0.8,
    templates: [
      '作为异域来客，你在{location}遇到了归乡之路的试炼。',
      '你的异域来客身份让你在{location}陷入了困境。',
      '{npc}因为你的异域来客身份而对你另眼相看。',
      '你在{location}觉醒了异域来客特有的能力。',
    ],
    effects: { charisma: 4, luck: 3 },
    flags: ['chain_foreigner_growth_1'],
    requiredFlags: ['chain_foreigner_childhood_0'],
    identityExclusive: 'foreigner',
    chainPriority: 1,
  },
  {
    id: 'wx_ie_foreigner_05', category: 'identity_exclusive', minAge: 26, maxAge: 35, probability: 0.75,
    templates: [
      '作为异域来客，你在{location}迎来了人生的重要转折点——文化桥梁。',
      '你的异域来客之路在{location}遭遇了最大的挑战。',
      '{legend}的传说与你的异域来客身份产生了某种联系。',
      '你在{location}做出了一个关乎异域来客命运的重要决定。',
    ],
    effects: { strength: 8 },
    flags: ['chain_foreigner_adult_0'],
    requiredFlags: ['chain_foreigner_growth_0'],
    identityExclusive: 'foreigner',
    chainPriority: 2,
  },
  {
    id: 'wx_ie_foreigner_06', category: 'identity_exclusive', minAge: 36, maxAge: 45, probability: 0.75,
    templates: [
      '作为异域来客，你在{location}迎来了人生的重要转折点——文化桥梁。',
      '你的异域来客之路在{location}遭遇了最大的挑战。',
      '{legend}的传说与你的异域来客身份产生了某种联系。',
      '你在{location}做出了一个关乎异域来客命运的重要决定。',
    ],
    choices: [
      { text: '坚持异域来客之道', successRate: 0.5, successText: '你成功了，文化桥梁之力大增', failText: '你失败了，但收获经验', effects: { special: 10, strength: 5 }, failEffects: { intelligence: 5, health: -5 }, flags: ['branch_identity_foreigner_path'], failFlags: ['branch_identity_foreigner_path_fail'] },
      { text: '另辟蹊径', successRate: 0.7, successText: '你找到了新的道路', failText: '你迷失了方向', effects: { luck: 5, charisma: 5 }, failEffects: { luck: -3 }, flags: ['branch_identity_foreigner_new'], failFlags: ['branch_identity_foreigner_new_fail'] },
    ],
    flags: ['chain_foreigner_adult_1'],
    requiredFlags: ['chain_foreigner_growth_0'],
    identityExclusive: 'foreigner',
    chainPriority: 2,
  },
  {
    id: 'wx_ie_foreigner_07', category: 'identity_exclusive', minAge: 10, maxAge: 30, probability: 0.7,
    templates: [
      '作为异域来客，你与{legend}产生了宿命般的纠葛。',
      '你在{location}发现了关于异域来客起源的秘密。',
      '{npc}揭示了一个关于异域来客的惊天秘密。',
      '你的异域来客血脉在{location}发生了异变。',
    ],
    effects: { special: 10, health: -5 },
    flags: ['chain_foreigner_special_0'],
    requiredFlags: ['chain_foreigner_adult_0'],
    identityExclusive: 'foreigner',
    chainPriority: 3,
  },
  {
    id: 'wx_ie_foreigner_08', category: 'identity_exclusive', minAge: 30, maxAge: 60, probability: 0.7,
    templates: [
      '作为异域来客，你与{legend}产生了宿命般的纠葛。',
      '你在{location}发现了关于异域来客起源的秘密。',
      '{npc}揭示了一个关于异域来客的惊天秘密。',
      '你的异域来客血脉在{location}发生了异变。',
    ],
    effects: { intelligence: 10 },
    flags: ['chain_foreigner_special_1'],
    requiredFlags: ['chain_foreigner_adult_0'],
    identityExclusive: 'foreigner',
    chainPriority: 3,
  },
  {
    id: 'wx_ie_medic_01', category: 'identity_exclusive', minAge: 3, maxAge: 8, probability: 0.85,
    templates: [
      '作为医仙传人，你从小就展现出与众不同的天赋。悬壶济世的特质在你体内蠢蠢欲动。',
      '你在{location}经历了一件改变一生的事，那是医仙传人的命运转折点。',
      '{npc}看出了你是医仙传人的苗子，决定暗中帮助你。',
      '你体内的悬壶济世之力在{location}第一次觉醒。',
    ],
    effects: { special: 5 },
    flags: ['chain_medic_childhood_0'],
    identityExclusive: 'medic',
  },
  {
    id: 'wx_ie_medic_02', category: 'identity_exclusive', minAge: 7, maxAge: 12, probability: 0.85,
    templates: [
      '作为医仙传人，你从小就展现出与众不同的天赋。毒医之争的特质在你体内蠢蠢欲动。',
      '你在{location}经历了一件改变一生的事，那是医仙传人的命运转折点。',
      '{npc}看出了你是医仙传人的苗子，决定暗中帮助你。',
      '你体内的毒医之争之力在{location}第一次觉醒。',
    ],
    effects: { special: 5 },
    flags: ['chain_medic_childhood_1'],
    identityExclusive: 'medic',
  },
  {
    id: 'wx_ie_medic_03', category: 'identity_exclusive', minAge: 14, maxAge: 20, probability: 0.8,
    templates: [
      '作为医仙传人，你在{location}遇到了医武双修的试炼。',
      '你的医仙传人身份让你在{location}陷入了困境。',
      '{npc}因为你的医仙传人身份而对你另眼相看。',
      '你在{location}觉醒了医仙传人特有的能力。',
    ],
    effects: { strength: 6 },
    flags: ['chain_medic_growth_0'],
    requiredFlags: ['chain_medic_childhood_0'],
    identityExclusive: 'medic',
    chainPriority: 1,
  },
  {
    id: 'wx_ie_medic_04', category: 'identity_exclusive', minAge: 19, maxAge: 25, probability: 0.8,
    templates: [
      '作为医仙传人，你在{location}遇到了医武双修的试炼。',
      '你的医仙传人身份让你在{location}陷入了困境。',
      '{npc}因为你的医仙传人身份而对你另眼相看。',
      '你在{location}觉醒了医仙传人特有的能力。',
    ],
    effects: { intelligence: 6 },
    flags: ['chain_medic_growth_1'],
    requiredFlags: ['chain_medic_childhood_0'],
    identityExclusive: 'medic',
    chainPriority: 1,
  },
  {
    id: 'wx_ie_medic_05', category: 'identity_exclusive', minAge: 26, maxAge: 35, probability: 0.75,
    templates: [
      '作为医仙传人，你在{location}迎来了人生的重要转折点——医仙之路。',
      '你的医仙传人之路在{location}遭遇了最大的挑战。',
      '{legend}的传说与你的医仙传人身份产生了某种联系。',
      '你在{location}做出了一个关乎医仙传人命运的重要决定。',
    ],
    effects: { intelligence: 8 },
    flags: ['chain_medic_adult_0'],
    requiredFlags: ['chain_medic_growth_0'],
    identityExclusive: 'medic',
    chainPriority: 2,
  },
  {
    id: 'wx_ie_medic_06', category: 'identity_exclusive', minAge: 36, maxAge: 45, probability: 0.75,
    templates: [
      '作为医仙传人，你在{location}迎来了人生的重要转折点——医仙之路。',
      '你的医仙传人之路在{location}遭遇了最大的挑战。',
      '{legend}的传说与你的医仙传人身份产生了某种联系。',
      '你在{location}做出了一个关乎医仙传人命运的重要决定。',
    ],
    choices: [
      { text: '坚持医仙传人之道', successRate: 0.5, successText: '你成功了，医仙之路之力大增', failText: '你失败了，但收获经验', effects: { special: 10, strength: 5 }, failEffects: { intelligence: 5, health: -5 }, flags: ['branch_identity_medic_path'], failFlags: ['branch_identity_medic_path_fail'] },
      { text: '另辟蹊径', successRate: 0.7, successText: '你找到了新的道路', failText: '你迷失了方向', effects: { luck: 5, charisma: 5 }, failEffects: { luck: -3 }, flags: ['branch_identity_medic_new'], failFlags: ['branch_identity_medic_new_fail'] },
    ],
    flags: ['chain_medic_adult_1'],
    requiredFlags: ['chain_medic_growth_0'],
    identityExclusive: 'medic',
    chainPriority: 2,
  },
  {
    id: 'wx_ie_medic_07', category: 'identity_exclusive', minAge: 10, maxAge: 30, probability: 0.7,
    templates: [
      '作为医仙传人，你与{legend}产生了宿命般的纠葛。',
      '你在{location}发现了关于医仙传人起源的秘密。',
      '{npc}揭示了一个关于医仙传人的惊天秘密。',
      '你的医仙传人血脉在{location}发生了异变。',
    ],
    effects: { strength: 8, luck: 5 },
    flags: ['chain_medic_special_0'],
    requiredFlags: ['chain_medic_adult_0'],
    identityExclusive: 'medic',
    chainPriority: 3,
  },
  {
    id: 'wx_ie_medic_08', category: 'identity_exclusive', minAge: 30, maxAge: 60, probability: 0.7,
    templates: [
      '作为医仙传人，你与{legend}产生了宿命般的纠葛。',
      '你在{location}发现了关于医仙传人起源的秘密。',
      '{npc}揭示了一个关于医仙传人的惊天秘密。',
      '你的医仙传人血脉在{location}发生了异变。',
    ],
    effects: { intelligence: 10 },
    flags: ['chain_medic_special_1'],
    requiredFlags: ['chain_medic_adult_0'],
    identityExclusive: 'medic',
    chainPriority: 3,
  },
  {
    id: 'wx_ie_poisoner_01', category: 'identity_exclusive', minAge: 3, maxAge: 8, probability: 0.85,
    templates: [
      '作为毒师弟子，你从小就展现出与众不同的天赋。毒术精进的特质在你体内蠢蠢欲动。',
      '你在{location}经历了一件改变一生的事，那是毒师弟子的命运转折点。',
      '{npc}看出了你是毒师弟子的苗子，决定暗中帮助你。',
      '你体内的毒术精进之力在{location}第一次觉醒。',
    ],
    effects: { intelligence: 5 },
    flags: ['chain_poisoner_childhood_0'],
    identityExclusive: 'poisoner',
  },
  {
    id: 'wx_ie_poisoner_02', category: 'identity_exclusive', minAge: 7, maxAge: 12, probability: 0.85,
    templates: [
      '作为毒师弟子，你从小就展现出与众不同的天赋。毒龙沼泽的特质在你体内蠢蠢欲动。',
      '你在{location}经历了一件改变一生的事，那是毒师弟子的命运转折点。',
      '{npc}看出了你是毒师弟子的苗子，决定暗中帮助你。',
      '你体内的毒龙沼泽之力在{location}第一次觉醒。',
    ],
    effects: { special: 5 },
    flags: ['chain_poisoner_childhood_1'],
    identityExclusive: 'poisoner',
  },
  {
    id: 'wx_ie_poisoner_03', category: 'identity_exclusive', minAge: 14, maxAge: 20, probability: 0.8,
    templates: [
      '作为毒师弟子，你在{location}遇到了以毒攻毒的试炼。',
      '你的毒师弟子身份让你在{location}陷入了困境。',
      '{npc}因为你的毒师弟子身份而对你另眼相看。',
      '你在{location}觉醒了毒师弟子特有的能力。',
    ],
    effects: { charisma: 4, luck: 3 },
    flags: ['chain_poisoner_growth_0'],
    requiredFlags: ['chain_poisoner_childhood_0'],
    identityExclusive: 'poisoner',
    chainPriority: 1,
  },
  {
    id: 'wx_ie_poisoner_04', category: 'identity_exclusive', minAge: 19, maxAge: 25, probability: 0.8,
    templates: [
      '作为毒师弟子，你在{location}遇到了以毒攻毒的试炼。',
      '你的毒师弟子身份让你在{location}陷入了困境。',
      '{npc}因为你的毒师弟子身份而对你另眼相看。',
      '你在{location}觉醒了毒师弟子特有的能力。',
    ],
    effects: { special: 6 },
    flags: ['chain_poisoner_growth_1'],
    requiredFlags: ['chain_poisoner_childhood_0'],
    identityExclusive: 'poisoner',
    chainPriority: 1,
  },
  {
    id: 'wx_ie_poisoner_05', category: 'identity_exclusive', minAge: 26, maxAge: 35, probability: 0.75,
    templates: [
      '作为毒师弟子，你在{location}迎来了人生的重要转折点——毒圣之名。',
      '你的毒师弟子之路在{location}遭遇了最大的挑战。',
      '{legend}的传说与你的毒师弟子身份产生了某种联系。',
      '你在{location}做出了一个关乎毒师弟子命运的重要决定。',
    ],
    effects: { intelligence: 8 },
    flags: ['chain_poisoner_adult_0'],
    requiredFlags: ['chain_poisoner_growth_0'],
    identityExclusive: 'poisoner',
    chainPriority: 2,
  },
  {
    id: 'wx_ie_poisoner_06', category: 'identity_exclusive', minAge: 36, maxAge: 45, probability: 0.75,
    templates: [
      '作为毒师弟子，你在{location}迎来了人生的重要转折点——毒圣之名。',
      '你的毒师弟子之路在{location}遭遇了最大的挑战。',
      '{legend}的传说与你的毒师弟子身份产生了某种联系。',
      '你在{location}做出了一个关乎毒师弟子命运的重要决定。',
    ],
    choices: [
      { text: '坚持毒师弟子之道', successRate: 0.5, successText: '你成功了，毒圣之名之力大增', failText: '你失败了，但收获经验', effects: { special: 10, strength: 5 }, failEffects: { intelligence: 5, health: -5 }, flags: ['branch_identity_poisoner_path'], failFlags: ['branch_identity_poisoner_path_fail'] },
      { text: '另辟蹊径', successRate: 0.7, successText: '你找到了新的道路', failText: '你迷失了方向', effects: { luck: 5, charisma: 5 }, failEffects: { luck: -3 }, flags: ['branch_identity_poisoner_new'], failFlags: ['branch_identity_poisoner_new_fail'] },
    ],
    flags: ['chain_poisoner_adult_1'],
    requiredFlags: ['chain_poisoner_growth_0'],
    identityExclusive: 'poisoner',
    chainPriority: 2,
  },
  {
    id: 'wx_ie_poisoner_07', category: 'identity_exclusive', minAge: 10, maxAge: 30, probability: 0.7,
    templates: [
      '作为毒师弟子，你与{legend}产生了宿命般的纠葛。',
      '你在{location}发现了关于毒师弟子起源的秘密。',
      '{npc}揭示了一个关于毒师弟子的惊天秘密。',
      '你的毒师弟子血脉在{location}发生了异变。',
    ],
    effects: { special: 10, health: -5 },
    flags: ['chain_poisoner_special_0'],
    requiredFlags: ['chain_poisoner_adult_0'],
    identityExclusive: 'poisoner',
    chainPriority: 3,
  },
  {
    id: 'wx_ie_poisoner_08', category: 'identity_exclusive', minAge: 30, maxAge: 60, probability: 0.7,
    templates: [
      '作为毒师弟子，你与{legend}产生了宿命般的纠葛。',
      '你在{location}发现了关于毒师弟子起源的秘密。',
      '{npc}揭示了一个关于毒师弟子的惊天秘密。',
      '你的毒师弟子血脉在{location}发生了异变。',
    ],
    effects: { special: 10, health: -5 },
    flags: ['chain_poisoner_special_1'],
    requiredFlags: ['chain_poisoner_adult_0'],
    identityExclusive: 'poisoner',
    chainPriority: 3,
  },
  {
    id: 'wx_ie_swordsman_01', category: 'identity_exclusive', minAge: 3, maxAge: 8, probability: 0.85,
    templates: [
      '作为剑客，你从小就展现出与众不同的天赋。剑心通明的特质在你体内蠢蠢欲动。',
      '你在{location}经历了一件改变一生的事，那是剑客的命运转折点。',
      '{npc}看出了你是剑客的苗子，决定暗中帮助你。',
      '你体内的剑心通明之力在{location}第一次觉醒。',
    ],
    effects: { intelligence: 5 },
    flags: ['chain_swordsman_childhood_0'],
    identityExclusive: 'swordsman',
  },
  {
    id: 'wx_ie_swordsman_02', category: 'identity_exclusive', minAge: 7, maxAge: 12, probability: 0.85,
    templates: [
      '作为剑客，你从小就展现出与众不同的天赋。剑冢传承的特质在你体内蠢蠢欲动。',
      '你在{location}经历了一件改变一生的事，那是剑客的命运转折点。',
      '{npc}看出了你是剑客的苗子，决定暗中帮助你。',
      '你体内的剑冢传承之力在{location}第一次觉醒。',
    ],
    effects: { intelligence: 5 },
    flags: ['chain_swordsman_childhood_1'],
    identityExclusive: 'swordsman',
  },
  {
    id: 'wx_ie_swordsman_03', category: 'identity_exclusive', minAge: 14, maxAge: 20, probability: 0.8,
    templates: [
      '作为剑客，你在{location}遇到了人剑合一的试炼。',
      '你的剑客身份让你在{location}陷入了困境。',
      '{npc}因为你的剑客身份而对你另眼相看。',
      '你在{location}觉醒了剑客特有的能力。',
    ],
    effects: { strength: 6 },
    flags: ['chain_swordsman_growth_0'],
    requiredFlags: ['chain_swordsman_childhood_0'],
    identityExclusive: 'swordsman',
    chainPriority: 1,
  },
  {
    id: 'wx_ie_swordsman_04', category: 'identity_exclusive', minAge: 19, maxAge: 25, probability: 0.8,
    templates: [
      '作为剑客，你在{location}遇到了人剑合一的试炼。',
      '你的剑客身份让你在{location}陷入了困境。',
      '{npc}因为你的剑客身份而对你另眼相看。',
      '你在{location}觉醒了剑客特有的能力。',
    ],
    effects: { special: 6 },
    flags: ['chain_swordsman_growth_1'],
    requiredFlags: ['chain_swordsman_childhood_0'],
    identityExclusive: 'swordsman',
    chainPriority: 1,
  },
  {
    id: 'wx_ie_swordsman_05', category: 'identity_exclusive', minAge: 26, maxAge: 35, probability: 0.75,
    templates: [
      '作为剑客，你在{location}迎来了人生的重要转折点——剑神之路。',
      '你的剑客之路在{location}遭遇了最大的挑战。',
      '{legend}的传说与你的剑客身份产生了某种联系。',
      '你在{location}做出了一个关乎剑客命运的重要决定。',
    ],
    effects: { intelligence: 8 },
    flags: ['chain_swordsman_adult_0'],
    requiredFlags: ['chain_swordsman_growth_0'],
    identityExclusive: 'swordsman',
    chainPriority: 2,
  },
  {
    id: 'wx_ie_swordsman_06', category: 'identity_exclusive', minAge: 36, maxAge: 45, probability: 0.75,
    templates: [
      '作为剑客，你在{location}迎来了人生的重要转折点——剑神之路。',
      '你的剑客之路在{location}遭遇了最大的挑战。',
      '{legend}的传说与你的剑客身份产生了某种联系。',
      '你在{location}做出了一个关乎剑客命运的重要决定。',
    ],
    choices: [
      { text: '坚持剑客之道', successRate: 0.5, successText: '你成功了，剑神之路之力大增', failText: '你失败了，但收获经验', effects: { special: 10, strength: 5 }, failEffects: { intelligence: 5, health: -5 }, flags: ['branch_identity_swordsman_path'], failFlags: ['branch_identity_swordsman_path_fail'] },
      { text: '另辟蹊径', successRate: 0.7, successText: '你找到了新的道路', failText: '你迷失了方向', effects: { luck: 5, charisma: 5 }, failEffects: { luck: -3 }, flags: ['branch_identity_swordsman_new'], failFlags: ['branch_identity_swordsman_new_fail'] },
    ],
    flags: ['chain_swordsman_adult_1'],
    requiredFlags: ['chain_swordsman_growth_0'],
    identityExclusive: 'swordsman',
    chainPriority: 2,
  },
  {
    id: 'wx_ie_swordsman_07', category: 'identity_exclusive', minAge: 10, maxAge: 30, probability: 0.7,
    templates: [
      '作为剑客，你与{legend}产生了宿命般的纠葛。',
      '你在{location}发现了关于剑客起源的秘密。',
      '{npc}揭示了一个关于剑客的惊天秘密。',
      '你的剑客血脉在{location}发生了异变。',
    ],
    effects: { special: 10, health: -5 },
    flags: ['chain_swordsman_special_0'],
    requiredFlags: ['chain_swordsman_adult_0'],
    identityExclusive: 'swordsman',
    chainPriority: 3,
  },
  {
    id: 'wx_ie_swordsman_08', category: 'identity_exclusive', minAge: 30, maxAge: 60, probability: 0.7,
    templates: [
      '作为剑客，你与{legend}产生了宿命般的纠葛。',
      '你在{location}发现了关于剑客起源的秘密。',
      '{npc}揭示了一个关于剑客的惊天秘密。',
      '你的剑客血脉在{location}发生了异变。',
    ],
    effects: { intelligence: 10 },
    flags: ['chain_swordsman_special_1'],
    requiredFlags: ['chain_swordsman_adult_0'],
    identityExclusive: 'swordsman',
    chainPriority: 3,
  },
  {
    id: 'wx_ie_assassin_wuxia_01', category: 'identity_exclusive', minAge: 3, maxAge: 8, probability: 0.85,
    templates: [
      '作为暗器师，你从小就展现出与众不同的天赋。暗器百解的特质在你体内蠢蠢欲动。',
      '你在{location}经历了一件改变一生的事，那是暗器师的命运转折点。',
      '{npc}看出了你是暗器师的苗子，决定暗中帮助你。',
      '你体内的暗器百解之力在{location}第一次觉醒。',
    ],
    effects: { special: 5 },
    flags: ['chain_assassin_wuxia_childhood_0'],
    identityExclusive: 'assassin_wuxia',
  },
  {
    id: 'wx_ie_assassin_wuxia_02', category: 'identity_exclusive', minAge: 7, maxAge: 12, probability: 0.85,
    templates: [
      '作为暗器师，你从小就展现出与众不同的天赋。暗杀任务的特质在你体内蠢蠢欲动。',
      '你在{location}经历了一件改变一生的事，那是暗器师的命运转折点。',
      '{npc}看出了你是暗器师的苗子，决定暗中帮助你。',
      '你体内的暗杀任务之力在{location}第一次觉醒。',
    ],
    effects: { strength: 4, luck: 2 },
    flags: ['chain_assassin_wuxia_childhood_1'],
    identityExclusive: 'assassin_wuxia',
  },
  {
    id: 'wx_ie_assassin_wuxia_03', category: 'identity_exclusive', minAge: 14, maxAge: 20, probability: 0.8,
    templates: [
      '作为暗器师，你在{location}遇到了明器暗器的试炼。',
      '你的暗器师身份让你在{location}陷入了困境。',
      '{npc}因为你的暗器师身份而对你另眼相看。',
      '你在{location}觉醒了暗器师特有的能力。',
    ],
    effects: { strength: 6 },
    flags: ['chain_assassin_wuxia_growth_0'],
    requiredFlags: ['chain_assassin_wuxia_childhood_0'],
    identityExclusive: 'assassin_wuxia',
    chainPriority: 1,
  },
  {
    id: 'wx_ie_assassin_wuxia_04', category: 'identity_exclusive', minAge: 19, maxAge: 25, probability: 0.8,
    templates: [
      '作为暗器师，你在{location}遇到了明器暗器的试炼。',
      '你的暗器师身份让你在{location}陷入了困境。',
      '{npc}因为你的暗器师身份而对你另眼相看。',
      '你在{location}觉醒了暗器师特有的能力。',
    ],
    effects: { strength: 6 },
    flags: ['chain_assassin_wuxia_growth_1'],
    requiredFlags: ['chain_assassin_wuxia_childhood_0'],
    identityExclusive: 'assassin_wuxia',
    chainPriority: 1,
  },
  {
    id: 'wx_ie_assassin_wuxia_05', category: 'identity_exclusive', minAge: 26, maxAge: 35, probability: 0.75,
    templates: [
      '作为暗器师，你在{location}迎来了人生的重要转折点——暗器之王。',
      '你的暗器师之路在{location}遭遇了最大的挑战。',
      '{legend}的传说与你的暗器师身份产生了某种联系。',
      '你在{location}做出了一个关乎暗器师命运的重要决定。',
    ],
    effects: { intelligence: 8 },
    flags: ['chain_assassin_wuxia_adult_0'],
    requiredFlags: ['chain_assassin_wuxia_growth_0'],
    identityExclusive: 'assassin_wuxia',
    chainPriority: 2,
  },
  {
    id: 'wx_ie_assassin_wuxia_06', category: 'identity_exclusive', minAge: 36, maxAge: 45, probability: 0.75,
    templates: [
      '作为暗器师，你在{location}迎来了人生的重要转折点——暗器之王。',
      '你的暗器师之路在{location}遭遇了最大的挑战。',
      '{legend}的传说与你的暗器师身份产生了某种联系。',
      '你在{location}做出了一个关乎暗器师命运的重要决定。',
    ],
    choices: [
      { text: '坚持暗器师之道', successRate: 0.5, successText: '你成功了，暗器之王之力大增', failText: '你失败了，但收获经验', effects: { special: 10, strength: 5 }, failEffects: { intelligence: 5, health: -5 }, flags: ['branch_identity_assassin_wuxia_path'], failFlags: ['branch_identity_assassin_wuxia_path_fail'] },
      { text: '另辟蹊径', successRate: 0.7, successText: '你找到了新的道路', failText: '你迷失了方向', effects: { luck: 5, charisma: 5 }, failEffects: { luck: -3 }, flags: ['branch_identity_assassin_wuxia_new'], failFlags: ['branch_identity_assassin_wuxia_new_fail'] },
    ],
    flags: ['chain_assassin_wuxia_adult_1'],
    requiredFlags: ['chain_assassin_wuxia_growth_0'],
    identityExclusive: 'assassin_wuxia',
    chainPriority: 2,
  },
  {
    id: 'wx_ie_assassin_wuxia_07', category: 'identity_exclusive', minAge: 10, maxAge: 30, probability: 0.7,
    templates: [
      '作为暗器师，你与{legend}产生了宿命般的纠葛。',
      '你在{location}发现了关于暗器师起源的秘密。',
      '{npc}揭示了一个关于暗器师的惊天秘密。',
      '你的暗器师血脉在{location}发生了异变。',
    ],
    effects: { strength: 8, luck: 5 },
    flags: ['chain_assassin_wuxia_special_0'],
    requiredFlags: ['chain_assassin_wuxia_adult_0'],
    identityExclusive: 'assassin_wuxia',
    chainPriority: 3,
  },
  {
    id: 'wx_ie_assassin_wuxia_08', category: 'identity_exclusive', minAge: 30, maxAge: 60, probability: 0.7,
    templates: [
      '作为暗器师，你与{legend}产生了宿命般的纠葛。',
      '你在{location}发现了关于暗器师起源的秘密。',
      '{npc}揭示了一个关于暗器师的惊天秘密。',
      '你的暗器师血脉在{location}发生了异变。',
    ],
    effects: { strength: 8, luck: 5 },
    flags: ['chain_assassin_wuxia_special_1'],
    requiredFlags: ['chain_assassin_wuxia_adult_0'],
    identityExclusive: 'assassin_wuxia',
    chainPriority: 3,
  },
  {
    id: 'wx_te_01', category: 'trash_exclusive', minAge: 0, maxAge: 6, probability: 0.9,
    templates: [
      '你被检测出武学废材，全村人都对你投来怜悯的目光。{npc}摇头叹息："这孩子废了。"',
      '其他孩子在{location}修炼时，你只能在一旁看着，因为你的身体根本无法吸收灵气。',
      '你的父母因为你的武学废材体质而愁眉不展，{npc}劝他们放弃对你的期望。',
    ],
    effects: { special: -3, strength: -2, intelligence: 2 },
    flags: ['trash_childhood_start'],
    talentExclusive: 'trash',
  },
  {
    id: 'wx_te_02', category: 'trash_exclusive', minAge: 4, maxAge: 10, probability: 0.85,
    templates: [
      '你在{location}被同龄人欺负，他们嘲笑你是武学废材的废物。你握紧拳头，暗暗发誓要变强。',
      '{npc}偷偷塞给你一本基础功法，说是"死马当活马医"。你如获至宝，日夜研读。',
      '你在{location}发现了一本破旧的书，虽然字迹模糊但你还是坚持抄了下来。',
    ],
    effects: { intelligence: 3, strength: 2, luck: 1 },
    flags: ['trash_childhood_1'],
    requiredFlags: ['trash_childhood_start'],
    talentExclusive: 'trash',
  },
  {
    id: 'wx_te_03', category: 'trash_exclusive', minAge: 12, maxAge: 18, probability: 0.8,
    templates: [
      '你按照那本破书上的方法在{location}修炼，进展缓慢但从未放弃。{npc}惊讶地发现你的气息变强了。',
      '别的天才一天能完成的修炼，你需要一个月。但你用十倍的时间来弥补，在{location}日复一日。',
      '你在{location}找到了一种适合武学废材体质的特殊修炼方式，虽然痛苦但有效。',
    ],
    effects: { strength: 4, intelligence: 3, special: 2 },
    flags: ['trash_growth_0'],
    requiredFlags: ['trash_childhood_1'],
    talentExclusive: 'trash',
  },
  {
    id: 'wx_te_04', category: 'trash_exclusive', minAge: 15, maxAge: 22, probability: 0.75,
    templates: [
      '你在{location}救了一个受伤的{npc}，他感激之下传授了你一套独门的炼体之术。',
      '{npc}被你的毅力打动，决定收你为记名弟子。你终于有了自己的师父！',
      '你在{location}苦修多年，虽然境界不高，但肉身强度已经远超同阶。',
    ],
    effects: { strength: 6, health: 5, charisma: 2 },
    flags: ['trash_growth_1'],
    requiredFlags: ['trash_growth_0'],
    talentExclusive: 'trash',
  },
  {
    id: 'wx_te_05', category: 'trash_exclusive', minAge: 18, maxAge: 25, probability: 0.7,
    templates: [
      '你在{location}遇到了一个神秘的{npc}，他说你的武学废材体质其实另有玄机。',
      '经过多年的积累，你在{location}突然有了顿悟——原来修炼不止一条路！',
      '{legend}的残魂在{location}与你相遇，说你是万年一遇的"大器晚成"之命。',
    ],
    effects: { intelligence: 5, luck: 5, special: 3 },
    flags: ['trash_growth_2'],
    requiredFlags: ['trash_growth_1'],
    talentExclusive: 'trash',
  },
  {
    id: 'wx_te_06', category: 'trash_exclusive', minAge: 26, maxAge: 35, probability: 0.75,
    templates: [
      '你在{location}参加了一场比试，虽然境界最低，但凭借坚韧的意志打败了数名对手，引起了轰动。',
      '你的修炼方式自成一派，{npc}说你是"以凡人之躯比肩神明"。',
      '你在{location}展示了你独创的功法，所有人都震惊了——原来武学废材也能这么强！',
    ],
    effects: { strength: 6, charisma: 5, special: 4 },
    flags: ['trash_adult_0'],
    requiredFlags: ['trash_growth_2'],
    talentExclusive: 'trash',
  },
  {
    id: 'wx_te_07', category: 'trash_exclusive', minAge: 30, maxAge: 40, probability: 0.7,
    templates: [
      '那些曾经嘲笑你的人在{location}看到你，全都目瞪口呆。你已经超越了他们中的大多数。',
      '{npc}邀请你加入一个重要组织，你的武学废材之名开始传开。',
      '你在{location}建立了自己的修炼体系，吸引了不少同样有天赋缺陷的人前来学习。',
    ],
    effects: { charisma: 6, intelligence: 4, luck: 3 },
    flags: ['trash_adult_1'],
    requiredFlags: ['trash_adult_0'],
    talentExclusive: 'trash',
  },
  {
    id: 'wx_te_08', category: 'trash_exclusive', minAge: 35, maxAge: 45, probability: 0.65,
    templates: [
      '你在{location}面对昔日最大的仇人，对方依然嘲笑你的武学废材体质。',
      '{legend}的传承之地开启，你说服众人让你这个"废物"也进去试试。',
      '你在{location}做出了一个大胆的决定——要用自己的方式证明武学废材不是终点。',
    ],
    effects: { strength: 5, luck: 5, special: 3 },
    flags: ['trash_adult_2'],
    requiredFlags: ['trash_adult_1'],
    talentExclusive: 'trash',
  },
  {
    id: 'wx_te_09', category: 'trash_exclusive', minAge: 28, maxAge: 42, probability: 0.6,
    templates: [
      '宗门大比的日子到了，你在{location}面对所有人的质疑，毅然报名参加。',
      '这是你证明自己的最好机会，{npc}暗中为你加油。',
      '{legend}的预言提到了一个"废物"将改变世界，所有人都看着你。',
    ],
    effects: { strength: 3 },
    choices: [
      { text: '全力一战', successRate: 0.4, successText: '你以弱胜强，创造了不可思议的奇迹！全场沸腾！', failText: '你拼尽全力但还是输了，虽然败了但赢得了尊重', effects: { strength: 10, charisma: 8, special: 5 }, failEffects: { strength: 5, charisma: 3, health: -15 }, flags: ['branch_trash_fight'], failFlags: ['branch_trash_fight_fail'] },
      { text: '智取巧胜', successRate: 0.6, successText: '你利用对手的轻敌，以巧取胜！', failText: '你的计策被识破，狼狈落败', effects: { intelligence: 8, luck: 5 }, failEffects: { charisma: -3, health: -10 }, flags: ['branch_trash_trick'], failFlags: ['branch_trash_trick_fail'] },
    ],
    flags: ['trash_climax_0'],
    requiredFlags: ['trash_adult_1'],
    talentExclusive: 'trash',
    chainPriority: 2,
  },
  {
    id: 'wx_te_10', category: 'trash_exclusive', minAge: 35, maxAge: 50, probability: 0.55,
    templates: [
      '你在{location}获得了{legend}的认可，TA说你的道路虽然艰难，但终点比任何人都高。',
      '一位隐世高人在{location}看中了你的毅力，决定传授你绝世功法。',
      '你发现了改变武学废材体质的方法，但需要冒极大的风险。',
    ],
    effects: { special: 5 },
    choices: [
      { text: '冒险改变体质', successRate: 0.35, successText: '你成功了！你的体质发生了翻天覆地的变化，从此一飞冲天！', failText: '改造失败，你受了重伤，但意志更加坚定', effects: { special: 15, strength: 5, health: -10 }, failEffects: { health: -25, strength: 3 }, flags: ['branch_trash_transform'], failFlags: ['branch_trash_transform_fail'] },
      { text: '坚持原有道路', successRate: 0.75, successText: '你的坚持得到了回报，你的功法大成，自成一派！', failText: '进展依然缓慢，但你没有放弃', effects: { intelligence: 8, strength: 5 }, failEffects: { intelligence: 3 }, flags: ['branch_trash_persist'], failFlags: ['branch_trash_persist_fail'] },
    ],
    flags: ['trash_climax_1'],
    requiredFlags: ['trash_climax_0'],
    talentExclusive: 'trash',
    chainPriority: 2,
  },
  {
    id: 'wx_te_11', category: 'trash_exclusive', minAge: 40, maxAge: 55, probability: 0.5,
    templates: [
      '你在{location}一战成名，所有人都知道那个武学废材的废物逆袭成了强者。',
      '你的故事传遍了大陆，无数武学废材的人把你当作偶像。',
      '{npc}跪在你面前，为当年嘲笑你而道歉。你扶起他，说："我走的路，比你们都长。"',
    ],
    effects: { charisma: 10, luck: 5, special: 5 },
    flags: ['trash_climax_2'],
    requiredFlags: ['trash_climax_1'],
    talentExclusive: 'trash',
    chainPriority: 3,
  },
  {
    id: 'wx_te_12', category: 'trash_exclusive', minAge: 45, maxAge: 60, probability: 0.45,
    templates: [
      '你在{location}达到了前所未有的高度，证明了武学废材也能登临绝巅。',
      '你成为了{legend}级别的存在，后人将你的故事传颂千古。',
      '你回头看向起点，那个在{location}被嘲笑的孩子，如今已是传奇。',
    ],
    effects: { strength: 8, intelligence: 8, charisma: 8, special: 8 },
    flags: ['trash_legend'],
    requiredFlags: ['trash_climax_2'],
    talentExclusive: 'trash',
    chainPriority: 3,
  },
  {
    id: 'wx_te_13', category: 'trash_exclusive', minAge: 55, maxAge: 80, probability: 0.55,
    templates: [
      '你在{location}收徒传道，专门招收那些被视为废材的孩子。你说："天赋决定起点，但毅力决定终点。"',
      '你的弟子中出了不少人才，{npc}感叹你创造了一个奇迹。',
      '你在{location}写下了自己的修炼心得，希望能帮助更多武学废材的人。',
    ],
    effects: { charisma: 6, intelligence: 5 },
    flags: ['trash_elder_0'],
    requiredFlags: ['trash_legend'],
    talentExclusive: 'trash',
  },
  {
    id: 'wx_te_14', category: 'trash_exclusive', minAge: 60, maxAge: 90, probability: 0.5,
    templates: [
      '你的大限将至，但你毫无遗憾。{npc}问你后不后悔走这条艰难的路。',
      '你微笑着说："如果重来一次，我还是会选择做那个武学废材的废物。"',
      '你在{location}度过了平静的最后岁月，每天都有人来听你讲当年的故事。',
    ],
    effects: { charisma: 5, health: -5 },
    flags: ['trash_elder_1'],
    requiredFlags: ['trash_elder_0'],
    talentExclusive: 'trash',
  },
  {
    id: 'wx_te_15', category: 'trash_exclusive', minAge: 70, maxAge: 100, probability: 0.45,
    templates: [
      '你离世的那天，{location}下起了金色的雨。无数人自发前来为你送行。',
      '{legend}亲自前来接引你的灵魂，说你是万古以来第一个以武学废材之躯证道的人。',
      '你的名字被刻在了{location}的最高处，激励着后世所有被视为废材的人。',
    ],
    effects: { charisma: 10, luck: 10 },
    flags: ['trash_ending'],
    requiredFlags: ['trash_elder_1'],
    talentExclusive: 'trash',
  },
];
